Repository wolfi-dev/os, pull requests merged in 2024-10, with the labels that each got.

#29760 python 3.13 - batch 6 packages.
  py3-attrs.yaml
  py3-click.yaml
  py3-filelock.yaml
  py3-frozenlist.yaml
  py3-fsspec.yaml
  py3-httpcore.yaml
  py3-iniconfig.yaml
  py3-meson-python.yaml
  py3-platformdirs.yaml
  py3-pydantic.yaml
  py3-scikit-build.yaml
  py3-tqdm.yaml
  py3-urllib3.yaml
  py3-yarl.yaml
Labels: staging-build

#29753 py3-pandas: multiversionize
  py3-pandas.yaml
Labels: staging-build

#29848 Add provider for csi-snapshotter 8.1
  kubernetes-csi-external-snapshotter-8.1.yaml
Labels: squad:sustaining, squad:lifecycle

#30360 Fix missing "pc=" provides that are otherwise referenced as Required
  jsoncpp.yaml
  leptonica.yaml
  libpng.yaml
  ncurses.yaml
  shared-mime-info.yaml
  utmps.yaml
  utmps/utmps.pc
  xorgproto.yaml
Labels: blocked

#31058 smartypants: rebuild for new melange SCA metadata
  smartypants.yaml
Labels: automated pr, melange

#31056 py3-libevdev: rebuild for new melange SCA metadata
  py3-libevdev.yaml
Labels: automated pr, melange

#31053 openjdk-12: rebuild for new melange SCA metadata
  openjdk-12.yaml
Labels: automated pr, melange

#31059 Prevent rebuild of libxcrypt breaking the world
  libxcrypt.yaml
Labels: melange

#31049 clang-15: rebuild for new melange SCA metadata
  clang-15.yaml
Labels: automated pr, melange

#31064 checksec: rebuild for new melange SCA metadata
  checksec.yaml
Labels: automated pr, melange

#31065 cowsay: rebuild for new melange SCA metadata
  cowsay.yaml
Labels: automated pr, melange

#31066 exiftool: rebuild for new melange SCA metadata
  exiftool.yaml
Labels: automated pr, melange

#31062 bats: rebuild for new melange SCA metadata
  bats.yaml
Labels: automated pr, melange

#31078 openscap: rebuild for new melange SCA metadata
  openscap.yaml
Labels: automated pr, melange

#31083 socat: rebuild for new melange SCA metadata
  socat.yaml
Labels: automated pr, melange

#31085 trafficserver-9: rebuild for new melange SCA metadata
  trafficserver-9.yaml
Labels: automated pr, melange

#31086 valgrind: rebuild for new melange SCA metadata
  valgrind.yaml
Labels: automated pr, melange

#31075 node-gyp: rebuild for new melange SCA metadata
  node-gyp.yaml
Labels: automated pr, melange

#31076 novnc: rebuild for new melange SCA metadata
  novnc.yaml
Labels: automated pr, melange

#31087 wait-for-it: rebuild for new melange SCA metadata
  wait-for-it.yaml
Labels: automated pr, melange

#31146 cronie: rebuild for new melange SCA metadata PKGDESC
  cronie.yaml
Labels: automated pr, melange

#31145 boost: rebuild for new melange SCA metadata PKGDESC
  boost.yaml
Labels: automated pr, melange

#31142 py3-oauthenticator: rebuild for new melange SCA metadata binary depend
  py3-oauthenticator.yaml
Labels: automated pr, melange

#31136 bison: rebuild for new melange SCA metadata binary depend
  bison.yaml
Labels: automated pr, melange

#31140 mitmproxy: rebuild for new melange SCA metadata binary depend
  mitmproxy.yaml
Labels: automated pr, melange

#31128 ruby3.2-validate_email: rebuild for new melange SCA metadata
  ruby3.2-validate_email.yaml
Labels: automated pr, melange

#31127 ruby3.2-treetop: rebuild for new melange SCA metadata
  ruby3.2-treetop.yaml
Labels: automated pr, melange

#31125 ruby3.2-snaky_hash: rebuild for new melange SCA metadata
  ruby3.2-snaky_hash.yaml
Labels: automated pr, melange

#31123 ruby3.2-redis-namespace: rebuild for new melange SCA metadata
  ruby3.2-redis-namespace.yaml
Labels: automated pr, melange

#31061 autoconf: rebuild for new melange SCA metadata
  autoconf.yaml
Labels: automated pr, melange

#31060 ack: rebuild for new melange SCA metadata
  ack.yaml
Labels: automated pr, melange

#31054 openjdk-7: rebuild for new melange SCA metadata
  openjdk-7.yaml
Labels: automated pr, melange

#31141 net-snmp: rebuild for new melange SCA metadata binary depend
  net-snmp.yaml
Labels: automated pr, melange

#31137 iperf: rebuild for new melange SCA metadata binary depend
  iperf.yaml
Labels: automated pr, melange

#31116 ruby3.2-oauth2: rebuild for new melange SCA metadata
  ruby3.2-oauth2.yaml
Labels: automated pr, melange

#31134 sqlmap: rebuild for new melange SCA metadata LICENSE change
  sqlmap.yaml
Labels: automated pr, melange

#31133 py3-beautifulsoup4: rebuild for new melange SCA metadata LICENSE change
  py3-beautifulsoup4.yaml
Labels: automated pr, melange

#31131 dns-root-hints: rebuild for new melange SCA metadata LICENSE change
  dns-root-hints.yaml
Labels: automated pr, melange

#31126 ruby3.2-swd: rebuild for new melange SCA metadata
  ruby3.2-swd.yaml
Labels: automated pr, melange

#31124 ruby3.2-sinatra: rebuild for new melange SCA metadata
  ruby3.2-sinatra.yaml
Labels: automated pr, melange

#31122 ruby3.2-redis-client: rebuild for new melange SCA metadata
  ruby3.2-redis-client.yaml
Labels: automated pr, melange

#31120 ruby3.2-rack-oauth2: rebuild for new melange SCA metadata
  ruby3.2-rack-oauth2.yaml
Labels: automated pr, melange

#31119 ruby3.2-pry: rebuild for new melange SCA metadata
  ruby3.2-pry.yaml
Labels: automated pr, melange

#31118 ruby3.2-openid_connect: rebuild for new melange SCA metadata
  ruby3.2-openid_connect.yaml
Labels: automated pr, melange

#31115 ruby3.2-net-protocol: rebuild for new melange SCA metadata
  ruby3.2-net-protocol.yaml
Labels: automated pr, melange

#31114 ruby3.2-net-http-persistent: rebuild for new melange SCA metadata
  ruby3.2-net-http-persistent.yaml
Labels: automated pr, melange

#31113 ruby3.2-manticore: rebuild for new melange SCA metadata
  ruby3.2-manticore.yaml
Labels: automated pr, melange

#31112 ruby3.2-mail: rebuild for new melange SCA metadata
  ruby3.2-mail.yaml
Labels: automated pr, melange

#31111 ruby3.2-logstash-mixin-ecs_compatibility_support: rebuild for new melange SCA metadata
  ruby3.2-logstash-mixin-ecs_compatibility_support.yaml
Labels: automated pr, melange

#31110 ruby3.2-fluent-config-regexp-type: rebuild for new melange SCA metadata
  ruby3.2-fluent-config-regexp-type.yaml
Labels: automated pr, melange

#31138 linenoise: rebuild for new melange SCA metadata binary depend
  linenoise.yaml
Labels: automated pr, melange

#31108 ruby3.2-faraday-excon: rebuild for new melange SCA metadata
  ruby3.2-faraday-excon.yaml
Labels: automated pr, melange

#31106 ruby3.2-chronic_duration: rebuild for new melange SCA metadata
  ruby3.2-chronic_duration.yaml
Labels: automated pr, melange

#31099 fluent-plugin-splunk-hec: rebuild for new melange SCA metadata
  fluent-plugin-splunk-hec.yaml
Labels: automated pr, melange

#31098 fluent-plugin-s3: rebuild for new melange SCA metadata
  fluent-plugin-s3.yaml
Labels: automated pr, melange

#31097 fluent-plugin-rewrite-tag-filter: rebuild for new melange SCA metadata
  fluent-plugin-rewrite-tag-filter.yaml
Labels: automated pr, melange

#31095 fluent-plugin-out-http: rebuild for new melange SCA metadata
  fluent-plugin-out-http.yaml
Labels: automated pr, melange

#31094 fluent-plugin-newrelic: rebuild for new melange SCA metadata
  fluent-plugin-newrelic.yaml
Labels: automated pr, melange

#31070 intltool: rebuild for new melange SCA metadata
  intltool.yaml
Labels: automated pr, melange

#31052 openjdk-10: rebuild for new melange SCA metadata
  openjdk-10.yaml
Labels: automated pr, melange

#31073 mariadb-11.5: rebuild for new melange SCA metadata
  mariadb-11.5.yaml
Labels: automated pr, melange

#31129 ruby3.2-validate_url: rebuild for new melange SCA metadata
  ruby3.2-validate_url.yaml
Labels: automated pr, melange

#31109 ruby3.2-faraday-follow_redirects: rebuild for new melange SCA metadata
  ruby3.2-faraday-follow_redirects.yaml
Labels: automated pr, melange

#31090 fluent-plugin-cloudwatch-logs: rebuild for new melange SCA metadata
  fluent-plugin-cloudwatch-logs.yaml
Labels: automated pr, melange

#31080 qt5-qtbase: rebuild for new melange SCA metadata
  qt5-qtbase.yaml
Labels: automated pr, melange

#31092 fluent-plugin-elasticsearch: rebuild for new melange SCA metadata
  fluent-plugin-elasticsearch.yaml
Labels: automated pr, melange

#31084 swaks: rebuild for new melange SCA metadata
  swaks.yaml
Labels: automated pr, melange

#31143 samurai: rebuild for new melange SCA metadata binary depend
  samurai.yaml
Labels: automated pr, melange

#31135 sshfs: rebuild for new melange SCA metadata LICENSE change
  sshfs.yaml
Labels: automated pr, melange

#31139 m4: rebuild for new melange SCA metadata binary depend
  m4.yaml
Labels: automated pr, melange

#31132 dnssec-root: rebuild for new melange SCA metadata LICENSE change
  dnssec-root.yaml
Labels: automated pr, melange

#31121 ruby3.2-rack-protection: rebuild for new melange SCA metadata
  ruby3.2-rack-protection.yaml
Labels: automated pr, melange

#31093 fluent-plugin-label-router: rebuild for new melange SCA metadata
  fluent-plugin-label-router.yaml
Labels: automated pr, melange

#31068 hdf5: rebuild for new melange SCA metadata
  hdf5.yaml
Labels: automated pr, melange

#31057 py3-sphinxcontrib-jsmath: rebuild for new melange SCA metadata
  py3-sphinxcontrib-jsmath.yaml
Labels: automated pr, melange

#31069 help2man: rebuild for new melange SCA metadata
  help2man.yaml
Labels: automated pr, melange

#31186 Rsync glow up
  rsync.yaml
  xxhash.yaml
Labels: fetch2checkout, service:ftbfs, melange

#31103 ruby3.2-aws-sdk-s3: rebuild for new melange SCA metadata
  ruby3.2-aws-sdk-s3.yaml
Labels: automated pr, service:ftbfs, melange

#31101 ruby3.2-aws-sdk-core: rebuild for new melange SCA metadata
  ruby3.2-aws-sdk-core.yaml
Labels: automated pr, service:ftbfs, melange

#31100 ruby3.2-aws-sdk-cloudwatchlogs: rebuild for new melange SCA metadata
  ruby3.2-aws-sdk-cloudwatchlogs.yaml
Labels: automated pr, service:ftbfs, melange

#31104 ruby3.2-aws-sdk-sqs: rebuild for new melange SCA metadata
  ruby3.2-aws-sdk-sqs.yaml
Labels: automated pr, service:ftbfs, melange

#31096 fluent-plugin-record-modifier: rebuild for new melange SCA metadata
  fluent-plugin-record-modifier.yaml
Labels: automated pr, melange

#31081 rarian: rebuild for new melange SCA metadata
  rarian.yaml
Labels: automated pr, melange

#31077 openresty: rebuild for new melange SCA metadata
  openresty.yaml
Labels: automated pr, melange

#31190 mercurial: do not install hgk (tk GUI) resolves FTBFS
  mercurial.yaml
Labels: service:ftbfs

#31051 gpsd: rebuild for new melange SCA metadata
  gpsd.yaml
Labels: automated pr, service:ftbfs, squad:sustaining, melange

#30645 add logstash bitnami compat
  logstash-8.yaml
Labels: P0

#31617 Remove wasker from Wolfi
  wasker.yaml
Labels: squad:sustaining

#30980 Misc openssf enablement
  R.yaml
  aom.yaml
  bazel-5.yaml
  bazel-6.yaml
  brew.yaml
  ca-certificates.yaml
  cairo.yaml
  cdparanoia.yaml
  cmake-bootstrap.yaml
  cmake.yaml
  expat.yaml
  falco-libs.yaml
  flux-image-automation-controller.yaml
  flux-source-controller.yaml
  fluxbox.yaml
  gc.yaml
  go-1.20.yaml
  haproxy-3.0.yaml
  http-parser.yaml
  iperf.yaml
  iperf3.yaml
  ipfs.yaml
  isl.yaml
  java-gcj-compat.yaml
  jitsucom-jitsu.yaml
  libaio.yaml
Labels: staging-build

#31702 python-3.13: cherrypick CVE-2024-9287 fixes
  python-3.13.yaml
Labels: staging-build

#31743 cifs-utils.yaml: Add openssf-options
  cifs-utils.yaml
Labels: automated pr, openssf-compiler-options

#31747 libevdev.yaml: Add openssf-options
  libevdev.yaml
Labels: automated pr, openssf-compiler-options

#31750 py3-onnx.yaml: Add openssf-options
  py3-onnx.yaml
Labels: automated pr, openssf-compiler-options

#31749 serf.yaml: Add openssf-options
  serf.yaml
Labels: automated pr, openssf-compiler-options

#31748 php-8.1-ddtrace.yaml: Add openssf-options
  php-8.1-ddtrace.yaml
Labels: automated pr, openssf-compiler-options

#31734 btop.yaml: Add openssf-options
  btop.yaml
Labels: automated pr, openssf-compiler-options

#31735 sshpass.yaml: Add openssf-options
  sshpass.yaml
Labels: automated pr, openssf-compiler-options

#31731 py3-logbook.yaml: Add openssf-options
  py3-logbook.yaml
Labels: automated pr, openssf-compiler-options

#31732 py3-simplejson.yaml: Add openssf-options
  py3-simplejson.yaml
Labels: automated pr, openssf-compiler-options

#31746 spark-operator.yaml: Add openssf-options
  spark-operator.yaml
Labels: automated pr, openssf-compiler-options

#31745 async-profiler.yaml: Add openssf-options
  async-profiler.yaml
Labels: automated pr, openssf-compiler-options

#31744 libnetfilter_conntrack.yaml: Add openssf-options
  libnetfilter_conntrack.yaml
Labels: automated pr, openssf-compiler-options

#31722 fastjar.yaml: Add openssf-options
  fastjar.yaml
Labels: automated pr, openssf-compiler-options

#31724 xz.yaml: Add openssf-options
  xz.yaml
Labels: automated pr, openssf-compiler-options

#31726 sdp-k8s-injector.yaml: Add openssf-options
  sdp-k8s-injector.yaml
Labels: automated pr, openssf-compiler-options

#31721 libpaper.yaml: Add openssf-options
  libpaper.yaml
Labels: automated pr, openssf-compiler-options

#31723 rust-1.75.yaml: Add openssf-options
  rust-1.75.yaml
Labels: automated pr, openssf-compiler-options

#31725 py3-libcst.yaml: Add openssf-options
  py3-libcst.yaml
Labels: automated pr, openssf-compiler-options

#31751 tk.yaml: Add openssf-options
  tk.yaml
Labels: automated pr, openssf-compiler-options

#31753 gpsd.yaml: Add openssf-options
  gpsd.yaml
Labels: automated pr, openssf-compiler-options

#31756 nmap.yaml: Add openssf-options
  nmap.yaml
Labels: automated pr, openssf-compiler-options

#31752 gdb.yaml: Add openssf-options
  gdb.yaml
Labels: automated pr, openssf-compiler-options

#31757 what-utils.yaml: Add openssf-options
  what-utils.yaml
Labels: automated pr, openssf-compiler-options

#31758 squid.yaml: Add openssf-options
  squid.yaml
Labels: automated pr, openssf-compiler-options

#31755 xh.yaml: Add openssf-options
  xh.yaml
Labels: automated pr, openssf-compiler-options

#31759 mosquitto.yaml: Add openssf-options
  mosquitto.yaml
Labels: automated pr, openssf-compiler-options

#31740 mariadb-11.5.yaml: Add openssf-options
  mariadb-11.5.yaml
Labels: automated pr, openssf-compiler-options

#31730 perl-dbi.yaml: Add openssf-options
  perl-dbi.yaml
Labels: automated pr, openssf-compiler-options

#31728 php-8.1-redis.yaml: Add openssf-options
  php-8.1-redis.yaml
Labels: automated pr, openssf-compiler-options

#31720 collectd.yaml: Add openssf-options
  collectd.yaml
Labels: automated pr, openssf-compiler-options

#31682 clang-*: Enable openssf options
  clang-15.yaml
  clang-16.yaml
  clang-17.yaml
  clang-18.yaml
  clang-19.yaml
Labels: openssf-compiler-options

#31071 jemalloc: rebuild for new melange SCA metadata
  jemalloc.yaml
Labels: automated pr, squad:sustaining, melange

#31067 flink-1.20: rebuild for new melange SCA metadata
  flink-1.20.yaml
Labels: automated pr, squad:sustaining, melange

#31852 R-s2.yaml: Add openssf-options
  R-s2.yaml
Labels: automated pr, openssf-compiler-options

#31853 R-sf.yaml: Add openssf-options
  R-sf.yaml
Labels: automated pr, openssf-compiler-options

#31855 Rcpp.yaml: Add openssf-options
  Rcpp.yaml
Labels: automated pr, openssf-compiler-options

#31854 R-wk.yaml: Add openssf-options
  R-wk.yaml
Labels: automated pr, openssf-compiler-options

#31950 bank-vaults.yaml: Add openssf-options
  bank-vaults.yaml
Labels: automated pr, openssf-compiler-options

#31952 bat.yaml: Add openssf-options
  bat.yaml
Labels: automated pr, openssf-compiler-options

#31953 bazel-7.yaml: Add openssf-options
  bazel-7.yaml
Labels: automated pr, openssf-compiler-options

#31955 berg.yaml: Add openssf-options
  berg.yaml
Labels: automated pr, openssf-compiler-options

#31954 bdftopcf.yaml: Add openssf-options
  bdftopcf.yaml
Labels: automated pr, openssf-compiler-options

#31951 bash.yaml: Add openssf-options
  bash.yaml
Labels: automated pr, openssf-compiler-options

#31969 buildkitd.yaml: Add openssf-options
  buildkitd.yaml
Labels: automated pr, openssf-compiler-options

#31972 cabextract.yaml: Add openssf-options
  cabextract.yaml
Labels: automated pr, openssf-compiler-options

#31971 bzip3.yaml: Add openssf-options
  bzip3.yaml
Labels: automated pr, openssf-compiler-options

#31970 byobu.yaml: Add openssf-options
  byobu.yaml
Labels: automated pr, openssf-compiler-options

#31960 bluez.yaml: Add openssf-options
  bluez.yaml
Labels: automated pr, openssf-compiler-options

#31957 bind.yaml: Add openssf-options
  bind.yaml
Labels: automated pr, openssf-compiler-options

#31959 bison.yaml: Add openssf-options
  bison.yaml
Labels: automated pr, openssf-compiler-options

#31958 binutils.yaml: Add openssf-options
  binutils.yaml
Labels: automated pr, openssf-compiler-options

#31962 boost.yaml: Add openssf-options
  boost.yaml
Labels: automated pr, openssf-compiler-options

#31963 botan.yaml: Add openssf-options
  botan.yaml
Labels: automated pr, openssf-compiler-options

#31965 btrfs-progs.yaml: Add openssf-options
  btrfs-progs.yaml
Labels: automated pr, openssf-compiler-options

#31964 bpftool.yaml: Add openssf-options
  bpftool.yaml
Labels: automated pr, openssf-compiler-options

#31966 bubblewrap.yaml: Add openssf-options
  bubblewrap.yaml
Labels: automated pr, openssf-compiler-options

#31945 at-spi2-core.yaml: Add openssf-options
  at-spi2-core.yaml
Labels: automated pr, openssf-compiler-options

#31944 argon2.yaml: Add openssf-options
  argon2.yaml
Labels: automated pr, openssf-compiler-options

#31947 audit.yaml: Add openssf-options
  audit.yaml
Labels: automated pr, openssf-compiler-options

#31946 atuin.yaml: Add openssf-options
  atuin.yaml
Labels: automated pr, openssf-compiler-options
