Repository wolfi-dev/os, pull requests merged in 2024-08, with the labels that each got.

#25510 Fix subpackage versioning in kuma-2.8
  kuma-2.8.yaml
Labels: bincapz/pass

#25566 adding melange tests for py3-wcmatch
  py3-wcmatch.yaml
Labels: bincapz/pass

#16713 disable NTLM in curl & wget
  curl.yaml
  wget.yaml
Labels: fips, hardening

#13417 add basic test case for cadvisor
  cadvisor.yaml
Labels: lifecycle/stale

#25873 zlib openssf
  zlib.yaml
Labels: foundations

#25869 openssl hardening
  openssl.yaml
Labels: foundations

#25870 test/hardening-check: enforce cfprotection on x86_64 by default
  busybox.yaml
  pipelines/test/hardening-check.yaml
Labels: foundations

#26423 FTBFS libevdev
  libevdev.yaml
Labels: ftbfs

#26412 ftbfs cargo-auditable
  cargo-auditable.yaml
Labels: ftbfs

#26422 FTBFS libffi
  libffi.yaml
Labels: ftbfs

#26406 gnupg glow up
  gnupg.yaml
Labels: ftbfs

#26524 FTBFS xtail
  xtail.yaml
Labels: ftbfs

#26609 FTBFS zsh
  zsh.yaml
Labels: ftbfs

#26523 FTBFS zip
  zip.yaml
  zip/06-stack-markings-to-avoid-executable-stack.patch
  zip/07-fclose-in-file-not-fclose-x.patch
  zip/08-hardening-build-fix-1.patch
  zip/09-hardening-build-fix-2.patch
  zip/10-remove-build-date.patch
  zip/12-fix-build-with-gcc-14.patch
Labels: ftbfs

#13312 add glow package to wolfi
  glow.yaml
Labels: lifecycle/stale
