Repository wolfi-dev/os, pull requests merged in 2024-01, with the labels that each got.

#8670 `dav1d/1.3.0` was failing soname checks, So I updated the epoch of downstream packages
  dav1d.yaml
  libavif.yaml
Labels: blocked

#6473 libmilter/1.0.3 package update
  libmilter.yaml
Labels: blocked

#8793 fix: py3-apache-beam + update to 2.53.0
  py3-apache-beam.yaml
Labels: blocked

#5492 feat(php-pecl-mcrypt): Improve update section to allow auto updates of mcrypt
  php-8.1-pecl-mcrypt.yaml
  php-8.2-pecl-mcrypt.yaml
Labels: lifecycle/stale

#7295 `libretls/3.8.1` package update
  libretls.yaml
Labels: hacktoberfest-accepted, soname-validated

#10079 Bump ICU to 74.2 + dependency bump
  at-spi2-core.yaml
  bluez.yaml
  harfbuzz.yaml
  icu.yaml
  icu/LICENSE
  libical.yaml
  nodejs-16.yaml
  nodejs-18.yaml
  nodejs-19.yaml
  nodejs-20.yaml
  nodejs-21.yaml
  php-8.1.yaml
  php-8.2.yaml
  php-8.3.yaml
  re2.yaml
Labels: blocked

#11278 crossplane/1.14.5-r1: cve remediation
  crossplane.yaml
Labels: automated pr

#11282 spire-server/1.8.7-r0: cve remediation
  spire-server.yaml
Labels: automated pr

#11284 argo-workflows/3.5.4-r1: cve remediation
  argo-workflows.yaml
Labels: automated pr

#11277 cert-manager-1.13/1.13.3-r1: cve remediation
  cert-manager-1.13.yaml
Labels: automated pr

#11281 cert-manager-1.11/1.11.5-r9: cve remediation
  cert-manager-1.11.yaml
Labels: automated pr

#11315 kubernetes-1.27/1.27.10-r0: cve remediation
  kubernetes-1.27.yaml
Labels: automated pr

#11351 zot/2.0.0-r1: cve remediation
  zot.yaml
Labels: automated pr

#11346 crossplane-provider-aws/0.47.1-r0: cve remediation
  crossplane-provider-aws.yaml
Labels: automated pr

#11356 flux-image-automation-controller/0.37.0-r2: cve remediation
  flux-image-automation-controller.yaml
Labels: automated pr

#11361 vault-1.13/1.13.12-r1: cve remediation
  vault-1.13.yaml
Labels: automated pr

#11358 ipfs/0.25.0-r0: cve remediation
  ipfs.yaml
Labels: automated pr

#11468 volume-modifier-for-k8s/0.2.0-r0: cve remediation
  volume-modifier-for-k8s.yaml
Labels: automated pr

#11525 skopeo/1.14.1-r0: cve remediation
  skopeo.yaml
Labels: automated pr

#11688 spire-server/1.8.7-r1: cve remediation
  spire-server.yaml
Labels: automated pr

#11700 tekton-chains/0.19.0-r5: cve remediation
  tekton-chains.yaml
Labels: automated pr

#11690 kyverno/1.11.4-r0: cve remediation
  kyverno.yaml
Labels: automated pr

#11685 falcoctl/0.7.1-r0: cve remediation
  falcoctl.yaml
Labels: automated pr

#11699 kubescape/3.0.3-r2: cve remediation
  kubescape.yaml
Labels: automated pr

#11703 kubescape/3.0.3-r3: cve remediation
  kubescape.yaml
Labels: automated pr

#11698 istio-pilot-discovery-1.19/1.19.6-r0: cve remediation
  istio-pilot-discovery-1.19.yaml
Labels: automated pr

#11696 istio-operator-1.20/1.20.2-r0: cve remediation
  istio-operator-1.20.yaml
Labels: automated pr

#11695 istio-cni-1.19/1.19.6-r0: cve remediation
  istio-cni-1.19.yaml
Labels: automated pr

#11689 istio-pilot-agent-1.20/1.20.2-r1: cve remediation
  istio-pilot-agent-1.20.yaml
Labels: automated pr

#11691 istio-pilot-discovery-1.18/1.18.7-r0: cve remediation
  istio-pilot-discovery-1.18.yaml
Labels: automated pr

#11692 istio-operator-1.19/1.19.6-r0: cve remediation
  istio-operator-1.19.yaml
Labels: automated pr

#11694 istio-pilot-agent-1.19/1.19.6-r0: cve remediation
  istio-pilot-agent-1.19.yaml
Labels: automated pr

#11687 istio-cni-1.20/1.20.2-r0: cve remediation
  istio-cni-1.20.yaml
Labels: automated pr

#11686 istio-pilot-agent-1.18/1.18.7-r0: cve remediation
  istio-pilot-agent-1.18.yaml
Labels: automated pr

#11697 istio-pilot-discovery-1.20/1.20.2-r1: cve remediation
  istio-pilot-discovery-1.20.yaml
Labels: automated pr

#11854 istio-operator-1.19/1.19.6-r1: cve remediation
  istio-operator-1.19.yaml
Labels: automated pr

#11855 istio-cni-1.19/1.19.6-r1: cve remediation
  istio-cni-1.19.yaml
Labels: automated pr

#11853 istio-pilot-discovery-1.19/1.19.6-r1: cve remediation
  istio-pilot-discovery-1.19.yaml
Labels: automated pr

#11856 mc/0.20231220.071422-r1: cve remediation
  mc.yaml
Labels: automated pr

#11851 istio-pilot-agent-1.20/1.20.2-r2: cve remediation
  istio-pilot-agent-1.20.yaml
Labels: automated pr

#11852 external-secrets-operator/0.9.11-r0: cve remediation
  external-secrets-operator.yaml
Labels: automated pr

#11849 istio-pilot-agent-1.19/1.19.6-r1: cve remediation
  istio-pilot-agent-1.19.yaml
Labels: automated pr

#11850 istio-pilot-discovery-1.18/1.18.7-r1: cve remediation
  istio-pilot-discovery-1.18.yaml
Labels: automated pr

#11846 istio-operator-1.20/1.20.2-r1: cve remediation
  istio-operator-1.20.yaml
Labels: automated pr

#11863 minio/0.20231220.010002-r1: cve remediation
  minio.yaml
Labels: automated pr

#12163 buildkitd/0.12.4-r3: cve remediation
  buildkitd.yaml
Labels: automated pr
