Repository wolfi-dev/os, pull requests merged in 2024-12, with the labels that each got.

#35563 add apicurio-registry
  apicurio-registry.yaml
  apicurio-registry/CVE-2024-31141.patch
Labels: bincapz/pass

#35625 fluent-plugin-label-router: bump to latest
  fluent-plugin-label-router.yaml
Labels: bincapz/pass

#35639 fix(repmgr): create missing dir and provide lib dir
  repmgr.yaml
Labels: bincapz/pass

#35640 Adding compat package to mirror upstream image
  splunk-otel-collector.yaml
Labels: approved-to-run

#35666 Withdraw bad vim package
  withdrawn-packages.txt
Labels: approved-to-run

#35267 Migrate teleport package to use go/build
  teleport.yaml
Labels: bincapz/pass

#35651 postgresql-bitnami: provide missing dirs
  postgresql-17-bitnami-compat.yaml
Labels: bincapz/pass

#35759 varnish-modules: rebuild varnish-modules for new varnish point release
  varnish-modules.yaml
Labels: bincapz/pass

#35760 add flux-2.4 version stream
  flux-2.4.yaml
Labels: bincapz/pass

#35761 Add QEMU package
  qemu.yaml
Labels: approved-to-run

#35796 Add run time dep for docker
  docker.yaml
Labels: bincapz/pass

#35870 add dockerd as a runtime dependency
  docker.yaml
Labels: bincapz/pass

#35882 Make lint.sh more better
  7zip.yaml
  apicurio-registry.yaml
  argo-workflows.yaml
  bird.yaml
  curl-rustls.yaml
  gperftools.yaml
  libnotify.yaml
  libnvme.yaml
  libyang.yaml
  lint.sh
  mesa.yaml
  onetbb.yaml
  openssl.yaml
  patchelf.yaml
  php-8.1-protobuf.yaml
  php-8.2-protobuf.yaml
  php-8.3-protobuf.yaml
  php-8.4-protobuf.yaml
  repmgr.yaml
  rtrlib.yaml
  scala-2.13.yaml
  tileserver-gl.yaml
  wayland-protocols.yaml
Labels: approved-to-run

#35852 protobuf dependent packages' rebuild
  grpc-1.68.yaml
  libpulsar.yaml
  opentelemetry-cpp.yaml
  protobuf-c.yaml
Labels: bincapz/pass

#35770 repmgr: rename package for version stream with postgresql
  repmgr-17.yaml
Labels: bincapz/pass

#35614 add pngquant package
  pngquant.yaml
Labels: bincapz/pass

#35623 add psmisc package
  psmisc.yaml
Labels: bincapz/blocking

#35956 Bump supervisor to fix missing EOF
  supervisor.yaml
Labels: approved-to-run

#35941 imagemagick: splitting out imagemagick-7 stream
  imagemagick-7.yaml
Labels: bincapz/pass, approved-to-run

#35957 fix(repmgr): write to stdout
  repmgr-17.yaml
Labels: bincapz/pass

#35958 py3-pybind11: Fix priorities of provides
  py3-pybind11.yaml
Labels: bincapz/pass, approved-to-run

#35742 feat(ruby): Make coinstallable
  ruby-3.1.yaml
  ruby-3.2.yaml
  ruby-3.3.yaml
Labels: bincapz/pass

#35855 Fixes symlink in opentelemetry-plugin-nginx-compat
  opentelemetry-cpp.yaml
  opentelemetry-plugin-nginx.yaml
Labels: bincapz/pass

#36033 fix(repmgr): provide missing conf.d dir
  repmgr-17.yaml
Labels: bincapz/pass

#36038 chore: Rebuild Ruby 3.1-3.3
  ruby-3.1.yaml
  ruby-3.2.yaml
  ruby-3.3.yaml
Labels: bincapz/blocking

#36048 fix(ruby): Revert changes making Ruby co-installable
  ruby-3.1.yaml
  ruby-3.2.yaml
  ruby-3.3.yaml
Labels: bincapz/blocking

#36076 add zizmor package
  zizmor.yaml
Labels: bincapz/pass, approved-to-run

#35615 debezium: symlink for apicurio
  debezium-3.0.yaml
Labels: bincapz/pass

#32820 nodejs-21.yaml: Add openssf-options
  nodejs-21.yaml
Labels: automated pr, bincapz/pass, openssf-compiler-options, approved-to-run

#32254 datawire-envoy-1.31.yaml: Add openssf-options
  datawire-envoy-1.31.yaml
Labels: automated pr, bincapz/pass, openssf-compiler-options, approved-to-run

#32400 falco-no-driver.yaml: Add openssf-options
  falco-no-driver.yaml
Labels: bincapz/pass, openssf-compiler-options, approved-to-run

#32441 git-bootstrap.yaml: Add openssf-options
  git-bootstrap.yaml
Labels: bincapz/pass, openssf-compiler-options, approved-to-run

#32816 nodejs-16.yaml: Add openssf-options
  nodejs-16.yaml
Labels: bincapz/pass, openssf-compiler-options, approved-to-run

#36138 bump debezium packages to properly install
  debezium-connect-entrypoint-3.0.yaml
  debezium-connector-db2-3.0.yaml
  debezium-connector-ibmi-3.0.yaml
  debezium-connector-informix-3.0.yaml
  debezium-connector-spanner-3.0.yaml
  debezium-connector-vitess-3.0.yaml
Labels: bincapz/pass

#35854 Drop pkgconf tests that fail because the package provides no .pc files
  frr-10.2.yaml
  libva.yaml
  lsof.yaml
  mimalloc.yaml
  qpdf.yaml
  tk.yaml
Labels: bincapz/pass, approved-to-run

#35186 Add the pkgconf test pipeline to fmt
  fmt.yaml
Labels: bincapz/pass

#34541 gatekeeper-3.17: Add crds package
  gatekeeper-3.17.yaml
Labels: staging-build, bincapz/pass, approved-to-run

#36030 libmamba: python multiversion support
  libmamba.yaml
Labels: bincapz/pass, approved-to-run

#32497 ingress-nginx-controller-1.11.yaml: Add openssf-options
  ingress-nginx-controller-1.11.yaml
Labels: bincapz/pass, malcontent/reviewed, openssf-compiler-options, approved-to-run

#36181 jenkins: require sequential auto update PRs to merge, not auto close un-merged ones
  jenkins.yaml
Labels: bincapz/pass

#36079 bump sqlite and use var-transforms
  sqlite.yaml
Labels: staging-build, bincapz/pass

#36171 update tesseract package
  leptonica.yaml
  tesseract.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#36047 py3-tensorflow-metadata: python multiversioning
  py3-tensorflow-metadata.yaml
Labels: bincapz/pass, approved-to-run

#36031 chore(aws-cli-2): Properly stream
  aws-cli-2.yaml
Labels: bincapz/pass

#34992 fix(sustaining): mitigate GHSA-8495-4g3g-x7pr in dask-gateway
  dask-gateway.yaml
Labels: bincapz/pass, approved-to-run

#36115 aws-signer-notation-plugin package build
  aws-signer-notation-plugin.yaml
Labels: bincapz/pass

#36114 refactor the build config for buildkitd
  buildkitd.yaml
Labels: bincapz/pass

#36172 don't provide for embedded components
  k3s.yaml
Labels: bincapz/pass

#36198 logstash-8/GHSA-2x2g-32r7-p4x8
  logstash-8.yaml
Labels: bincapz/pass

#36210 kyverno-notation-aws package build
  kyverno-notation-aws.yaml
Labels: bincapz/pass

#29194 python-3.12, python-3.13 - build tkinter with python rather than separately.
  py3-tkinter.yaml
  python-3.12.yaml
  python-3.13.yaml
Labels: bincapz/pass

#36282 add duckdb
  duckdb.yaml
Labels: bincapz/pass

#36116 erofs-utils: new package
  erofs-utils.yaml
Labels: bincapz/pass, approved-to-run

#36081 git-credential-oauth: new package
  git-credential-oauth.yaml
Labels: bincapz/pass, approved-to-run

#36332 dask-gateway GHSA-8w49-h785-mj3c fix
  dask-gateway.yaml
Labels: bincapz/pass

#36347 kubeflow-pipelines/GHSA-27wf-5967-98gx fix
  kubeflow-pipelines.yaml
Labels: bincapz/pass

#36361 ruby3.2-aws-sdk-core: support xml parsing
  ruby3.2-aws-sdk-core.yaml
Labels: bincapz/pass

#36385 split containerd into two version streams
  containerd-1.yaml
  containerd-2.yaml
Labels: bincapz/pass

#36281 Adding filebrowser package
  filebrowser.yaml
Labels: bincapz/pass, approved-to-run

#36398 cilium: upgrade to 1.16.4
  cilium-1.16.yaml
Labels: bincapz/pass, approved-to-run

#36392 ensure the -1 package depends on the -1 subpackage runtimes
  containerd-1.yaml
  containerd-2.yaml
Labels: bincapz/pass

#36420 py3-pip - Update virtual to prefer python-3.13 package.
  py3-pip.yaml
Labels: bincapz/pass

#36421 py3-wheel - Update virtual to prefer python-3.13 package.
  py3-wheel.yaml
Labels: bincapz/pass

#36413 xsimd - fix apache-arrow FTBFS by putting cmake files in -dev package, update python 3.13
  apache-arrow.yaml
  xsimd.yaml
Labels: bincapz/pass

#36443 openssl: improve packaging
  openssl.yaml
Labels: bincapz/pass

#36442 Add a dep to datadog-agent-nvml to help it build more
  datadog-agent-nvml.yaml
Labels: bincapz/pass

#32825 nvidia-container-toolkit.yaml: Add openssf-options
  nvidia-container-toolkit.yaml
Labels: automated pr, bincapz/pass, openssf-compiler-options, approved-to-run

#36362 refactor(graphicsmagick): improve fetching to support updates ; fix missing .la files ; add tests
  graphicsmagick.yaml
  graphicsmagick/linky.png
Labels: bincapz/pass

#36521 epoch bump for debezium
  debezium-3.0.yaml
  debezium-connect-entrypoint-3.0.yaml
  debezium-connector-db2-3.0.yaml
  debezium-connector-ibmi-3.0.yaml
  debezium-connector-informix-3.0.yaml
  debezium-connector-vitess-3.0.yaml
Labels: bincapz/pass

#33564 dotnet-8: use a bootstrap package to decouple the requirement artifacts
  dotnet-8.yaml
  dotnet-bootstrap-8.yaml
Labels: approved-to-run

#36538 uglifyjs: new package
  uglifyjs.yaml
Labels: bincapz/pass

#34624 dotnet-9: use a bootstrap package to decouple the requirement artifacts
  dotnet-9.yaml
  dotnet-bootstrap-9.yaml
Labels: bincapz/pass, approved-to-run

#36503 python-3.13: cherry-pick proposed change to block blake2
  python-3.13.yaml
  python-3.13/gh-127301.patch
Labels: bincapz/pass

#36573 Converted mercurial package to build with each supported python version
  mercurial.yaml
Labels: bincapz/pass

#36593 openssh: support config snippets includes
  openssh.yaml
Labels: bincapz/blocking, malcontent/reviewed

#36623 chore(gitsign,guac): fix ghsa-v778-237x-gjrc
  gitsign.yaml
  guac.yaml
Labels: bincapz/pass

#36561 oxipng: new package
  oxipng.yaml
Labels: bincapz/pass

#32475 hdf5.yaml: Add openssf-options
  hdf5.yaml
Labels: automated pr, bincapz/pass, openssf-compiler-options, approved-to-run

#36646 hdf5: Upstream has changed their tagging scheme
  hdf5.yaml
Labels: bincapz/pass, approved-to-run

#36614 Fix a ftbfs with ldb due to a changed url
  ldb.yaml
Labels: bincapz/pass

#36610 Fix a ftbfs with asciidoc due to an incorrect dep
  asciidoc.yaml
  asciidoc/allow-specify-python.yaml
Labels: bincapz/pass

#36698 rsyslog: Use relative symlink
  rsyslog.yaml
Labels: bincapz/pass, approved-to-run

#36450 ruby 3.4: gems batch 2
  ruby3.4-addressable.yaml
  ruby3.4-aws-sigv4.yaml
  ruby3.4-chronic_duration.yaml
  ruby3.4-chronic_duration/numerizer-dependency.patch
  ruby3.4-concurrent-ruby.yaml
  ruby3.4-console.yaml
  ruby3.4-elasticsearch-api.yaml
  ruby3.4-faraday-net_http.yaml
  ruby3.4-faraday.yaml
  ruby3.4-ffi.yaml
  ruby3.4-http-cookie.yaml
  ruby3.4-jruby-openssl.yaml
  ruby3.4-jsonpath.yaml
  ruby3.4-manticore.yaml
  ruby3.4-mime-types.yaml
  ruby3.4-mustermann.yaml
  ruby3.4-net-http-persistent.yaml
  ruby3.4-protocol-http1.yaml
  ruby3.4-protocol-http2.yaml
  ruby3.4-pry.yaml
  ruby3.4-psych.yaml
  ruby3.4-puma.yaml
  ruby3.4-rack-protection.yaml
  ruby3.4-redis-client.yaml
  ruby3.4-reline.yaml
  ruby3.4-rspec-core.yaml
  ruby3.4-rspec-expectations.yaml
  ruby3.4-rspec-mocks.yaml
  ruby3.4-serverengine.yaml
  ruby3.4-snaky_hash.yaml
  ruby3.4-treetop.yaml
Labels: bincapz/pass, ai/skip-comment

#36717 flatbuffers: Make python 3.13 the default
  flatbuffers.yaml
Labels: bincapz/pass, approved-to-run

#36713 Make python-3.13 the answer if you request 'python3' or 'python3-dev'
  python-3.13.yaml
Labels: bincapz/pass

#36346 airflow/GHSA-8w49-h785-mj3c/GHSA-8495-4g3g-x7pr/GHSA-27mf-ghqm-j3j8 fixes
  airflow.yaml
Labels: bincapz/pass

#36708 Add test/ldd-check pipeline, replace ldd 'tests' with it.
  aws-c-auth.yaml
  aws-c-cal.yaml
  aws-c-common.yaml
  aws-c-compression.yaml
  aws-c-event-stream.yaml
  aws-c-http.yaml
  aws-c-mqtt.yaml
  aws-c-s3.yaml
  aws-c-sdkutils.yaml
  aws-checksums.yaml
  chromium.yaml
  expat.yaml
  pipelines/test/ldd-check.yaml
  rtmpdump.yaml
  s2n-tls.yaml
Labels: bincapz/pass

#36568 nodetaint/GHSA-27wf-5967-98gx fix
  nodetaint.yaml
Labels: bincapz/pass

#36483 kubeflow-pipelines-visualization-server GHSA-8w49-h785-mj3c fix
  kubeflow-pipelines-visualization-server.yaml
  kubeflow-pipelines-visualization-server/0001-Bump-dependencies.patch
Labels: bincapz/pass

#36342 py3-cassandra-medusa/GHSA-8495-4g3g-x7p fix
  py3-cassandra-medusa.yaml
Labels: bincapz/pass

#36477 local-static-provisioner-GHSA-27wf-5967-98gx-fix
  local-static-provisioner.yaml
  local-static-provisioner/k8s-GHSA-27wf-5967-98gx-fix.patch
Labels: bincapz/pass

#36152 Refactor docker.yaml
  docker.yaml
Labels: bincapz/pass

#36864 revert: icu 76.1 package update as contains ABI breakage, bumps dependants that have already been built with new ABI
  icu.yaml
  ruby3.4-charlock_holmes.yaml
  tensorflow-core.yaml
  withdrawn-packages.txt
Labels: bincapz/pass

#36857 bump kubernetes-latest to default to k8s 1.32
  kubernetes-latest.yaml
Labels: bincapz/pass

#36915 withdraw icu 76.1 packages (again)
  icu.yaml
Labels: bincapz/pass

#36909 Improvement: Replace the dianamic go mod -edit command with the use of go/bump replaces
  nodetaint.yaml
Labels: bincapz/pass

#36920 fix(microvm-init): fix modprobe when missing modalias
  melange.yaml
  melange/init
Labels: bincapz/pass, approved-to-run

#36930 Drop pkg-config tests obsoleted by pkgconf tests
  libspatialindex.yaml
  userspace-rcu.yaml
  wayland-protocols.yaml
Labels: approved-to-run

#36950 Make python 3.13 version of virtual packages the default. batch 1.10
  py3-deprecation.yaml
  py3-diffoscope.yaml
  py3-dill.yaml
Labels: bincapz/pass

#36948 Make python 3.13 version of virtual packages the default. batch 1.8
  py3-colorama.yaml
  py3-colorlog.yaml
  py3-comm.yaml
  py3-commonmark.yaml
  py3-conda-package-handling.yaml
  py3-conda-package-streaming.yaml
  py3-configargparse.yaml
  py3-configobj.yaml
  py3-contextlib2.yaml
  py3-contourpy.yaml
  py3-cppy.yaml
Labels: bincapz/pass

#36947 Make python 3.13 version of virtual packages the default. batch 1.7
  py3-chardet.yaml
  py3-charset-normalizer.yaml
  py3-cleo.yaml
  py3-cli-helpers.yaml
  py3-click-aliases.yaml
  py3-click-option-group.yaml
  py3-click.yaml
  py3-cloudpickle.yaml
  py3-cmaes.yaml
  py3-codeowners.yaml
  py3-codespell.yaml
Labels: bincapz/pass

#36946 Make python 3.13 version of virtual packages the default. batch 1.6
  py3-breezy.yaml
  py3-cachecontrol.yaml
  py3-cached-property.yaml
  py3-cachetools.yaml
  py3-calver.yaml
  py3-canonicaljson.yaml
  py3-cassandra-driver.yaml
  py3-certifi.yaml
  py3-certipy.yaml
  py3-cffi.yaml
  py3-changelog-chug.yaml
Labels: bincapz/pass

#36945 Make python 3.13 version of virtual packages the default. batch 1.5
  py3-beartype.yaml
  py3-beautifulsoup4.yaml
  py3-beniget.yaml
  py3-bleach.yaml
  py3-blinker.yaml
  py3-bokeh.yaml
  py3-boltons.yaml
  py3-boolean.py.yaml
  py3-boto3.yaml
  py3-botocore.yaml
  py3-bracex.yaml
Labels: bincapz/pass

#36942 Make python 3.13 version of virtual packages the default. batch 1.2
  py3-alembic.yaml
  py3-annotated-types.yaml
  py3-ansible-core.yaml
  py3-ansible-runner-http.yaml
  py3-ansible-runner.yaml
  py3-antlr4-python3-runtime.yaml
  py3-anyio.yaml
  py3-appdirs.yaml
  py3-appnope.yaml
  py3-archspec.yaml
  py3-argcomplete.yaml
Labels: bincapz/pass

#36962 Make python 3.13 version of virtual packages the default. - batch 02.09
  py3-itsdangerous.yaml
  py3-jaeger-client.yaml
  py3-jaraco.classes.yaml
Labels: bincapz/pass

#36960 Make python 3.13 version of virtual packages the default. - batch 02.07
  py3-httplib2.yaml
  py3-httpx.yaml
  py3-huggingface-hub.yaml
  py3-humanfriendly.yaml
  py3-hyperlink.yaml
  py3-hyperopt.yaml
  py3-idna.yaml
  py3-imagesize.yaml
  py3-importlib-metadata.yaml
  py3-importlib-resources.yaml
  py3-influxdb-client.yaml
Labels: bincapz/pass, approved-to-run

#36944 Make python 3.13 version of virtual packages the default. batch 1.4
  py3-avro-python3.yaml
  py3-awscrt.yaml
  py3-awslambdaric.yaml
  py3-azure-core.yaml
  py3-azure-identity.yaml
  py3-azure-storage-blob.yaml
  py3-babel.yaml
  py3-backcall.yaml
  py3-backoff.yaml
  py3-backports.tarfile.yaml
  py3-bcrypt.yaml
Labels: bincapz/pass

#36941 Make python 3.13 version of virtual packages the default. batch 1.1
  emissary.yaml
  gdal.yaml
  grpc-1.67.yaml
  grpc-1.68.yaml
  py3-absl-py.yaml
  py3-agate.yaml
  py3-aiofiles.yaml
  py3-aiohappyeyeballs.yaml
  py3-aiohttp.yaml
  py3-aiosignal.yaml
  py3-alabaster.yaml
Labels: bincapz/pass

#36954 Make python 3.13 version of virtual packages the default. - batch 02.01
  py3-elfdeps.yaml
  py3-entrypoints.yaml
  py3-escapism.yaml
  py3-exceptiongroup.yaml
  py3-executing.yaml
  py3-expandvars.yaml
  py3-extras.yaml
  py3-fabric.yaml
  py3-face.yaml
  py3-fastavro.yaml
  py3-fastbencode.yaml
Labels: bincapz/pass, approved-to-run

#36957 Make python 3.13 version of virtual packages the default. - batch 02.04
  py3-glom.yaml
  py3-glpk.yaml
  py3-google-api-core.yaml
  py3-google-auth-httplib2.yaml
  py3-google-auth-oauthlib.yaml
  py3-google-auth.yaml
  py3-google-cloud-core.yaml
  py3-google-cloud-spanner.yaml
  py3-google-crc32c.yaml
  py3-google-pasta.yaml
  py3-google-resumable-media.yaml
Labels: bincapz/pass, approved-to-run

#36943 Make python 3.13 version of virtual packages the default. batch 1.3
  py3-argon2-cffi-bindings.yaml
  py3-argon2-cffi.yaml
  py3-asgiref.yaml
  py3-asn1crypto.yaml
  py3-astroid.yaml
  py3-asttokens.yaml
  py3-astunparse.yaml
  py3-async-generator.yaml
  py3-async-lru.yaml
  py3-async-timeout.yaml
  py3-attrs.yaml
Labels: bincapz/pass, approved-to-run

#36931 bluez: workaround permission issue to enable test runs.
  bluez.yaml
Labels: bincapz/pass, approved-to-run

#36959 Make python 3.13 version of virtual packages the default. - batch 02.06
  py3-hatch-fancy-pypi-readme.yaml
  py3-hatch-jupyter-builder.yaml
  py3-hatch-nodejs-version.yaml
  py3-hatch-requirements-txt.yaml
  py3-hatch-vcs.yaml
  py3-hatch.yaml
  py3-hatchling.yaml
  py3-hdfs.yaml
  py3-hologram.yaml
  py3-html5lib.yaml
  py3-httpcore.yaml
Labels: bincapz/pass, approved-to-run

#36956 Make python 3.13 version of virtual packages the default. - batch 02.03
  py3-fromager.yaml
  py3-frozenlist.yaml
  py3-fsspec.yaml
  py3-future.yaml
  py3-gast.yaml
  py3-gcloud-aio-auth.yaml
  py3-gcloud-aio-storage.yaml
  py3-gcovr.yaml
  py3-geomet.yaml
  py3-gevent.yaml
  py3-git-filter-repo.yaml
Labels: bincapz/pass, approved-to-run

#36953 Make python 3.13 version of virtual packages the default. - batch 02.00
  py3-distlib.yaml
  py3-distro.yaml
  py3-django.yaml
  py3-dnspython.yaml
  py3-docker-squash.yaml
  py3-docker.yaml
  py3-docopt.yaml
  py3-docutils.yaml
  py3-dulwich.yaml
  py3-durationpy.yaml
  py3-editables.yaml
Labels: bincapz/pass, approved-to-run

#36949 Make python 3.13 version of virtual packages the default. batch 1.9
  py3-crashtest.yaml
  py3-crcmod.yaml
  py3-cryptography.yaml
  py3-cxxfilt.yaml
  py3-cycler.yaml
  py3-cython.yaml
  py3-datadog.yaml
  py3-debugpy.yaml
  py3-decorator.yaml
  py3-defusedxml.yaml
  py3-deprecated.yaml
Labels: bincapz/pass, approved-to-run

#36958 Make python 3.13 version of virtual packages the default. - batch 02.05
  py3-googleapis-common-protos.yaml
  py3-gpep517.yaml
  py3-greenlet.yaml
  py3-grpc-google-iam-v1.yaml
  py3-grpc-interceptor.yaml
  py3-grpcio-gcp.yaml
  py3-grpcio-tools.yaml
  py3-gunicorn.yaml
  py3-gyp-next.yaml
  py3-h11.yaml
  py3-h5py.yaml
Labels: bincapz/pass, approved-to-run

#36419 Update python 3.13 priority in 4 packages.
  libmamba.yaml
  py3-build.yaml
  py3-cairo.yaml
  py3-google-apitools.yaml
Labels: bincapz/pass, approved-to-run

#32883 py3-ml-metadata.yaml: Add openssf-options
  openssf-compiler-options.yaml
  openssf-compiler-options/usr/local/bin/gcc-wrapper
  pipelines/compiler/disable-openssf-flags.yaml
  pipelines/compiler/undisable-openssf-flags.yaml
  py3-ml-metadata.yaml
Labels: bincapz/pass, openssf-compiler-options, approved-to-run

#36456 conda/py3-conda-libmamba-solver: python multiversioning
  conda.yaml
  py3-conda-libmamba-solver.yaml
Labels: bincapz/pass, approved-to-run

#37034 conda: fix failure to plan
  conda-base.yaml
Labels: bincapz/pass

#36981 meson: python multiversioning
  meson.yaml
Labels: bincapz/pass, approved-to-run

#37097 feat(couchdb): add entrypoint and container specific files ; pin Python 3.12
  couchdb-3.3.yaml
  couchdb-3.3/10-docker-default.ini
  couchdb-3.3/docker-entrypoint.sh
  couchdb-3.3/vm.args
Labels: bincapz/pass

#37040 add argocd-image-updater package
  argocd-image-updater.yaml
Labels: bincapz/pass

#37112 fix the symlink in opentofu
  opentofu-1.8.yaml
Labels: bincapz/pass

#37114 pups: add pups gem package
  pups.yaml
Labels: bincapz/pass

#37113 airflow: pin to python3.12, due to FTBFS with python3.13
  airflow.yaml
Labels: bincapz/pass

#37110 opentelemetry-target-allocator
  opentelemetry-operator.yaml
Labels: bincapz/pass

#37133 aws-cli provide full-version
  aws-cli-2.yaml
Labels: bincapz/pass

#37135 fix(couchdb): remove set -x from compat package
  couchdb-3.3.yaml
  couchdb-3.3/docker-entrypoint.sh
Labels: bincapz/pass

#37164 Automatic bump for missing-copier-publication group 24
  tekton-pipelines.yaml
Labels: kind/cleanup, bincapz/pass

#37162 Automatic bump for missing-copier-publication group 22
  ruby3.4-protocol-http2.yaml
  ruby3.4-pry.yaml
  ruby3.4-puma.yaml
  ruby3.4-rack-protection.yaml
  ruby3.4-rspec-expectations.yaml
Labels: kind/cleanup, bincapz/pass

#37163 Automatic bump for missing-copier-publication group 23
  ruby3.4-rspec-mocks.yaml
  ruby3.4-serverengine.yaml
  ruby3.4-snaky_hash.yaml
  ruby3.4-treetop.yaml
  s3cmd.yaml
Labels: kind/cleanup, bincapz/pass

#37149 Automatic bump for missing-copier-publication group 9
  py3-jeepney.yaml
  py3-json5.yaml
  py3-jupyter-events.yaml
  py3-keras.yaml
  py3-kiwisolver.yaml
Labels: kind/cleanup, bincapz/pass

#37144 Automatic bump for missing-copier-publication group 4
  py3-breezy.yaml
  py3-cachecontrol.yaml
  py3-cached-property.yaml
  py3-calver.yaml
  py3-changelog-chug.yaml
Labels: kind/cleanup, bincapz/pass

#37143 Automatic bump for missing-copier-publication group 3
  py3-async-lru.yaml
  py3-async-timeout.yaml
  py3-backcall.yaml
  py3-bracex.yaml
Labels: kind/cleanup, bincapz/pass

#37160 Automatic bump for missing-copier-publication group 20
  ruby3.4-chronic_duration.yaml
  ruby3.4-concurrent-ruby.yaml
  ruby3.4-faraday-net_http.yaml
  ruby3.4-faraday.yaml
  ruby3.4-ffi.yaml
Labels: kind/cleanup, bincapz/pass

#37159 Automatic bump for missing-copier-publication group 19
  py3-wcwidth.yaml
  py3-xmltodict.yaml
  py3-xyzservices.yaml
  ruby3.4-addressable.yaml
  ruby3.4-aws-sigv4.yaml
Labels: kind/cleanup, bincapz/pass

#37158 Automatic bump for missing-copier-publication group 18
  py3-tqdm.yaml
  py3-typing-extensions.yaml
  py3-tzlocal.yaml
  py3-ujson.yaml
  py3-vcrpy.yaml
Labels: kind/cleanup, bincapz/pass

#37157 Automatic bump for missing-copier-publication group 17
  py3-stevedore.yaml
  py3-tensorflow-metadata.yaml
  py3-threadpoolctl.yaml
  py3-toml.yaml
  py3-tornado.yaml
Labels: kind/cleanup, bincapz/pass

#37156 Automatic bump for missing-copier-publication group 16
  py3-setproctitle.yaml
  py3-setuptools-gettext.yaml
  py3-shellingham.yaml
  py3-sphinxcontrib-applehelp.yaml
  py3-sphinxcontrib-serializinghtml.yaml
Labels: kind/cleanup, bincapz/pass

#37155 Automatic bump for missing-copier-publication group 15
  py3-ruamel-yaml.yaml
  py3-s3transfer.yaml
  py3-secretstorage.yaml
  py3-send2trash.yaml
  py3-sentencepiece.yaml
Labels: kind/cleanup, bincapz/pass

#37154 Automatic bump for missing-copier-publication group 14
  py3-pyrsistent.yaml
  py3-pytest.yaml
  py3-python-slugify.yaml
  py3-referencing.yaml
  py3-requests-oauthlib.yaml
Labels: kind/cleanup, bincapz/pass

#37153 Automatic bump for missing-copier-publication group 13
  py3-pyelftools.yaml
  py3-pymysql.yaml
  py3-pyopenssl.yaml
  py3-pyperclip.yaml
  py3-pyproject-hooks.yaml
Labels: kind/cleanup, bincapz/pass

#37152 Automatic bump for missing-copier-publication group 12
  py3-pipenv.yaml
  py3-ply.yaml
  py3-ptyprocess.yaml
  py3-pure-eval.yaml
  py3-pycryptodome.yaml
Labels: kind/cleanup, bincapz/pass

#37150 Automatic bump for missing-copier-publication group 10
  py3-markupsafe.yaml
  py3-matplotlib-inline.yaml
  py3-mock.yaml
  py3-mwoauth.yaml
  py3-ntia-conformance-checker.yaml
Labels: kind/cleanup, bincapz/pass

#37148 Automatic bump for missing-copier-publication group 8
  py3-hyperopt.yaml
  py3-idna.yaml
  py3-ipython-genutils.yaml
  py3-jaeger-client.yaml
  py3-jaraco.classes.yaml
Labels: kind/cleanup, bincapz/pass

#37147 Automatic bump for missing-copier-publication group 7
  py3-google-api-core.yaml
  py3-google-auth.yaml
  py3-google-cloud-core.yaml
  py3-google-pasta.yaml
  py3-google-resumable-media.yaml
Labels: kind/cleanup, bincapz/pass

#37146 Automatic bump for missing-copier-publication group 6
  py3-exceptiongroup.yaml
  py3-expandvars.yaml
  py3-face.yaml
  py3-fastavro.yaml
  py3-glpk.yaml
Labels: kind/cleanup, bincapz/pass

#37174 jupyter-server{-terminals} python multiversion support
  py3-jupyter-server-terminals.yaml
  py3-jupyter-server.yaml
Labels: bincapz/pass
