Repository wolfi-dev/os, pull requests merged in 2024-05, with the labels that each got.

#18133 Correct linux-headers license
  linux-headers.yaml
Labels: fetch2checkout

#18184 crane.yaml: convert from fetch to git-checkout
  crane.yaml
Labels: fetch2checkout

#18180 container-entrypoint.yaml: convert from fetch to git-checkout
  container-entrypoint.yaml
Labels: fetch2checkout

#18173 benchmark.yaml: convert from fetch to git-checkout
  benchmark.yaml
Labels: fetch2checkout

#18170 aws-c-sdkutils.yaml: convert from fetch to git-checkout
  aws-c-sdkutils.yaml
Labels: fetch2checkout

#18168 aws-c-mqtt.yaml: convert from fetch to git-checkout
  aws-c-mqtt.yaml
Labels: fetch2checkout

#18165 aws-c-compression.yaml: convert from fetch to git-checkout
  aws-c-compression.yaml
Labels: fetch2checkout

#18162 aws-c-auth.yaml: convert from fetch to git-checkout
  aws-c-auth.yaml
Labels: fetch2checkout

#18177 bubblewrap.yaml: convert from fetch to git-checkout
  bubblewrap.yaml
Labels: fetch2checkout

#18167 aws-c-io.yaml: convert from fetch to git-checkout
  aws-c-io.yaml
Labels: fetch2checkout

#18172 aws-checksums.yaml: convert from fetch to git-checkout
  aws-checksums.yaml
Labels: fetch2checkout

#18185 crc32c.yaml: convert from fetch to git-checkout
  crc32c.yaml
Labels: fetch2checkout

#18163 aws-c-cal.yaml: convert from fetch to git-checkout
  aws-c-cal.yaml
Labels: fetch2checkout

#18182 cqlsh.yaml: convert from fetch to git-checkout
  cqlsh.yaml
Labels: fetch2checkout

#18164 aws-c-common.yaml: convert from fetch to git-checkout
  aws-c-common.yaml
Labels: fetch2checkout

#18192 wasi-libc.yaml: convert from fetch to git-checkout
  wasi-libc.yaml
Labels: automated pr, fetch2checkout

#18169 aws-c-s3.yaml: convert from fetch to git-checkout
  aws-c-s3.yaml
Labels: fetch2checkout

#18166 aws-c-http.yaml: convert from fetch to git-checkout
  aws-c-http.yaml
Labels: fetch2checkout

#18190 delve.yaml: convert from fetch to git-checkout
  delve.yaml
Labels: automated pr, fetch2checkout

#18191 deno.yaml: convert from fetch to git-checkout
  deno.yaml
Labels: automated pr, fetch2checkout

#18230 lua-cjson.yaml: convert from fetch to git-checkout
  lua-cjson.yaml
Labels: automated pr, fetch2checkout

#18205 go-bindata.yaml: convert from fetch to git-checkout
  go-bindata.yaml
Labels: automated pr, fetch2checkout

#18215 kots.yaml: convert from fetch to git-checkout
  kots.yaml
Labels: automated pr, fetch2checkout

#18207 golangci-lint.yaml: convert from fetch to git-checkout
  golangci-lint.yaml
Labels: automated pr, fetch2checkout

#18236 lua-resty-global-throttle.yaml: convert from fetch to git-checkout
  lua-resty-global-throttle.yaml
Labels: automated pr, fetch2checkout

#18235 lua-resty-dns.yaml: convert from fetch to git-checkout
  lua-resty-dns.yaml
Labels: automated pr, fetch2checkout

#18234 lua-resty-core.yaml: convert from fetch to git-checkout
  lua-resty-core.yaml
Labels: automated pr, fetch2checkout

#18206 go-md2man.yaml: convert from fetch to git-checkout
  go-md2man.yaml
Labels: automated pr, fetch2checkout

#18179 confluent-kafka.yaml: convert from fetch to git-checkout
  confluent-kafka.yaml
Labels: fetch2checkout

#18199 flux.yaml: convert from fetch to git-checkout
  flux.yaml
Labels: automated pr, fetch2checkout

#18341 terragrunt.yaml: convert from fetch to git-checkout
  terragrunt.yaml
Labels: automated pr, fetch2checkout

#18340 tclx.yaml: convert from fetch to git-checkout
  tclx.yaml
Labels: automated pr, fetch2checkout

#18337 su-exec.yaml: convert from fetch to git-checkout
  su-exec.yaml
Labels: automated pr, fetch2checkout

#18336 ssdeep.yaml: convert from fetch to git-checkout
  ssdeep.yaml
Labels: automated pr, fetch2checkout

#18343 tinyxml2.yaml: convert from fetch to git-checkout
  tinyxml2.yaml
Labels: automated pr, fetch2checkout

#18333 snappy.yaml: convert from fetch to git-checkout
  snappy.yaml
Labels: automated pr, fetch2checkout

#18334 spirv-headers.yaml: convert from fetch to git-checkout
  spirv-headers.yaml
Labels: automated pr, fetch2checkout

#18330 s2n-tls.yaml: convert from fetch to git-checkout
  s2n-tls.yaml
Labels: automated pr, fetch2checkout

#18329 ruby3.3-bundler.yaml: convert from fetch to git-checkout
  ruby3.3-bundler.yaml
Labels: automated pr, fetch2checkout

#18328 ruby3.2-webrick.yaml: convert from fetch to git-checkout
  ruby3.2-webrick.yaml
Labels: automated pr, fetch2checkout

#18327 ruby3.2-tzinfo.yaml: convert from fetch to git-checkout
  ruby3.2-tzinfo.yaml
Labels: automated pr, fetch2checkout

#18326 ruby3.2-tzinfo-data.yaml: convert from fetch to git-checkout
  ruby3.2-tzinfo-data.yaml
Labels: automated pr, fetch2checkout

#18325 ruby3.2-traces.yaml: convert from fetch to git-checkout
  ruby3.2-traces.yaml
Labels: automated pr, fetch2checkout

#18324 ruby3.2-timers.yaml: convert from fetch to git-checkout
  ruby3.2-timers.yaml
Labels: automated pr, fetch2checkout

#18323 ruby3.2-timeout.yaml: convert from fetch to git-checkout
  ruby3.2-timeout.yaml
Labels: automated pr, fetch2checkout

#18319 ruby3.2-rexml.yaml: convert from fetch to git-checkout
  ruby3.2-rexml.yaml
Labels: automated pr, fetch2checkout

#18317 ruby3.2-redis-namespace.yaml: convert from fetch to git-checkout
  ruby3.2-redis-namespace.yaml
Labels: automated pr, fetch2checkout

#18268 openlibm.yaml: convert from fetch to git-checkout
  openlibm.yaml
Labels: automated pr, fetch2checkout

#18315 ruby3.2-rack.yaml: convert from fetch to git-checkout
  ruby3.2-rack.yaml
Labels: automated pr, fetch2checkout

#18313 ruby3.2-puma.yaml: convert from fetch to git-checkout
  ruby3.2-puma.yaml
Labels: automated pr, fetch2checkout

#18267 openh264.yaml: convert from fetch to git-checkout
  openh264.yaml
Labels: automated pr, fetch2checkout

#18265 nerdctl.yaml: convert from fetch to git-checkout
  nerdctl.yaml
Labels: automated pr, fetch2checkout

#18312 ruby3.2-protocol-http2.yaml: convert from fetch to git-checkout
  ruby3.2-protocol-http2.yaml
Labels: automated pr, fetch2checkout

#18311 ruby3.2-protocol-http1.yaml: convert from fetch to git-checkout
  ruby3.2-protocol-http1.yaml
Labels: automated pr, fetch2checkout

#18310 ruby3.2-protocol-http.yaml: convert from fetch to git-checkout
  ruby3.2-protocol-http.yaml
Labels: automated pr, fetch2checkout

#18309 ruby3.2-prometheus-client.yaml: convert from fetch to git-checkout
  ruby3.2-prometheus-client.yaml
Labels: automated pr, fetch2checkout

#18308 ruby3.2-pg.yaml: convert from fetch to git-checkout
  ruby3.2-pg.yaml
Labels: automated pr, fetch2checkout

#18306 ruby3.2-oj.yaml: convert from fetch to git-checkout
  ruby3.2-oj.yaml
Labels: automated pr, fetch2checkout

#18302 ruby3.2-net-http-persistent.yaml: convert from fetch to git-checkout
  ruby3.2-net-http-persistent.yaml
Labels: automated pr, fetch2checkout

#18300 ruby3.2-mini_mime.yaml: convert from fetch to git-checkout
  ruby3.2-mini_mime.yaml
Labels: automated pr, fetch2checkout

#18299 ruby3.2-jwt.yaml: convert from fetch to git-checkout
  ruby3.2-jwt.yaml
Labels: automated pr, fetch2checkout

#18298 ruby3.2-io-event.yaml: convert from fetch to git-checkout
  ruby3.2-io-event.yaml
Labels: automated pr, fetch2checkout

#18297 ruby3.2-i18n.yaml: convert from fetch to git-checkout
  ruby3.2-i18n.yaml
Labels: automated pr, fetch2checkout

#18296 ruby3.2-hashie.yaml: convert from fetch to git-checkout
  ruby3.2-hashie.yaml
Labels: automated pr, fetch2checkout

#18295 ruby3.2-fiber-local.yaml: convert from fetch to git-checkout
  ruby3.2-fiber-local.yaml
Labels: automated pr, fetch2checkout

#18293 ruby3.2-faraday-net_http.yaml: convert from fetch to git-checkout
  ruby3.2-faraday-net_http.yaml
Labels: automated pr, fetch2checkout

#18281 ruby3.0-bundler.yaml: convert from fetch to git-checkout
  ruby3.0-bundler.yaml
Labels: automated pr, fetch2checkout

#18174 bincapz.yaml: convert from fetch to git-checkout
  bincapz.yaml
Labels: fetch2checkout

#18282 ruby3.1-bundler.yaml: convert from fetch to git-checkout
  ruby3.1-bundler.yaml
Labels: automated pr, fetch2checkout

#18292 ruby3.2-faraday-follow_redirects.yaml: convert from fetch to git-checkout
  ruby3.2-faraday-follow_redirects.yaml
Labels: automated pr, fetch2checkout

#18291 ruby3.2-date.yaml: convert from fetch to git-checkout
  ruby3.2-date.yaml
Labels: automated pr, fetch2checkout

#18290 ruby3.2-console.yaml: convert from fetch to git-checkout
  ruby3.2-console.yaml
Labels: automated pr, fetch2checkout

#18305 ruby3.2-nio4r.yaml: convert from fetch to git-checkout
  ruby3.2-nio4r.yaml
Labels: automated pr, fetch2checkout

#18304 ruby3.2-net-protocol.yaml: convert from fetch to git-checkout
  ruby3.2-net-protocol.yaml
Labels: automated pr, fetch2checkout

#18289 ruby3.2-connection_pool.yaml: convert from fetch to git-checkout
  ruby3.2-connection_pool.yaml
Labels: automated pr, fetch2checkout

#18287 ruby3.2-bundler.yaml: convert from fetch to git-checkout
  ruby3.2-bundler.yaml
Labels: automated pr, fetch2checkout

#18285 ruby3.2-async-pool.yaml: convert from fetch to git-checkout
  ruby3.2-async-pool.yaml
Labels: automated pr, fetch2checkout

#18284 ruby3.2-async-io.yaml: convert from fetch to git-checkout
  ruby3.2-async-io.yaml
Labels: automated pr, fetch2checkout

#18283 ruby3.2-async-http.yaml: convert from fetch to git-checkout
  ruby3.2-async-http.yaml
Labels: automated pr, fetch2checkout

#18280 restic.yaml: convert from fetch to git-checkout
  restic.yaml
Labels: automated pr, fetch2checkout

#18279 regclient.yaml: convert from fetch to git-checkout
  regclient.yaml
Labels: automated pr, fetch2checkout

#18278 rapidjson.yaml: convert from fetch to git-checkout
  rapidjson.yaml
Labels: automated pr, fetch2checkout

#18286 ruby3.2-async.yaml: convert from fetch to git-checkout
  ruby3.2-async.yaml
Labels: automated pr, fetch2checkout

#18233 lua-resty-cookie.yaml: convert from fetch to git-checkout
  lua-resty-cookie.yaml
Labels: automated pr, fetch2checkout

#18256 lua-resty-lock.yaml: convert from fetch to git-checkout
  lua-resty-lock.yaml
Labels: automated pr, fetch2checkout

#18277 py3-wheel.yaml: convert from fetch to git-checkout
  py3-wheel.yaml
Labels: automated pr, fetch2checkout

#18275 py3-sphinx.yaml: convert from fetch to git-checkout
  py3-sphinx.yaml
Labels: automated pr, fetch2checkout

#18273 py3-magic.yaml: convert from fetch to git-checkout
  py3-magic.yaml
Labels: automated pr, fetch2checkout

#18272 py3-colorama.yaml: convert from fetch to git-checkout
  py3-colorama.yaml
Labels: automated pr, fetch2checkout

#18262 mimalloc.yaml: convert from fetch to git-checkout
  mimalloc.yaml
Labels: automated pr, fetch2checkout

#18258 lua-resty-string.yaml: convert from fetch to git-checkout
  lua-resty-string.yaml
Labels: automated pr, fetch2checkout

#18257 lua-resty-memcached.yaml: convert from fetch to git-checkout
  lua-resty-memcached.yaml
Labels: automated pr, fetch2checkout

#18264 mold.yaml: convert from fetch to git-checkout
  mold.yaml
Labels: automated pr, fetch2checkout

#18210 gtest.yaml: convert from fetch to git-checkout
  gtest.yaml
Labels: automated pr, fetch2checkout

#18209 grpcurl.yaml: convert from fetch to git-checkout
  grpcurl.yaml
Labels: automated pr, fetch2checkout

#18208 graphite2.yaml: convert from fetch to git-checkout
  graphite2.yaml
Labels: automated pr, fetch2checkout

#18204 glslang.yaml: convert from fetch to git-checkout
  glslang.yaml
Labels: automated pr, fetch2checkout

#18203 gke-gcloud-auth-plugin.yaml: convert from fetch to git-checkout
  gke-gcloud-auth-plugin.yaml
Labels: automated pr, fetch2checkout

#18202 ghaudit.yaml: convert from fetch to git-checkout
  ghaudit.yaml
Labels: automated pr, fetch2checkout

#18200 freerdp-3.yaml: convert from fetch to git-checkout
  freerdp-3.yaml
Labels: automated pr, fetch2checkout

#18198 fluent-plugin-splunk-hec.yaml: convert from fetch to git-checkout
  fluent-plugin-splunk-hec.yaml
Labels: automated pr, fetch2checkout

#18197 elixir-1.16.yaml: convert from fetch to git-checkout
  elixir-1.16.yaml
Labels: automated pr, fetch2checkout

#18196 e2fsprogs.yaml: convert from fetch to git-checkout
  e2fsprogs.yaml
Labels: automated pr, fetch2checkout

#18195 dumb-init.yaml: convert from fetch to git-checkout
  dumb-init.yaml
Labels: automated pr, fetch2checkout

#18188 cups.yaml: convert from fetch to git-checkout
  cups.yaml
Labels: fetch2checkout

#18181 cosign.yaml: convert from fetch to git-checkout
  cosign.yaml
Labels: fetch2checkout

#18269 pciutils.yaml: convert from fetch to git-checkout
  pciutils.yaml
Labels: automated pr, fetch2checkout

#18227 libvncserver.yaml: convert from fetch to git-checkout
  libvncserver.yaml
Labels: automated pr, fetch2checkout

#18225 libtbb.yaml: convert from fetch to git-checkout
  libtbb.yaml
Labels: automated pr, fetch2checkout

#18224 libsrt.yaml: convert from fetch to git-checkout
  libsrt.yaml
Labels: automated pr, fetch2checkout

#18223 librdkafka.yaml: convert from fetch to git-checkout
  librdkafka.yaml
Labels: automated pr, fetch2checkout

#18222 libpsl-native.yaml: convert from fetch to git-checkout
  libpsl-native.yaml
Labels: automated pr, fetch2checkout

#18214 kafkacat.yaml: convert from fetch to git-checkout
  kafkacat.yaml
Labels: automated pr, fetch2checkout

#18217 kustomize.yaml: convert from fetch to git-checkout
  kustomize.yaml
Labels: automated pr, fetch2checkout

#18176 btop.yaml: convert from fetch to git-checkout
  btop.yaml
Labels: fetch2checkout

#18331 scorecard.yaml: convert from fetch to git-checkout
  scorecard.yaml
Labels: automated pr, fetch2checkout

#18345 trurl.yaml: convert from fetch to git-checkout
  trurl.yaml
Labels: automated pr, fetch2checkout

#18344 tmux.yaml: convert from fetch to git-checkout
  tmux.yaml
Labels: automated pr, fetch2checkout

#18693 binutils: convert from fetch to git-checkout
  binutils.yaml
Labels: fetch2checkout

#18322 ruby3.2-tilt.yaml: convert from fetch to git-checkout
  ruby3.2-tilt.yaml
Labels: automated pr, fetch2checkout

#18320 ruby3.2-sidekiq.yaml: convert from fetch to git-checkout
  ruby3.2-sidekiq.yaml
Labels: automated pr, fetch2checkout

#18318 ruby3.2-redis.yaml: convert from fetch to git-checkout
  ruby3.2-redis.yaml
Labels: automated pr, fetch2checkout

#18316 ruby3.2-redis-client.yaml: convert from fetch to git-checkout
  ruby3.2-redis-client.yaml
Labels: automated pr, fetch2checkout

#18314 ruby3.2-rack-protection.yaml: convert from fetch to git-checkout
  ruby3.2-rack-protection.yaml
Labels: automated pr, fetch2checkout

#18303 ruby3.2-net-imap.yaml: convert from fetch to git-checkout
  ruby3.2-net-imap.yaml
Labels: automated pr, fetch2checkout

#18301 ruby3.2-multi_xml.yaml: convert from fetch to git-checkout
  ruby3.2-multi_xml.yaml
Labels: automated pr, fetch2checkout

#18342 tini.yaml: convert from fetch to git-checkout
  tini.yaml
Labels: automated pr, fetch2checkout

#18339 suricata.yaml: convert from fetch to git-checkout
  suricata.yaml
Labels: automated pr, fetch2checkout

#18338 suricata-update.yaml: convert from fetch to git-checkout
  suricata-update.yaml
Labels: automated pr, fetch2checkout

#18335 spirv-tools.yaml: convert from fetch to git-checkout
  spirv-tools.yaml
Labels: automated pr, fetch2checkout

#18332 skopeo.yaml: convert from fetch to git-checkout
  skopeo.yaml
Labels: automated pr, fetch2checkout

#18270 pkgconf.yaml: convert from fetch to git-checkout
  pkgconf.yaml
Labels: automated pr, fetch2checkout

#18266 oniguruma.yaml: convert from fetch to git-checkout
  oniguruma.yaml
Labels: automated pr, fetch2checkout

#18261 memcached-exporter.yaml: convert from fetch to git-checkout
  memcached-exporter.yaml
Labels: automated pr, fetch2checkout

#18906 fetch2checkout batch
  http-parser.yaml
  iputils.yaml
  libepoxy.yaml
  libhtp.yaml
Labels: fetch2checkout

#18915 postgresql-16.yaml: convert from fetch to git-checkout
  postgresql-16.yaml
Labels: fetch2checkout

#18216 kubevela.yaml: convert from fetch to git-checkout
  kubevela.yaml
Labels: automated pr, fetch2checkout

#18220 libgit2.yaml: convert from fetch to git-checkout
  libgit2.yaml
Labels: automated pr, fetch2checkout

#18226 libva.yaml: convert from fetch to git-checkout
  libva.yaml
Labels: automated pr, fetch2checkout

#18212 iperf3.yaml: convert from fetch to git-checkout
  iperf3.yaml
Labels: automated pr, fetch2checkout

#18276 py3-udev.yaml: convert from fetch to git-checkout
  py3-udev.yaml
Labels: automated pr, fetch2checkout

#18201 freerdp.yaml: convert from fetch to git-checkout
  freerdp.yaml
Labels: automated pr, fetch2checkout

#18259 lua5.3-lzlib.yaml: convert from fetch to git-checkout
  lua5.3-lzlib.yaml
Labels: automated pr, fetch2checkout

#18361 w3m: Switch to packaging git-branch
  w3m.yaml
Labels: fetch2checkout

#18229 libxcrypt.yaml: convert from fetch to git-checkout
  libxcrypt.yaml
Labels: automated pr, fetch2checkout

#18228 libwebsockets.yaml: convert from fetch to git-checkout
  libwebsockets.yaml
Labels: automated pr, fetch2checkout

#19277 xdpyinfo: fix copyright and upgrade to git-checkout
  xdpyinfo.yaml
Labels: fetch2checkout, copyright

#19827 cilium 1.15.5 upgrade
  cilium-1.15.yaml
  cilium-1.15/go.mod.patch
  cilium-1.15/toolchains-paths.patch
Labels: P1, security

#19918 kustomize: bump epoch to rebuild with latest go 1.22.3
  kustomize.yaml
Labels: CVE-2024-24787, CVE-2024-24788

#19925 go sdtlib cve
  kyverno.yaml
  newrelic-nri-statsd.yaml
Labels: CVE-2024-24787, CVE-2024-24788
