Repository wolfi-dev/os, pull requests merged in 2024-07, with the labels that each got.

#22992 mattermost-9: fix CVE GHSA-3669-72x9-r9p3
  mattermost-9.yaml
Labels: bincapz/pass

#23292 k8s-sidecar: fix GHSA-248v-346w-9cwc
  k8s-sidecar.yaml
Labels: bincapz/pass

#23290 superset: fix GHSA-248v-346w-9cwc
  superset.yaml
Labels: bincapz/blocking

#23633 fix(metric-collector-for-apache-cassandra): Stream for Cassandra 4.1
  metric-collector-for-apache-cassandra-4.1.yaml
  metric-collector-for-apache-cassandra-4.1/collectd-download-url-fix.patch
  metric-collector-for-apache-cassandra-4.1/pombump-deps.yaml
Labels: bincapz/blocking

#23735 fix(neuvector): Add paths expected by agent to enforcer
  neuvector.yaml
Labels: bincapz/blocking

#23787 gcc: add C and C++ tests (gcc-13)
  gcc.yaml
Labels: foundations

#23788 gcc-12: add C and C++ tests
  gcc-12.yaml
Labels: foundations

#23911 fix(neuvector): Add CIS benchmarks to enforcer and controller
  neuvector.yaml
Labels: bincapz/pass

#23924 fix(neuvector-cis-benchmarks): Add utils
  neuvector.yaml
Labels: bincapz/pass

#23899 chore(gitlab): Migrate packages with nonstandard releases to gitlab-cng
  gitlab-cng-17.1.yaml
  gitlab-container-registry.yaml
  gitlab-elasticsearch-indexer.yaml
  gitlab-exporter.yaml
  gitlab-logger.yaml
  gitlab-mailroom.yaml
  gitlab-shell.yaml
Labels: bincapz/blocking

#23940 fix(gitlab): Fix tag filters for KAS and runner
  gitlab-kas-17.1.yaml
  gitlab-runner-17.1.yaml
Labels: bincapz/pass

#23941 fix(gitlab-cng-17.1): Don't bundle CNG scripts/config with components…
  gitlab-cng-17.1.yaml
Labels: bincapz/blocking

#23972 superset: fix GHSA-jfmj-5v4g-7637
  superset.yaml
Labels: bincapz/blocking

#24146 kube-fluentd-operator: fix GHSA-4xqq-m2hx-25v8
  kube-fluentd-operator.yaml
Labels: bincapz/pass

#24258 chore: Bump ruby packages 1 of 6
  fluent-plugin-cloudwatch-logs.yaml
  fluent-plugin-detect-exceptions.yaml
  fluent-plugin-elasticsearch.yaml
  fluent-plugin-kubernetes_metadata_filter.yaml
  fluent-plugin-label-router.yaml
  fluent-plugin-newrelic.yaml
  fluent-plugin-out-http.yaml
  fluent-plugin-prometheus.yaml
  fluent-plugin-record-modifier.yaml
Labels: bincapz/pass

#24259 chore: Bump ruby packages 2 of 6
  fluent-plugin-rewrite-tag-filter.yaml
  fluent-plugin-s3.yaml
  fluent-plugin-splunk-hec.yaml
  fluent-plugin-tag-normaliser.yaml
  ruby3.2-activemodel.yaml
  ruby3.2-activesupport.yaml
  ruby3.2-aws-sdk-cloudwatchlogs.yaml
  ruby3.2-aws-sdk-kms.yaml
Labels: bincapz/pass

#24260 chore: Bump ruby packages 3 of 6
  ruby3.2-aws-sdk-s3.yaml
  ruby3.2-aws-sdk-sqs.yaml
  ruby3.2-aws-sigv4.yaml
  ruby3.2-chronic_duration.yaml
  ruby3.2-elastic-transport.yaml
  ruby3.2-elasticsearch-api.yaml
  ruby3.2-elasticsearch.yaml
  ruby3.2-faraday-excon.yaml
  ruby3.2-faraday-follow_redirects.yaml
Labels: bincapz/pass

#24263 chore: Bump ruby packages 6 of 6
  ruby3.2-redis-client.yaml
  ruby3.2-redis-namespace.yaml
  ruby3.2-redis.yaml
  ruby3.2-sinatra.yaml
  ruby3.2-snaky_hash.yaml
  ruby3.2-swd.yaml
  ruby3.2-treetop.yaml
  ruby3.2-validate_email.yaml
  ruby3.2-validate_url.yaml
  ruby3.2-webfinger.yaml
  selenium.yaml
Labels: bincapz/pass

#24262 chore: Bump ruby packages 5 of 6
  ruby3.2-net-http-persistent.yaml
  ruby3.2-net-imap.yaml
  ruby3.2-net-protocol.yaml
  ruby3.2-oauth2.yaml
  ruby3.2-openid_connect-1.1.8.yaml
  ruby3.2-openid_connect.yaml
  ruby3.2-pry.yaml
  ruby3.2-rack-oauth2.yaml
  ruby3.2-rack-protection.yaml
Labels: bincapz/pass

#24261 chore: Bump ruby packages 4 of 6
  ruby3.2-faraday.yaml
  ruby3.2-fluent-config-regexp-type.yaml
  ruby3.2-i18n.yaml
  ruby3.2-jruby-openssl.yaml
  ruby3.2-json-jwt.yaml
  ruby3.2-logstash-mixin-ecs_compatibility_support.yaml
  ruby3.2-mail.yaml
  ruby3.2-manticore.yaml
  ruby3.2-mustermann.yaml
Labels: bincapz/pass

#24298 chore: Bump ruby packages 1
  fluent-plugin-cloudwatch-logs.yaml
  fluent-plugin-detect-exceptions.yaml
  fluent-plugin-elasticsearch.yaml
  fluent-plugin-kubernetes_metadata_filter.yaml
  fluent-plugin-label-router.yaml
  fluent-plugin-newrelic.yaml
  fluent-plugin-out-http.yaml
  fluent-plugin-prometheus.yaml
  fluent-plugin-record-modifier.yaml
  fluent-plugin-rewrite-tag-filter.yaml
Labels: bincapz/pass

#24299 chore: Bump ruby packages 2
  fluent-plugin-s3.yaml
  fluent-plugin-splunk-hec.yaml
  fluent-plugin-tag-normaliser.yaml
  ruby3.2-activemodel.yaml
  ruby3.2-activesupport.yaml
  ruby3.2-aes_key_wrap.yaml
  ruby3.2-attr_required.yaml
  ruby3.2-aws-eventstream.yaml
  ruby3.2-aws-partitions.yaml
Labels: bincapz/pass

#24300 chore: Bump ruby packages 3
  ruby3.2-aws-sdk-cloudwatchlogs.yaml
  ruby3.2-aws-sdk-kms.yaml
  ruby3.2-aws-sdk-s3.yaml
  ruby3.2-aws-sdk-sqs.yaml
  ruby3.2-aws-sigv4.yaml
  ruby3.2-base64.yaml
  ruby3.2-bindata.yaml
  ruby3.2-bouncy-castle-java.yaml
  ruby3.2-charlock_holmes.yaml
Labels: bincapz/pass

#24302 chore: Bump ruby packages 5
  ruby3.2-faraday-excon.yaml
  ruby3.2-faraday-follow_redirects.yaml
  ruby3.2-faraday-net_http.yaml
  ruby3.2-faraday.yaml
  ruby3.2-filesize.yaml
  ruby3.2-fluent-config-regexp-type.yaml
  ruby3.2-gems.yaml
  ruby3.2-hashie.yaml
  ruby3.2-i18n.yaml
  ruby3.2-jar-dependencies.yaml
Labels: bincapz/pass

#24303 chore: Bump ruby packages 6
  ruby3.2-jmespath.yaml
  ruby3.2-json-jwt.yaml
  ruby3.2-json.yaml
  ruby3.2-jwt.yaml
  ruby3.2-logstash-mixin-ecs_compatibility_support.yaml
  ruby3.2-mail.yaml
  ruby3.2-manticore.yaml
  ruby3.2-method_source.yaml
  ruby3.2-mini_mime.yaml
  ruby3.2-minitar.yaml
Labels: bincapz/pass

#24304 chore: Bump ruby packages 7
  ruby3.2-multi_json.yaml
  ruby3.2-multi_xml.yaml
  ruby3.2-mustermann.yaml
  ruby3.2-net-http-persistent.yaml
  ruby3.2-net-imap.yaml
  ruby3.2-net-protocol.yaml
  ruby3.2-nio4r.yaml
  ruby3.2-numerizer.yaml
  ruby3.2-oauth2.yaml
  ruby3.2-openid_connect-1.1.8.yaml
Labels: bincapz/pass

#24305 chore: Bump ruby packages 8
  ruby3.2-openid_connect.yaml
  ruby3.2-openssl_pkcs8_pure.yaml
  ruby3.2-pg.yaml
  ruby3.2-polyglot.yaml
  ruby3.2-prometheus-client.yaml
  ruby3.2-pry.yaml
  ruby3.2-public_suffix.yaml
  ruby3.2-quantile.yaml
  ruby3.2-rack-2.2.yaml
  ruby3.2-rack-oauth2.yaml
Labels: bincapz/pass

#24306 chore: Bump ruby packages 9
  ruby3.2-rack-protection.yaml
  ruby3.2-rack.yaml
  ruby3.2-redis-client.yaml
  ruby3.2-redis-namespace.yaml
  ruby3.2-redis.yaml
  ruby3.2-ruby2_keywords.yaml
  ruby3.2-rubyzip.yaml
  ruby3.2-sinatra.yaml
  ruby3.2-snaky_hash.yaml
  ruby3.2-stud.yaml
Labels: bincapz/pass

#24311 chore: Bump ruby packages 10
  ruby3.2-swd.yaml
  ruby3.2-thread_safe.yaml
  ruby3.2-timeout.yaml
  ruby3.2-treetop.yaml
  ruby3.2-validate_email.yaml
  ruby3.2-validate_url.yaml
  ruby3.2-version_gem.yaml
  ruby3.2-webfinger.yaml
  selenium.yaml
Labels: bincapz/pass

#24264 Adds a compat package for gitlab-shell-scripts
  gitlab-cng-17.1.yaml
Labels: bincapz/blocking

#24113 fix(gitlab-exporter-17.1): Unlock gemspec
  gitlab-cng-17.1.yaml
Labels: bincapz/blocking

#24774 fix(gitaly-17.2): Build bundled Git
  gitaly-17.2.yaml
Labels: bincapz/pass

#24500 Copy authorized_keys with suitable permission
  gitlab-cng-17.2.yaml
Labels: bincapz/pass

#25144 fix(gitlab-exporter-17.2): Bundle expected gems
  gitlab-cng-17.2.yaml
Labels: bincapz/pass

#25171 pulumi-watch: fix GHSA-r8w9-5wcg-vfj7
  pulumi-watch.yaml
Labels: bincapz/pass

#25235 fix(gitlab-runner-17.2): Add Docker Machine
  gitlab-runner-17.2.yaml
Labels: bincapz/pass
