Repository wolfi-dev/os, pull requests merged in 2024-09, with the labels that each got.

#27313 Pin py3-gevent to gcc 13, add openssf.
  py3-gevent.yaml
Labels: ftbfs

#27329 Fix runit FTBFS with gcc-14
  runit.yaml
Labels: ftbfs

#27321 py3-xmlsec - fix FTBFS, add openssf-compiler-flags
  py3-xmlsec.yaml
Labels: ftbfs

#27320 Ftbfs py3 ruamel yaml clib
  py3-ruamel-yaml-clib.yaml
Labels: ftbfs

#27318 py3-glpk - fix FTBFS
  py3-glpk.yaml
Labels: ftbfs

#28440 Revert "ruby3.2-protocol-hpack/1.5.1 package update"
  ruby3.2-protocol-hpack.yaml
  ruby3.2-protocol-hpack/001-remove-signing-key.patch
Labels: bincapz/pass

#28452 Rebuild for jsoncpp soname bump
  cmake.yaml
  falco.yaml
  grpc.yaml
Labels: dependencies, ftbfs, sustaining

#28595 krb5: improve configuration options
  krb5.yaml
Labels: fips

#29595 Revert "only run GHA presubmit if 'github-build' label is applied"
  .github/workflows/ci-build.yaml
  ko.yaml
Labels: bincapz/pass

#29744 suricata-update: Fix build
  suricata-update.yaml
Labels: staging-build
