Repository wolfi-dev/os, pull requests merged in 2025-07, with the labels that each got.

#57976 Mariadb operator
  mariadb-operator.yaml
Labels: bincapz/pass, ai/skip-comment

#51720 aws-network-policy-agent: build with latest linux headers
  aws-network-policy-agent/pkg/ebpf/c/vmlinux.h-aarch64
  aws-network-policy-agent/pkg/ebpf/c/vmlinux.h-x86_64
Labels: bincapz/pass

#58013 quality: improved cilium-envoy package testing
  cilium-envoy-1.17.yaml
Labels: bincapz/pass

#58137 Use no-hardening.spec
  falco-no-driver.yaml
  gperftools.yaml
  grpc-1.66.yaml
  grpc-1.68.yaml
  grpc-1.69.yaml
  grpc-1.70.yaml
  grpc-1.71.yaml
  hdf5.yaml
  nvidia-container-toolkit.yaml
Labels: bincapz/pass

#58140 boring-registry: fix GHSA-fv92-fjc5-jj9h
  boring-registry.yaml
Labels: bincapz/pass

#58103 feat(cassandra-reaper): bump dep to remediate GHSA-h46c-h94j-95f3
  cassandra-reaper.yaml
  cassandra-reaper/src/server/pombump-deps.yaml
Labels: bincapz/pass

#58145 Added all knative components (with range)
  knative-serving-1.18.yaml
Labels: bincapz/pass

#58159 kyverno-notation-aws: remediate cve
  kyverno-notation-aws.yaml
Labels: bincapz/pass

#57612 tmux: use -std=gnu17 to fix ftbfs with gcc 15
  tmux.yaml
Labels: bincapz/pass, approved-to-run

#57462 apicurio-registry: update package
  apicurio-registry.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#58187 No change rebuilds for 2.28
  abseil-cpp.yaml
  apk-tools.yaml
  apr-util.yaml
  dav1d.yaml
  gtest.yaml
  libdrm.yaml
  libevent.yaml
  libsrt.yaml
  libuv.yaml
  mpdecimal.yaml
  openldap.yaml
  postgresql-17.yaml
Labels: bincapz/pass

#58047 openssl: Update to 3.5.1
  openssl.yaml
Labels: bincapz/pass

#58020 glibc: Cherry-pick AArch64 fix & re-enable hardening
  glibc.yaml
  glibc/vendor/ld.so.conf.d/libc.conf
Labels: bincapz/pass

#58149 Do not create /usr/lib32 or empty symlinks for i686 .so files
  rust-1.69.yaml
Labels: bincapz/pass

#58029 add editcap subpackage to tshark
  tshark-4.4.yaml
Labels: bincapz/pass, approved-to-run

#58224 pytest: alpha-sort runtime deps, add pygments
  py3-pytest.yaml
Labels: bincapz/pass

#58027 Blob csi fixes
  blob-csi-1.26.yaml
Labels: bincapz/pass

#57973 feat: add kubescape-operator package
  kubescape-operator.yaml
Labels: bincapz/pass, approved-to-run

#58192 Builds compat package to run redis w/harbor
  harbor-2.13.yaml
Labels: bincapz/pass

#58045 Add new package: kratos
  kratos.yaml
Labels: bincapz/pass, approved-to-run

#58106 refactor langfuse
  langfuse.yaml
  withdrawn-packages.txt
Labels: bincapz/pass, ai/skip-comment

#58237 malcontent/1.14.0 package update; yara-x/1.3.0 test update
  malcontent.yaml
  yara-x.yaml
Labels: bincapz/pass

#58155 feat: new package dkron:4.0.5
  dkron.yaml
Labels: bincapz/pass, ai/skip-comment

#58188 add flux-operator package
  flux-operator.yaml
Labels: bincapz/pass

#58282 Update Versions and enable update for future # total packages
  py3-alembic.yaml
  py3-pyfarmhash.yaml
  py3-pykube-ng.yaml
  py3-pytz.yaml
Labels: bincapz/pass

#58024 cmake: Upgrade to version 4.0.3
  cmake-bootstrap.yaml
  cmake.yaml
  cmake/wolfi-tests/CMakeLists.txt
Labels: bincapz/pass

#58148 datadog-agent: fix GHSA-fv92-fjc5-jj9h by updating mapstructure to v2.3.0
  datadog-agent.yaml
Labels: bincapz/pass

#58253 switch cis-operator to version stream
  cis-operator-1.4.yaml
Labels: bincapz/pass

#58358 Fix Bunch of CVE across multiple subprojectes
  kubeflow.yaml
Labels: bincapz/pass, ai/skip-comment

#58296 iptables: Add tests to prepare for package refactoring
  iptables.yaml
Labels: bincapz/pass

#55221 luajit: bump to latest
  luajit.yaml
Labels: bincapz/pass

#58419 7zip: update to 2500
  7zip.yaml
Labels: bincapz/pass

#58438 update chromium to 138.0.7204.96
  chromium.yaml
Labels: bincapz/pass

#58318 Drop lib32 and broken symlinks to non-existent .so file
  rust-1.72.yaml
Labels: bincapz/pass

#58317 Drop lib32 and broken symlinks to non-existent .so file
  rust-1.73.yaml
Labels: bincapz/pass

#58316 Drop lib32 and broken symlinks to non-existent .so file
  rust-1.74.yaml
Labels: bincapz/pass

#58315 Drop lib32 and broken symlinks to non-existent .so file
  rust-1.75.yaml
Labels: bincapz/pass

#58314 Drop lib32 and broken symlinks to non-existent .so file
  rust-1.76.yaml
Labels: bincapz/pass

#17120 add iptables-wrapper
  iptables-wrappers.yaml
Labels: bincapz/pass, ai/skip-comment

#58517 openssh: Update default PATH to prefer /usr/bin over /usr/sbin
  openssh.yaml
Labels: bincapz/pass

#58456 add font-kacst
  font-kacst.yaml
Labels: bincapz/pass

#58494 melange/0.29.0 package update
  melange.yaml
Labels: bincapz/pass

#57527 llvm-16.yaml: Consolidate into unified llvm-16.yaml and remove split …
  clang-16.yaml
  llvm-16.yaml
  llvm-cmake-16.yaml
  llvm-libcxx-16.yaml
  llvm-lld-16.yaml
  llvm16.yaml
Labels: bincapz/pass, approved-to-run

#58529 Rebuild pkgs providing pc files
  cmocka.yaml
  eventlog.yaml
  font-xproto.yaml
  ivykis.yaml
  lerc.yaml
  libart-lgpl.yaml
  libdaemon.yaml
  libdeflate.yaml
  libestr.yaml
  libev.yaml
  libfastjson.yaml
  libfontenc.yaml
  libisofs.yaml
  libmpack.yaml
  libpthread-stubs.yaml
  libvdpau.yaml
  popt.yaml
  speexdsp.yaml
  spirv-tools.yaml
  startup-notification.yaml
  subunit.yaml
Labels: bincapz/pass, ai/skip-comment

#58586 package: saf
  saf.yaml
Labels: bincapz/pass

#58597 azure-ipam: make package reproducible
  azure-ipam.yaml
Labels: bincapz/pass

#58604 postfix: Add `ld.so.conf.d` snippet
  postfix.yaml
Labels: bincapz/pass

#58619 melange/0.29.1 package update
  melange.yaml
Labels: bincapz/pass

#58626 go-1.24: update to go-1.24.5
  go-1.24.yaml
Labels: bincapz/pass

#58628 go-1.23: update to go-1.23.11
  go-1.23.yaml
Labels: bincapz/pass

#58516 Pin more packages to use cmake-3 when building
  crc32c.yaml
  libcbor.yaml
  libsrt.yaml
  nfs-ganesha.yaml
  orthanc-dicomweb.yaml
  orthanc-gdcm.yaml
  orthanc-ohif.yaml
  orthanc-webviewer.yaml
  plog.yaml
  soxr.yaml
  yaml-cpp.yaml
  zeromq.yaml
Labels: bincapz/pass

#58550 add font-tibetan-machine
  font-tibetan-machine.yaml
Labels: bincapz/pass, ai/skip-comment

#58478 add font pkgs
  font-opensymbol.yaml
  font-takao.yaml
Labels: bincapz/pass, ai/skip-comment

#58617 liburcu package addition
  liburcu.yaml
Labels: bincapz/pass

#58580 ceph: fix FTBFS with cmake 4
  ceph.yaml
Labels: bincapz/pass

#58669 feat(rust-analyzer): update package to version 20250709
  rust-analyzer.yaml
Labels: bincapz/pass

#58387 add aznfs-mount files/dirs
  aznfs-mount.yaml
  blob-csi-1.26.yaml
Labels: bincapz/pass, ai/skip-comment

#58680 java-cacerts-default: Ensure java-certs script is copied to contextdir so it is present in the package.
  java-cacerts.yaml
Labels: bincapz/pass

#58724 Adds provides to rancher-shell
  rancher-shell-0.4.yaml
Labels: bincapz/pass

#58633 bitstream vera
  font-bitstream-vera.yaml
Labels: bincapz/pass

#58746 mariadb-operator: fix github tag-filter-prefix
  mariadb-operator.yaml
Labels: bincapz/pass

#58738 consul-k8s-1.7: bump helm to v3.18.4 to fix GHSA-557j-xg8c-q2mm
  consul-k8s-1.7.yaml
Labels: bincapz/pass

#58742 go-1.2*: Improve tests
  go-1.20.yaml
  go-1.22.yaml
  go-1.23.yaml
  go-1.24.yaml
Labels: bincapz/pass

#58879 add additonal ldflags for cis-operator
  cis-operator-1.4.yaml
Labels: bincapz/pass

#58128 Add lua-resty packages
  lua-resty-events.yaml
  lua-resty-worker-events.yaml
Labels: bincapz/pass

#58938 postfix: Use `rpath` instead of `ld.so.conf.d` for internal libraries
  postfix.yaml
Labels: bincapz/pass

#58721 cerbos: split cerbos & cerbosctl packages
  cerbos.yaml
Labels: bincapz/pass

#58878 feat: new package infinispan-operator
  infinispan-operator.yaml
Labels: bincapz/pass

#58655 llvm 16 renames
  aws-network-policy-agent.yaml
  falco-libs.yaml
  flux-image-automation-controller.yaml
  flux-source-controller.yaml
  openmp-16.yaml
Labels: bincapz/pass, ai/skip-comment, llvm-renames

#54531 feat(virtualpackage.yaml): Add new virtualpackage test pipeline with example usage
  pipelines/test/virtualpackage.yaml
  py3-fsspec.yaml
Labels: bincapz/pass

#58972 feat(teleport-17): bump deps to remediate GHSA-557j-xg8c-q2mm
  teleport-17.yaml
Labels: bincapz/pass, ai/skip-comment

#58722 postgresql: add ecpg and libecpg-dev packages
  postgresql-16.yaml
  postgresql-17.yaml
Labels: bincapz/pass, ai/skip-comment

#58538 add font-nanum
  font-nanum.yaml
  pipelines/test/fonts.yaml
Labels: bincapz/pass

#59006 Updated crossplane-provider-keycloak to 1.9.2
  crossplane-provider-keycloak.yaml
Labels: bincapz/pass

#59011 Updated crossplane-provider-keycloak to 1.11.0
  crossplane-provider-keycloak.yaml
Labels: bincapz/pass

#58527 package: manifest-tool
  manifest-tool.yaml
Labels: bincapz/pass, approved-to-run

#59165 feat(akhq): bump deps to remediate GHSA-j288-q9x7-2f5v and GHSA-xwmg-2g98-w7v9 and upgrade package
  akhq.yaml
  akhq/cves-20250530.patch
  akhq/cves-20250714.patch
Labels: bincapz/pass, ai/skip-comment

#59167 add py3-pybase64 package
  py3-pybase64.yaml
Labels: bincapz/pass

#59154 add py3-blake3 package
  py3-blake3.yaml
Labels: bincapz/pass

#59164 erl{25-28}-rebar3: set provides rebar3 + provider priority based on erlang version
  electric.yaml
  erl25-rebar3.yaml
  erl26-rebar3.yaml
  erl27-rebar3.yaml
  erl28-rebar3.yaml
Labels: bincapz/pass

#59201 gi-docgen: add virtualpackage tests
  gi-docgen.yaml
Labels: bincapz/pass

#59205 py3-anyio: add virtual package tests
  py3-anyio.yaml
Labels: bincapz/pass

#59211 Create symlink for metrics-server binary at root of filesystem
  coredns.yaml
  metrics-server.yaml
Labels: bincapz/pass

#59224 add compat package for sonobuoy
  sonobuoy.yaml
Labels: bincapz/pass, approved-to-run

#58942 pypy-3.11: add ldd-check test and missing runtime dependencies
  pypy-3.11.yaml
Labels: bincapz/pass

#58292 elixir-1.{17,18}: multiversion depending on supported OTP version
  elixir-1.17.yaml
  elixir-1.18.yaml
  elixir-1.18/zzz/lib/zzz.ex
  elixir-1.18/zzz/lib/zzz/application.ex
  elixir-1.18/zzz/mix.exs
  elixir-1.18/zzz/test/test_helper.exs
  erl25-elixir-1.17.yaml
  erl25-elixir-1.18.yaml
  erl26-elixir-1.17.yaml
  erl26-elixir-1.18.yaml
  erl27-elixir-1.17.yaml
  erl27-elixir-1.18.yaml
  withdrawn-packages.txt
Labels: bincapz/pass, ai/skip-comment

#59194 enhance spegel testing
  spegel.yaml
Labels: bincapz/pass

#59235 py3-safetensors: Add additional tests
  py3-safetensors.yaml
  py3-safetensors/test_simple.py
Labels: bincapz/pass

#59166 pipelines: add new metapackage test
  pipelines/test/metapackage.yaml
  py3-fsspec.yaml
Labels: bincapz/pass

#59263 font-xorg: make co-installable
  font-xorg-adobe100dpi.yaml
  font-xorg-adobe75dpi.yaml
  font-xorg-adobeutopia100dpi.yaml
  font-xorg-adobeutopia75dpi.yaml
  font-xorg-adobeutopiatype1.yaml
  font-xorg-arabicmisc.yaml
  font-xorg-bh100dpi.yaml
  font-xorg-bh75dpi.yaml
  font-xorg-bhlucidatypewriter100dpi.yaml
  font-xorg-bhlucidatypewriter75dpi.yaml
  font-xorg-bhtype1.yaml
  font-xorg-bitstream100dpi.yaml
  font-xorg-bitstreamtype1.yaml
  font-xorg-cursormisc.yaml
  font-xorg-daewoomisc.yaml
  font-xorg-decmisc.yaml
  font-xorg-dirs.yaml
  font-xorg-ibmtype1.yaml
  font-xorg-isasmisc.yaml
  font-xorg-schumachermisc.yaml
  font-xorg-screencyrillic.yaml
  font-xorg-sonymisc.yaml
  font-xorg-sunmisc.yaml
  font-xorg-winitzkicyrillic.yaml
  font-xorg-xfree86type1.yaml
  font-xorg.yaml
Labels: bincapz/pass

#59234 add compat package for symlink compatibility
  k8s_gateway.yaml
Labels: bincapz/pass

#59206 Builds rancher security scan
  rancher-security-scan-0.6.yaml
Labels: bincapz/pass

#59319 Pins kubectl version as expected by project
  rancher-shell-0.4.yaml
Labels: bincapz/pass

#59347 add sonobuoy package
  sonobuoy-systemd-logs.yaml
Labels: bincapz/pass

#59362 cerbos: package update
  cerbos.yaml
Labels: bincapz/pass

#58877 initial build for ratify package
  ratify.yaml
Labels: bincapz/pass, ai/skip-comment

#59419 feat(solr-9.8.1): bump deps to remediate GHSA-j288-q9x7-2f5v
  solr.yaml
Labels: bincapz/pass

#59393 llvm-libunwind-*: Drop, no longer required
  llvm-libunwind-15.yaml
  llvm-libunwind-16.yaml
  llvm-libunwind-17.yaml
Labels: llvm-renames

#59444 jenkins-plugin-manager: remediate GHSA-j288-q9x7-2f5v CVE-2025-48924
  jenkins-plugin-manager.yaml
  jenkins-plugin-manager/pombump-deps.yaml
Labels: bincapz/pass

#59403 rust-1.75: Update build dependencies for LLVM 17 package renames.
  rust-1.75.yaml
Labels: bincapz/pass, llvm-renames

#59450 fix(perl-net-ssleay): rebuild the package with perl 5.42.0
  perl-net-ssleay.yaml
Labels: bincapz/pass

#59398 rust 1.73/llvm 17 renames
  rust-1.73.yaml
Labels: bincapz/pass, ai/skip-comment, llvm-renames

#59397 openmp 17/llvm 17 renames
  openmp-17.yaml
Labels: bincapz/pass, ai/skip-comment, llvm-renames

#59471 py3-coloredlogs: init package on 15.0.1
  py3-coloredlogs.yaml
Labels: bincapz/pass

#58258 kwok: create sa token and ca.cert
  amazon-cloudwatch-agent-operator.yaml
  cert-manager-webhook-pdns.yaml
  pipelines/test/kwok/cluster.yaml
  sealed-secrets.yaml
Labels: bincapz/pass

#59485 fix: systemd-logs doesn't need qemu
  sonobuoy-systemd-logs.yaml
Labels: bincapz/pass

#59498 melange/0.29.5 package update
  melange.yaml
Labels: bincapz/pass

#59494 perl 5.42 other rdeps3
  nginx-mainline.yaml
  nginx-stable.yaml
  openresty.yaml
Labels: bincapz/pass, perl-5.42.0

#59502 perl 5.42 rdeps3
  perl-encode-locale.yaml
  perl-eval-closure.yaml
  perl-exception-class.yaml
  perl-extutils-config.yaml
  perl-extutils-helpers.yaml
  perl-extutils-installpaths.yaml
  perl-extutils-makemaker-cpanfile.yaml
  perl-file-copy-recursive.yaml
  perl-file-listing.yaml
  perl-file-next.yaml
Labels: bincapz/pass, perl-5.42.0

#59511 perl 5.42 rdeps12
  perl-www-robotrules.yaml
  perl-xml-parser.yaml
  perl-yaml-pp.yaml
  perl-yaml-syck.yaml
  perl-yaml-tiny.yaml
  perl-yapp.yaml
Labels: bincapz/pass, perl-5.42.0

#59510 perl 5.42 rdeps11
  perl-test-without-module.yaml
  perl-test2-plugin-nowarnings.yaml
  perl-text-diff.yaml
  perl-tidy.yaml
  perl-time-hires.yaml
  perl-tk.yaml
  perl-try-tiny.yaml
  perl-types-serialiser.yaml
  perl-uri.yaml
  perl-win32-shellquote.yaml
Labels: bincapz/pass, perl-5.42.0

#59509 perl 5.42 rdeps10
  perl-sub-info.yaml
  perl-sub-quote.yaml
  perl-template-toolkit.yaml
  perl-term-table.yaml
  perl-test-differences.yaml
  perl-test-fatal.yaml
  perl-test-nowarnings.yaml
  perl-test-pod-coverage.yaml
  perl-test-pod.yaml
  perl-test-simple.yaml
Labels: bincapz/pass, perl-5.42.0

#59508 perl 5.42 rdeps9
  perl-parse-yapp.yaml
  perl-pod-coverage.yaml
  perl-pod-parser.yaml
  perl-readonly.yaml
  perl-role-tiny.yaml
  perl-scope-guard.yaml
  perl-specio.yaml
  perl-string-shellquote.yaml
  perl-sub-exporter-progressive.yaml
  perl-sub-identify.yaml
Labels: bincapz/pass, perl-5.42.0

#59507 perl 5.42 rdeps8
  perl-namespace-autoclean.yaml
  perl-namespace-clean.yaml
  perl-net-http.yaml
  perl-net-snmp.yaml
  perl-net-telnet.yaml
  perl-package-stash.yaml
  perl-parallel-iterator.yaml
  perl-parallel-pipes.yaml
  perl-params-validationcompiler.yaml
  perl-parse-pmfile.yaml
Labels: bincapz/pass, perl-5.42.0

#59504 perl 5.42 rdeps5
  perl-http-negotiate.yaml
  perl-http-tinyish.yaml
  perl-importer.yaml
  perl-inc-latest.yaml
  perl-io-gzip.yaml
  perl-io-html.yaml
  perl-io-socket-ssl.yaml
  perl-ipc-run3.yaml
  perl-json-maybexs.yaml
  perl-json-xs.yaml
Labels: bincapz/pass, perl-5.42.0

#59495 perl 5.42 other rdeps4
  openscap.yaml
  postgis-17.yaml
  qt5-qtbase.yaml
Labels: bincapz/pass, perl-5.42.0

#59517 version streams net-kourier
  net-kourier-1.18.yaml
Labels: bincapz/pass

#59522 Split off the libzip docs to their own package
  libzip.yaml
Labels: bincapz/pass

#59521 Builds tiktoken
  py3-tiktoken.yaml
Labels: bincapz/pass

#59381 add bento pkg
  bento.yaml
Labels: bincapz/pass, ai/skip-comment

#59396 cilium envoy 1.17/llvm 17 renames
  cilium-envoy-1.17.yaml
Labels: bincapz/pass, ai/skip-comment, llvm-renames

#59399 rust 1.74/llvm 17 renames
  rust-1.74.yaml
Labels: bincapz/pass, ai/skip-comment, llvm-renames

#59402 wasi-libc: update LLVM 17 package references
  wasi-libc.yaml
Labels: bincapz/pass, llvm-renames

#59540 fix(tileserver-gl): bump epoch to pick up libpng 1.6.50
  tileserver-gl.yaml
Labels: bincapz/pass

#59451 nextflow: remediate CVE-2025-48924 GHSA-j288-q9x7-2f5v
  nextflow.yaml
Labels: bincapz/pass

#59553 gradle-8: remediate cve
  gradle-8.yaml
  gradle-8/commons-lang3-GHSA-j288-q9x7-2f5v.patch
Labels: bincapz/pass

#59595 melange/0.29.6 package update
  melange.yaml
Labels: bincapz/pass

#59597 py3-cassandra-medusa: remediate CVE-2025-53643 GHSA-9548-qrrj-x5pj
  py3-cassandra-medusa.yaml
Labels: bincapz/pass

#59606 melange/0.29.7 package update
  melange.yaml
Labels: bincapz/pass

#59803 666 rebuild184
  ruby3.4-console.yaml
  ruby3.4-cool.io.yaml
  ruby3.4-date.yaml
  ruby3.4-diff-lcs.yaml
  ruby3.4-dotenv.yaml
  ruby3.4-elasticsearch-api.yaml
  ruby3.4-elasticsearch.yaml
  ruby3.4-excon.yaml
  ruby3.4-faraday-net_http.yaml
  ruby3.4-faraday.yaml
Labels: bincapz/pass, 666-files

#59621 666 rebuild3
  argocd-extension-installer.yaml
  argocd-image-updater.yaml
  armadillo.yaml
  arpack.yaml
  async-profiler.yaml
  at-spi2-core.yaml
  atmoz-sftp.yaml
  attr.yaml
  atuin.yaml
  audit.yaml
Labels: 666-files

#59658 666 rebuild40
  font-xorg-bhlucidatypewriter75dpi.yaml
  font-xorg-bhtype1.yaml
  font-xorg-bitstream100dpi.yaml
  font-xorg-bitstreamtype1.yaml
  font-xorg-cursormisc.yaml
  font-xorg-daewoomisc.yaml
  font-xorg-decmisc.yaml
  font-xorg-ibmtype1.yaml
  font-xorg-isasmisc.yaml
  font-xorg-schumachermisc.yaml
Labels: bincapz/pass, 666-files

#59793 666 rebuild174
  ruby3.2-minitar.yaml
  ruby3.2-multi_xml.yaml
  ruby3.2-net-imap.yaml
  ruby3.2-net-protocol.yaml
  ruby3.2-numerizer.yaml
  ruby3.2-oauth2.yaml
  ruby3.2-oj.yaml
  ruby3.2-openid_connect-1.1.8.yaml
  ruby3.2-openid_connect.yaml
  ruby3.2-prometheus-client.yaml
Labels: bincapz/pass, 666-files

#59656 666 rebuild38
  font-opensymbol.yaml
  font-samyak.yaml
  font-sony-misc.yaml
  font-stix-otf.yaml
  font-takao.yaml
  font-tibetan-machine.yaml
  font-tlwg.yaml
  font-twemoji-colr.yaml
  font-unfonts-core.yaml
  font-wqy-microhei.yaml
Labels: bincapz/pass, 666-files

#59798 666 rebuild179
  ruby3.3-http.yaml
  ruby3.3-http_parser.rb.yaml
  ruby3.3-io-console.yaml
  ruby3.3-io-event.yaml
  ruby3.3-io-stream.yaml
  ruby3.3-jruby-openssl.yaml
  ruby3.3-json.yaml
  ruby3.3-jwt.yaml
  ruby3.3-mime-types-data.yaml
  ruby3.3-mime-types.yaml
Labels: bincapz/pass, 666-files

#59654 666 rebuild36
  font-khmeros.yaml
  font-lao.yaml
  font-liberation.yaml
  font-linux-libertine.yaml
  font-lklug-sinhala.yaml
  font-lklug.yaml
  font-lohit-beng-assamese.yaml
  font-lohit-beng-bengali.yaml
  font-lohit-beng-extra.yaml
  font-lohit-extras.yaml
Labels: bincapz/pass, 666-files

#59710 666 rebuild92
  lua-resty-cookie.yaml
  lua-resty-core.yaml
  lua-resty-dns.yaml
  lua-resty-events.yaml
  lua-resty-global-throttle.yaml
  lua-resty-http.yaml
  lua-resty-ipmatcher.yaml
  lua-resty-lock.yaml
  lua-resty-memcached.yaml
  lua-resty-redis.yaml
Labels: bincapz/pass, 666-files

#59632 666 rebuild14
  cloudflared.yaml
  cloudnative-pg.yaml
  cloudprober.yaml
  cloudwatch-exporter.yaml
  clucene.yaml
  cluster-api-1.10.yaml
  cluster-autoscaler-1.33.yaml
  cluster-proportional-autoscaler.yaml
  clusterctl.yaml
  cmake-3.yaml
Labels: 666-files

#59648 666 rebuild30
  exiftool.yaml
  exim.yaml
  expat.yaml
  exploitdb.yaml
  external-dns.yaml
  external-secrets-operator-0.18.yaml
  extism.yaml
  eza.yaml
  faiss.yaml
  falco-exporter.yaml
Labels: 666-files

#59709 666 rebuild91
  loki-3.5.yaml
  longhorn-instance-manager-1.9.yaml
  lshw.yaml
  lsof.yaml
  lttng-ust.yaml
  lua-cjson.yaml
  lua-haproxy-auth-request.yaml
  lua-luv.yaml
  lua-resty-balancer.yaml
  lua-resty-cache.yaml
Labels: 666-files

#59702 666 rebuild84
  libsigcplusplus.yaml
  libslirp.yaml
  libsndfile.yaml
  libsolv.yaml
  libspf2.yaml
  libsrt.yaml
  libssh.yaml
  libtasn1.yaml
  libtelnet.yaml
  libtirpc.yaml
Labels: 666-files

#59665 666 rebuild47
  gitlab-pages-18.1.yaml
  gitlab-runner-18.1.yaml
  gitleaks.yaml
  gitness.yaml
  gitsign.yaml
  gke-gcloud-auth-plugin.yaml
  glab.yaml
  glew.yaml
  glib-gir.yaml
  glib.yaml
Labels: 666-files

#59684 666 rebuild66
  kafka-proxy.yaml
  kafka_exporter.yaml
  kakoune.yaml
  kaniko.yaml
  kapp-controller.yaml
  kapp.yaml
  kargo.yaml
  karma.yaml
  karpenter-1.5.yaml
  kbd.yaml
Labels: 666-files

#59642 666 rebuild24
  dive.yaml
  dkron.yaml
  docbook-xml.yaml
  docker-cli-buildx.yaml
  docker-cli.yaml
  docker-compose.yaml
  docker-credential-acr-env.yaml
  docker-credential-ecr-login.yaml
  docker-credential-gcr.yaml
  docker-library-php.yaml
Labels: bincapz/pass, 666-files

#59726 666 rebuild108
  nri-kubernetes.yaml
  nri-memcached.yaml
  nri-mongodb.yaml
  nri-mssql.yaml
  nri-mysql.yaml
  nri-nagios.yaml
  nri-nginx.yaml
  nri-postgresql.yaml
  nri-prometheus.yaml
  nri-rabbitmq.yaml
Labels: 666-files

#59652 666 rebuild34
  fluent-plugin-tag-normaliser.yaml
  flux-2.6.yaml
  flux-helm-controller.yaml
  flux-image-automation-controller.yaml
  flux-image-reflector-controller.yaml
  flux-kustomize-controller.yaml
  flux-notification-controller.yaml
  flux-operator.yaml
  flux-source-controller.yaml
  flux.yaml
Labels: 666-files

#59697 666 rebuild79
  libfido2.yaml
  libfontenc.yaml
  libgcrypt.yaml
  libgdiplus.yaml
  libgit2.yaml
  libglvnd.yaml
  libgpg-error.yaml
  libgphoto2.yaml
  libgsf.yaml
  libhtp.yaml
Labels: bincapz/pass, 666-files

#59694 666 rebuild76
  lerna.yaml
  less.yaml
  libacvp.yaml
  libaec.yaml
  libapr.yaml
  libarchive.yaml
  libart-lgpl.yaml
  libass.yaml
  libassuan.yaml
  libatomic_ops.yaml
Labels: 666-files

#59669 666 rebuild51
  gops.yaml
  goreleaser.yaml
  gostatsd.yaml
  gosu.yaml
  gotestsum.yaml
  govulncheck.yaml
  gperf.yaml
  gperftools.yaml
  gpgme.yaml
  gpsd.yaml
Labels: bincapz/pass, 666-files

#59749 666 rebuild131
  prometheus-pushgateway.yaml
  promxy.yaml
  protobuf-c.yaml
  protobuf.yaml
  protoc-gen-go-grpc.yaml
  protoc-gen-go.yaml
  proxysql.yaml
  prrte.yaml
  pstack.yaml
  pugixml.yaml
Labels: bincapz/pass, 666-files
