Repository wolfi-dev/os, pull requests merged in 2025-05, with the labels that each got.

#52203 crosstool-ng: fix automatic parallel builds
  crosstool-ng.yaml
Labels: bincapz/pass

#38083 tensorflow-core: Remove build-dep on cython
  tensorflow-core.yaml
Labels: bincapz/pass, approved-to-run, eng:os

#49098 Add libcurl-abi virtual package (take #2)
  curl-rustls.yaml
  curl.yaml
Labels: bincapz/pass

#51930 jaeger/cve-remediation
  jaeger.yaml
Labels: bincapz/pass

#51892 ceph: add jq to runtime dependencies
  ceph.yaml
Labels: bincapz/pass

#52275 ceph: remove apache-arrow dependencies
  ceph.yaml
Labels: bincapz/pass

#52172 pax-utils: fix lddtree runtime dependencies
  pax-utils.yaml
Labels: staging-build, bincapz/pass

#52294 rebuild tileserver-gl with libpng's newer version
  tileserver-gl.yaml
Labels: bincapz/blocking, malcontent/reviewed

#52274 tileserver-gl-5.3.0-r0 CVE remediation
  tileserver-gl.yaml
  tileserver-gl/CVE-2025-46653.patch
Labels: bincapz/blocking, malcontent/reviewed

#52296 logstash-8/build error
  logstash-8.yaml
Labels: bincapz/pass

#51963 fix(airflow): pin python requirements for airflow 2.x
  airflow.yaml
Labels: bincapz/pass, ai/skip-comment

#52270 Fix(Update bot faliure): Move to git checkout compiler-rt is just subdirectory
  scudo-malloc.yaml
Labels: bincapz/pass

#52327 harbor-registry: updates
  harbor-registry.yaml
Labels: bincapz/pass

#52303 fleet-controller: add package
  rancher-fleet.yaml
Labels: bincapz/pass

#52424 add cairomm as dependency to -dev package
  cairomm.yaml
Labels: bincapz/pass

#51573 New version stream: airflow-3
  airflow-3.yaml
  airflow-3/urllib3.patch
Labels: bincapz/pass, service:version-stream

#52445 add cairomm-1.16 package
  cairomm-1.16.yaml
Labels: bincapz/pass

#52446 add `kubernetes-csi-external-attacher-compat` pkg
  kubernetes-csi-external-attacher.yaml
Labels: bincapz/pass

#52441 py3-pydantic-core: backfill version for py3-pydantic, require sequential updates
  py3-pydantic-core.yaml
Labels: bincapz/pass

#52456 fleet: add cli package and update log script path
  rancher-fleet.yaml
Labels: bincapz/pass, approved-to-run

#52482 kube-fluentd-operator/cve-remediation
  kube-fluentd-operator.yaml
Labels: bincapz/pass

#52479 openjdk8: update to the latest GA(8u452)
  openjdk-8.yaml
Labels: bincapz/pass

#52451 add py3-gobject3 package
  py3-gobject3.yaml
Labels: bincapz/pass

#52334 new package: aws-nuke
  aws-nuke.yaml
Labels: bincapz/pass

#52332 php: enable apache module for libphp
  apache2.yaml
  apr-util.yaml
  php-8.1.yaml
  php-8.1/apache.conf
  php-8.2.yaml
  php-8.2/apache.conf
  php-8.3.yaml
  php-8.3/apache.conf
  php-8.4.yaml
  php-8.4/apache.conf
Labels: bincapz/pass, ai/skip-comment

#52493 xcover: add new package
  xcover.yaml
Labels: bincapz/pass

#52420 Drop the use of `$HOME` in php packages
  php-8.1.yaml
  php-8.2.yaml
  php-8.3.yaml
  php-8.4.yaml
Labels: bincapz/pass

#51959 feat(pipelines): Configure gradle to use Libraries
  pdftk.yaml
  pipelines/ecosystems/gradle.yaml
Labels: bincapz/pass, ai/skip-comment

#52474 tekton-pipelines-1.0: update binary names
  tekton-pipelines-1.0.yaml
Labels: bincapz/pass

#51292 add py3-graph-tool package
  py3-graph-tool.yaml
Labels: bincapz/pass, malcontent/reviewed, ai/skip-comment

#50502 feat: add fixuid package
  fixuid.yaml
Labels: bincapz/pass

#52523 Add missing `mkdir`
  azure-service-operator.yaml
Labels: bincapz/pass

#52202 new/llvm-libcxx-18
  llvm-libcxx-18.yaml
  llvm.yaml
  withdrawn-packages.txt
Labels: bincapz/pass

#51936 quality: extend prometheus-operator package test
  prometheus-operator.yaml
Labels: bincapz/pass

#52253 fix(vector): add openssl fixes to Cargo.toml
  vector.yaml
Labels: bincapz/pass

#52581 Add wal-g configuration file for database archival and restoration
  wal-g.yaml
Labels: bincapz/pass, approved-to-run

#52646 fix: add missing /dev/fd symlink
  melange.yaml
  melange/init
Labels: bincapz/pass

#52526 melange: add tmpfs /dev/shm to melange-init for VMs
  melange.yaml
  melange/init
Labels: staging-build, bincapz/pass

#52632 k3s/GHSA-v778-237x-gjrc/GHSA-hcg3-q754-cr77 fix
  k3s.yaml
Labels: bincapz/pass

#52673 Fix the `PATH` for `ggshield`
  ggshield.yaml
Labels: bincapz/pass

#52678 Add missing clang dependency
  postgis-17.yaml
Labels: bincapz/pass

#52316 add istioctl-bash-completion package
  istio-1.25.yaml
Labels: bincapz/pass

#52685 strimzi-kafka-operator: replace nmap with netcat-openbsd
  strimzi-kafka-operator.yaml
Labels: bincapz/pass

#52604 vitess-21.0/GHSA-859w-5945-r5v3 fix
  vitess-21.0.yaml
Labels: bincapz/blocking, malcontent/reviewed

#52704 strimzi-kafka-operator: revert nmap change
  strimzi-kafka-operator.yaml
Labels: ai/skip-comment

#52002 glibc: extend glibc.rtld.execstack tunable to force executable stack
  glibc.yaml
  glibc/stable/0001-elf-Extend-glibc.rtld.execstack-tunable-to-force-exe.patch
Labels: bincapz/pass

#52709 fix: add missing symlinks for stdin/out/err
  melange.yaml
  melange/init
Labels: bincapz/pass

#52677 opensearch: add tag-filter-prefix
  opensearch-2.yaml
Labels: bincapz/pass, ai/skip-comment

#52729 More missing subpackage mkdirs
  gobject-introspection.yaml
  nats-server-config-reloader.yaml
  splunk-otel-collector.yaml
Labels: bincapz/pass

#52749 `liquibase-docker` tag moved
  liquibase-docker.yaml
Labels: bincapz/pass

#52728 add stunnel-compat package
  stunnel.yaml
Labels: bincapz/pass, ai/skip-comment

#52726 Add missing clang dependency
  pgvector-16.yaml
  pgvector-17.yaml
  repmgr-17.yaml
Labels: bincapz/pass, ai/skip-comment

#52744 add openmp versions 18 and 19
  openmp-18.yaml
  openmp-19.yaml
Labels: bincapz/pass, approved-to-run

#48749 feat: init code-server package
  code-server.yaml
  code-server/GHSA-pq67-2wwv-3xjx.patch
  code-server/node-memory.patch
Labels: bincapz/blocking, malcontent/reviewed, ai/skip-comment

#52781 abseil-cpp: epoch bump to build against latest gtest-dev
  abseil-cpp.yaml
Labels: bincapz/pass

#52782 Use lp.net not edge.lp.net
  intltool.yaml
Labels: bincapz/pass

#52783 Drop an unnecessary go bump
  smarter-device-manager.yaml
Labels: bincapz/pass

#52772 kube-fluentd-operator: Remove bundle clean
  kube-fluentd-operator.yaml
Labels: bincapz/pass

#52791 Add `.ssh/authorized_keys` to rat exclusions.
  apache-activemq-artemis.yaml
  apache-activemq-artemis/rat-exclusions.txt
Labels: bincapz/pass

#52792 melange: bump RLIMIT_NOFILE hardlimit to max value from kernel
  melange.yaml
  melange/init
Labels: bincapz/pass

#52795 chore(update): Bump pulumi-language-java to 1.11.0 and fix update backend
  pulumi-language-java.yaml
Labels: bincapz/pass

#52522 py3-graph-tool: add more runtime deps
  py3-graph-tool.yaml
Labels: bincapz/pass, ai/skip-comment

#52618 ceph: re-enable rgw parquet support
  ceph.yaml
  ceph/arrow-20-compat.patch
Labels: bincapz/pass, ai/skip-comment

#52642 add py3-pystache package configuration
  py3-pystache.yaml
Labels: bincapz/pass, approved-to-run

#52817 influxd: move to version-stream
  influxd-2.7.yaml
  influxd-2.7/default-config.yml
  influxd-2.7/entrypoint.sh
Labels: ai/skip-comment

#52839 feat(wal-g.yaml): Bump epoch of wal-g and subpackages to trigger rebuild and CVE scan
  wal-g.yaml
Labels: bincapz/pass

#52774 From wolfi repo from openssl
  openssl.yaml
Labels: bincapz/pass

#51908 py3-pecan: align with upstream versioning, fix tests
  py3-pecan.yaml
Labels: bincapz/pass

#52883 Pass `--force` to `kaniko` test.
  kaniko.yaml
Labels: bincapz/pass

#52874 Add missing build deps for pg-failover-slots-16 fixing an FTBFS
  pg-failover-slots-16.yaml
Labels: bincapz/pass

#52886 GLib-2.0.gir was missing from our -dev packaged (needed by another bu…
  gobject-introspection.yaml
Labels: bincapz/pass

#52890 Bash's brace expansion is not available
  jellyfin.yaml
Labels: bincapz/pass

#52894 Make sure Bazel installs a default JDK.
  bazel-6.yaml
Labels: bincapz/pass

#52853 gnutar: test improvements (qemu env failure, add ldd-test)
  gnutar.yaml
Labels: staging-build, bincapz/pass

#52895 `maven` test should use JDK not JRE.
  maven-3.9.yaml
Labels: bincapz/pass

#52891 Add `cgroups` to the set of mounts melange init does.
  melange.yaml
  melange/init
Labels: bincapz/pass

#52889 Redirect output for `cadvisor` test.
  cadvisor.yaml
Labels: bincapz/pass

#52923 etcd-3.5: add -buildvcs=false flag
  etcd-3.5.yaml
Labels: bincapz/pass

#52869 Add missing build deps for pgaudit-17 fixing an FTBFS
  pgaudit-17.yaml
Labels: bincapz/pass

#52942 missing a few other *.gir objects needed for other builds
  gobject-introspection.yaml
Labels: bincapz/pass

#52911 experiment: on the fly disk for melange QEMU runner
  microvm-init.yaml
  microvm-init/init
Labels: bincapz/pass

#52948 fix: add missing xattrs when extracting rootfs
  microvm-init.yaml
  microvm-init/init
Labels: bincapz/pass

#52881 glu: stop using osmesa gl_provider
  glu.yaml
Labels: bincapz/pass

#52912 grafana-11.6: add -buildvcs=false to upstream build system
  grafana-11.6.yaml
  grafana-11.6/append-buildvcs-false-to-go-build.patch
Labels: bincapz/blocking, malcontent/reviewed

#52995 revert those last two commits; these files are provided by glib-gir a…
  gobject-introspection.yaml
Labels: bincapz/pass

#53077 Add `nohup` and output redir to `memcached` tests
  memcached.yaml
Labels: bincapz/pass

#52818 added package: trivy-operator
  trivy-operator.yaml
Labels: bincapz/pass

#52808 feat: add efs-utils for efs-csi-driver
  efs-utils.yaml
Labels: bincapz/pass, ai/skip-comment

#52809 change efs-utils pkg in aws-efs-csi-driver
  aws-efs-csi-driver.yaml
Labels: bincapz/pass

#53075 gogatekeeper package build
  gogatekeeper.yaml
Labels: bincapz/pass

#53128 ruby3.x-rails-8.0/cve remediation
  ruby3.2-rails-8.0.yaml
  ruby3.3-rails-8.0.yaml
  ruby3.4-rails-8.0.yaml
Labels: bincapz/pass

#53095 feat: add postgresql-17-iamguarded-compat
  postgresql-17-iamguarded-compat.yaml
Labels: bincapz/pass, ai/skip-comment

#53076 Improve microvm user support
  .gitignore
  microvm-init.yaml
  microvm-init/init
Labels: bincapz/pass

#53083 liquibase: set version at build-time
  liquibase.yaml
Labels: bincapz/pass

#52994 fix(strimzi-kafka): support kafka 3.9
  strimzi-kafka-operator.yaml
Labels: bincapz/pass

#53121 utmps: cherry-pick header fix from upstream
  utmps.yaml
Labels: bincapz/pass

#53159 curl-rustls: bump epoch
  curl-rustls.yaml
Labels: bincapz/pass

#53144 Update lean4 to 4.19.0 and add patches for FTBFS w/ libuv 1.51
  lean4.yaml
  lean4/libuv-1.51-stage0.patch
  lean4/libuv-1.51.patch
Labels: bincapz/pass

#52982 gperftools: Disable compiler optimizations & spec file usage, fixing tests
  gperftools.yaml
Labels: bincapz/pass

#53082 fix: remove hard dependency
  code-server.yaml
Labels: bincapz/blocking

#53184 Add missing `file` dependency
  dotnet-bootstrap-9.yaml
Labels: bincapz/pass

#53185 Exclude the SSH authorized keys from the license check.
  cassandra-reaper.yaml
  cassandra-reaper/rat-exclusions.txt
Labels: bincapz/pass

#53183 Don't use `$HOME` in `chromium.yaml`
  chromium.yaml
Labels: staging-build, bincapz/pass

#53169 feat: microvm-init setup additional ports
  microvm-init.yaml
  microvm-init/init
Labels: bincapz/pass, approved-to-run

#52899 upgrade aws-sdk-core gem for kube-fluentd-operator
  kube-fluentd-operator.yaml
Labels: bincapz/pass

#53244 linkerd2-proxy: add coreutils and tzdata as runtime deps
  linkerd2-proxy.yaml
Labels: bincapz/pass

#53250 Fix python path
  py3-maturin.yaml
Labels: bincapz/pass

#53187 code-server: use one more patch
  code-server.yaml
  code-server/GHSA-pq67-2wwv-3xjx.patch
  code-server/v8flags-create-hash.patch
Labels: bincapz/blocking, ai/skip-comment

#52529 Adds dask-kubernetes package
  dask-kubernetes.yaml
Labels: bincapz/pass

#52582 quality: extend tigera-operator package tests
  tigera-operator-1.37.yaml
Labels: bincapz/pass, approved-to-run

#53265 Rename pam-linux file to linux-pam/login.pamd
  linux-pam.yaml
  linux-pam/login.pamd
Labels: bincapz/pass

#52457 fix(kubeflow-pipelines-metadata-writer): Use Python 3.10
  kubeflow-pipelines.yaml
Labels: bincapz/blocking, malcontent/reviewed, ai/skip-comment

#53294 feat(kubernetes): add iamguarded-compat package
  kubernetes-1.33.yaml
Labels: bincapz/pass

#53293 add missing templates folder
  gogatekeeper.yaml
Labels: bincapz/pass

#53303 add missing runtime deps
  k3s.yaml
Labels: bincapz/pass

#53311 fix: format ext4 with news profile
  microvm-init.yaml
  microvm-init/init
Labels: bincapz/pass

#53313 llvm: misc housekeeping - consistent toolchain for libs
  llvm-libcxx-18.yaml
  llvm-libunwind-15.yaml
  llvm-libunwind-16.yaml
  llvm-libunwind-17.yaml
Labels: bincapz/pass

#53331 qemu - enable vnc support.
  qemu.yaml
Labels: bincapz/pass

#53225 Add curl and move entrypoint script in opensearch-2
  opensearch-2.yaml
  opensearch-2/ingest-attachment.patch
  opensearch-2/ml-commons.patch
  opensearch-2/repository-azure.patch
Labels: bincapz/pass, approved-to-run

#53191 apache2: split apache2 config(s) into subpackage
  apache2.yaml
Labels: bincapz/pass

#53330 feat: switch QEMU environment to XFS
  microvm-init.yaml
  microvm-init/init
Labels: bincapz/pass

#53326 Valkey sentinel adder
  valkey.yaml
Labels: bincapz/pass

#53263 Rebuild patroni
  patroni.yaml
  py3-prettytable.yaml
  py3-pysyncobj.yaml
  py3-pysyncobj/class.py
  py3-ydiff.yaml
  py3-ydiff/testa.txt
  py3-ydiff/testb.txt
Labels: bincapz/pass, approved-to-run

#53344 chore(kubevela): add functional tests w/ KOWK + remove reduntant statement in definition
  kubevela.yaml
Labels: bincapz/pass

#53343 grafana-12.0: fix FTBFS
  grafana-12.0.yaml
  grafana-12.0/fix-pkg-storage-unified-resource-health.go.patch
Labels: bincapz/blocking, malcontent/reviewed

#53400 fead(memcached): add iamguarded compat, also to exporter package
  memcached-exporter.yaml
  memcached.yaml
Labels: bincapz/pass, ai/skip-comment

#53409 test(ollama): better package definition + more consistent tests
  ollama.yaml
Labels: bincapz/pass

#53429 fix: remove confusing error messages
  microvm-init.yaml
  microvm-init/init
Labels: bincapz/pass

#53358 fix(kubevela): split vela-cli into its own subpackage
  kubevela.yaml
Labels: bincapz/pass

#53443 opensearch-3: Move docker entrypoint
  opensearch-3.yaml
Labels: bincapz/pass

#42648 btrfs-progs: fix python build-deps
  btrfs-progs.yaml
Labels: lifecycle/stale, bincapz/pass

#53405 emissary/kubeflow-jupyter-web-app/kubeflow-volumes-web-app: fix cve
  emissary.yaml
  kubeflow-jupyter-web-app.yaml
  kubeflow-volumes-web-app.yaml
Labels: bincapz/blocking, malcontent/reviewed

#52430 golem package build
  golem.yaml
Labels: bincapz/pass, ai/skip-comment

#53463 steampipe/cve remediation
  steampipe.yaml
Labels: bincapz/pass

#53473 libmamba/ftbfs fix
  libmamba.yaml
Labels: bincapz/pass

#53496 chore(kubevela): add `kubevela-` prefix for vela-{core,cli} subpackages
  kubevela.yaml
Labels: bincapz/pass

#53498 fix(rabbitmq-server-4.1): use correct version of compat
  rabbitmq-server-4.1.yaml
Labels: bincapz/blocking

#53530 Bumped epoches on R-sf and postgis-17 to ensure gdal changes are picked up
  R-sf.yaml
  postgis-17.yaml
Labels: bincapz/pass

#53524 quality: improve renovate package test
  renovate.yaml
Labels: bincapz/blocking, malcontent/reviewed

#53290 quality: extend test thanos package
  thanos.yaml
Labels: bincapz/pass, approved-to-run

#53560 chainguard-security-guide: update to v3.2.0 (based on v3r2 GPOS SRG)
  chainguard-security-guide.yaml
Labels: bincapz/pass

#53557 Add ldd-check tests to several packages
  libnetfilter_conntrack.yaml
  libnetfilter_queue.yaml
  llvm-libunwind-16.yaml
  llvm-libunwind-17.yaml
  py3-cassandra-medusa.yaml
  py3-sentencepiece.yaml
  reflex.yaml
  reproc.yaml
  riemann-c-client.yaml
  rpm-sequoia.yaml
Labels: bincapz/pass

#53630 rootlesskit switch to go/build
  rootlesskit.yaml
Labels: bincapz/pass

#53658 llvm-libcxx-18: ensure compiled with -fpic
  llvm-libcxx-18.yaml
Labels: bincapz/pass

#53678 fix: mount pty for chroots
  microvm-init.yaml
  microvm-init/init
Labels: bincapz/pass

#52080 cmake: update to latest 3.31 release
  cmake-bootstrap.yaml
  cmake.yaml
  cmake/fix-build-cmCurl-Avoid-using-undocumented-type-for-CURLOPT_NET.patch
Labels: bincapz/pass, ai/skip-comment

#53680 fix: we need devpts setup also outside chroot
  microvm-init.yaml
  microvm-init/init
Labels: bincapz/pass

#53677 chore(kubevela): vela-core-entrypoint compatibility package for upstream image compat
  kubevela.yaml
Labels: bincapz/pass

#53471 Add ldd-check tests to several packages
  apache-arrow.yaml
  lerna.yaml
  opendoas.yaml
  qemu.yaml
  renovate.yaml
  ssdeep.yaml
  strongswan.yaml
  tensorflow-core.yaml
  tensorflow-cpu-jupyter.yaml
  tomcat-native.yaml
  tpm2-tss.yaml
  tshark-4.4.yaml
  whereabouts.yaml
Labels: bincapz/blocking, malcontent/reviewed

#53708 glibc: no change rebuild to fix unstripped binaries
  glibc.yaml
Labels: bincapz/pass
