Repository wolfi-dev/os, pull requests merged in 2025-01, with the labels that each got.

#38575 fix the jar directory of the neo4j
  neo4j-5.26.yaml
Labels: bincapz/pass

#38580 new package: k8s-wait-for
  k8s-wait-for.yaml
Labels: bincapz/pass

#38563 pipelines: test: ldd-check: Add "packages" input parameter
  gcc.yaml
  pipelines/test/ldd-check.yaml
Labels: approved-to-run, eng:os

#38586 gitlab-cng-17.7: update registry-commit
  gitlab-cng-17.7.yaml
Labels: bincapz/pass

#38631 ruby3.4-activemodel: Update to match activesupport version
  ruby3.4-activemodel.yaml
  ruby3.4-activesupport.yaml
  ruby3.4-i18n.yaml
Labels: bincapz/pass

#38533 ruby 3.4: Bump gems for released ruby batch 6
  ruby3.4-addressable.yaml
  ruby3.4-async-io.yaml
  ruby3.4-async-pool.yaml
  ruby3.4-aws-sdk-cloudwatchlogs.yaml
  ruby3.4-aws-sdk-core.yaml
  ruby3.4-aws-sdk-kms.yaml
  ruby3.4-aws-sdk-s3.yaml
  ruby3.4-aws-sdk-sqs.yaml
  ruby3.4-aws-sigv4.yaml
  ruby3.4-elastic-transport.yaml
  ruby3.4-elasticsearch.yaml
  ruby3.4-excon.yaml
  ruby3.4-faraday-excon.yaml
  ruby3.4-faraday-follow_redirects.yaml
  ruby3.4-faraday_middleware-aws-sigv4.yaml
  ruby3.4-ffi-compiler.yaml
  ruby3.4-fluentd-1.17.yaml
  ruby3.4-http-accept.yaml
  ruby3.4-http-form_data.yaml
  ruby3.4-http.yaml
  ruby3.4-json-jwt.yaml
  ruby3.4-llhttp.yaml
  ruby3.4-mail.yaml
  ruby3.4-metrics.yaml
  ruby3.4-oauth2.yaml
  ruby3.4-redis-namespace.yaml
  ruby3.4-redis.yaml
  ruby3.4-rest-client.yaml
  ruby3.4-rspec.yaml
  ruby3.4-sidekiq.yaml
  ruby3.4-sinatra.yaml
  ruby3.4-swd.yaml
  ruby3.4-systemd-journal.yaml
  ruby3.4-tzinfo-data.yaml
  ruby3.4-tzinfo.yaml
  ruby3.4-webfinger.yaml
Labels: bincapz/pass

#38640 ruby 3.4: Bump gems for released ruby batch 7
  ruby3.4-async-http.yaml
  ruby3.4-fluent-config-regexp-type.yaml
  ruby3.4-kubeclient.yaml
  ruby3.4-logstash-core-plugin-api.yaml
  ruby3.4-logstash-core.yaml
  ruby3.4-logstash-mixin-ecs_compatibility_support.yaml
  ruby3.4-openid_connect-1.1.8.yaml
  ruby3.4-openid_connect.yaml
  ruby3.4-rack-oauth2.yaml
  ruby3.4-validate_email.yaml
  ruby3.4-validate_url.yaml
Labels: bincapz/pass

#38639 libb64-1.2: New package
  libb64-1.2.yaml
Labels: bincapz/pass

#37600 add jupyter-docker-stacks package
  jupyter-docker-stacks.yaml
Labels: bincapz/blocking, malcontent/reviewed

#38683 modelmesh-runtime-adapter/GHSA-w32m-9786-jp63 fix
  modelmesh-runtime-adapter.yaml
Labels: bincapz/pass

#38712 py3-cassandra-medusa: re-remove the grpc-health-probe dep
  py3-cassandra-medusa.yaml
Labels: bincapz/pass, approved-to-run

#38724 remove package `up`, update dependents to fetch prebuilt `up`
  crossplane-provider-aws.yaml
  crossplane-provider-azure.yaml
  crossplane-provider-gcp.yaml
  crossplane-provider-keycloak.yaml
  crossplane-provider-sql.yaml
  up.yaml
Labels: bincapz/pass, ai/skip-comment

#38726 Samba-4.21.2 build issue: Bumping epoch for talloc, tdb and tevent to rebuild with python 3.13
  talloc.yaml
  tdb.yaml
  tevent.yaml
Labels: bincapz/pass, approved-to-run

#38739 Fix a FTBFS with libxcb due to a missing dep
  libxcb.yaml
Labels: service:ftbfs, bincapz/pass

#38745 Fix a FTBFS with buck2 by pulling a new version
  buck2.yaml
  buck2/GHSA-hc92-9h3m-c39j.patch
Labels: service:ftbfs, bincapz/pass

#38780 fix missing static/assets issue
  superset.yaml
Labels: bincapz/pass

#38813 lychee: bump to 0.18.0
  lychee.yaml
  lychee/cargobump-deps.yaml
Labels: bincapz/pass

#38783 spdlog: cherry pick fix for compat with fmt >= 11.1
  spdlog.yaml
Labels: service:ftbfs, bincapz/pass, approved-to-run

#38778 Python multi-version py3-smbus
  i2c-tools.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#38840 py3-jupyterhub- multiversion
  py3-jupyterhub-firstuseauthenticator.yaml
  py3-jupyterhub-hmacauthenticator.yaml
  py3-jupyterhub-idle-culler.yaml
  py3-jupyterhub-ldapauthenticator.yaml
  py3-jupyterhub-ltiauthenticator.yaml
  py3-jupyterhub-nativeauthenticator.yaml
  py3-jupyterhub-tmpauthenticator.yaml
Labels: bincapz/pass

#38604 add neo4j docker-publish changes
  neo4j-5.26.yaml
Labels: bincapz/pass

#38845 feat(airflow.yaml): Bump epoch to force rebuild to remediate two jinja2 CVEs
  airflow.yaml
Labels: bincapz/pass

#38738 openfga-1.8.3: new package
  openfga.yaml
  openfga/test_auth_model.json
Labels: bincapz/pass

#38849 py3-pamela - fix FTBFS by updating repository url
  py3-pamela.yaml
Labels: bincapz/pass

#38781 openssf-compiler-options: allow -fdelete-null-pointer-checks to workaround abseil-cpp-related FTBFS
  abseil-cpp.yaml
  grpc-1.67.yaml
  libreoffice-24.8.yaml
  nodejs-22.yaml
  nodejs-23.yaml
  openssf-compiler-options.yaml
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/12/openssf.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/13/openssf.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/14/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/12/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/13/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/14/openssf.spec
  protobuf-c.yaml
  protobuf.yaml
  py3-grpcio-tools.yaml
Labels: service:ftbfs, bincapz/pass, approved-to-run, ai/skip-comment

#38860 openfga - fix ldflags for version/commit/timestamp
  openfga.yaml
Labels: bincapz/pass

#38842 Feat: python multiversion build for gi-docgen
  gi-docgen.yaml
Labels: bincapz/pass

#38882 Split docs to its own package
  lsb-release-minimal.yaml
Labels: bincapz/pass, approved-to-run

#38892 Split docs to its own package
  pwgen.yaml
Labels: bincapz/pass

#38900 Add compat package to create root level symlink, required by helm chart
  splunk-otel-collector.yaml
Labels: bincapz/pass

#38899 Restore gcc-11
  gcc-11.yaml
Labels: bincapz/pass, approved-to-run, eng:os

#38875 Builds kong
  kong.yaml
  kong/http-archive.patch
Labels: bincapz/pass

#38929 py3-jupyterhub-idle-culler: only the -bin package should provide the original
  py3-jupyterhub-idle-culler.yaml
Labels: bincapz/pass

#38911 Jenkins-2: GHSA-76h9-2vwh-w278 fix
  jenkins-2.yaml
Labels: bincapz/pass

#38961 Fix docs package and drop go from buildtime deps as this is pre-loaded by go/build
  splunk-otel-collector.yaml
Labels: bincapz/pass

#38957 rename subpackage to jupyter-docker-base
  jupyter-docker-stacks.yaml
Labels: bincapz/blocking

#38960 feat(kubeflow-jupyter-web-app.yaml): Bump epoch to force rebuild to remediate two jinja2 CVEs
  kubeflow-jupyter-web-app.yaml
Labels: bincapz/pass

#39016 gcc-11: modernize based on gcc-12 packaging
  gcc-11.yaml
  gcc-11/1be715f31605976d8e4336973d3b81c5b7cea79f.patch
  openssf-compiler-options.yaml
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/11/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/11/openssf.spec
Labels: bincapz/pass, approved-to-run

#39022 pipelines: test: ldd-check: Fix pass/fail/total counts
  pipelines/test/ldd-check.yaml
Labels: approved-to-run

#39023 Add php-8.4-swoole
  php-8.4-swoole.yaml
Labels: bincapz/pass, approved-to-run

#39015 feat(emissary.yaml): Bump jinja2 version to remediate two jinja2 CVEs
  emissary.yaml
Labels: bincapz/pass

#39035 openssf-compiler-options: gcc-11: drop -D_FORTIFY_SOURCE from 3->2
  openssf-compiler-options.yaml
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/11/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/11/openssf.spec
Labels: bincapz/pass

#39054 remove openfga compat from grpc-health-probe package
  grpc-health-probe.yaml
Labels: bincapz/pass

#39066 ca-certs: re-add support for Entrust certs
  ca-certificates.yaml
  ca-certificates/entrust.patch
Labels: bincapz/pass

#39082 openfga: add openfga-compat subpackage
  openfga.yaml
Labels: bincapz/pass

#38962 feat(kubeflow-volumes-web-app.yaml.yaml): Bump epoch to force rebuild to remediate two jinja2 CVEs
  kubeflow-volumes-web-app.yaml
Labels: bincapz/pass

#39010 feat(mlflow.yaml): Bump epoch to force rebuild to remediate two jinja2 CVEs
  mlflow.yaml
Labels: bincapz/pass

#39083 calico: bump epoch
  calico-3.29.yaml
Labels: bincapz/pass, approved-to-run

#39091 kyverno-notation-aws: build from tagged releases
  kyverno-notation-aws.yaml
Labels: bincapz/pass

#39105 openssf-compiler-options: gcc-11: Allow overriding -fno-delete-null-pointer
  openssf-compiler-options.yaml
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/11/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/11/openssf.spec
Labels: bincapz/pass

#39011 add jupyter-base-notebook package
  jupyter-base-notebook.yaml
Labels: bincapz/blocking, malcontent/reviewed

#39012 refactor jupyter-docker-stacks package
  jupyter-docker-stacks.yaml
Labels: bincapz/pass

#39036 Adds docker entrypoint for kong
  kong-entrypoint.yaml
Labels: bincapz/pass

#39136 Add the ldd-check test pipeline to more packages
  apache2.yaml
  async-profiler.yaml
  aws-crt-cpp.yaml
  aws-flb-firehose.yaml
  aws-flb-kinesis.yaml
  binaryen.yaml
  brunsli.yaml
  chromium.yaml
  cifs-utils.yaml
  cryptsetup.yaml
  cython-0.yaml
  dotnet-7.yaml
  enchant2.yaml
  erlang-25.yaml
  erlang-26.yaml
  falco.yaml
  fluent-bit-plugin-loki.yaml
  gcc-12.yaml
  gcc-13.yaml
  gcc-6.yaml
  gcc.yaml
  ggshield.yaml
  ghostscript.yaml
  gst-plugins-bad.yaml
  gtk-4.yaml
  helix.yaml
  hwloc.yaml
  imlib2.yaml
  iptables.yaml
  jack.yaml
  jruby-9.4.yaml
  jvmkill.yaml
  kube-fluentd-operator.yaml
Labels: bincapz/pass

#39135 jitsucom-jitsu: fix docker-start-console.sh by removing references to…
  jitsucom-jitsu.yaml
Labels: bincapz/pass

#38835 feat(new package): add nextflow
  nextflow.yaml
  nextflow/commons-io-2.14.0.patch
  nextflow/logback-core-1.5.13.patch
Labels: bincapz/pass, approved-to-run

#37794 systemd: Add misc dependencies for additional functionality
  systemd.yaml
  tpm2-tss.yaml
Labels: bincapz/blocking, malcontent/reviewed

#39145 kyverno-policy-reporter-ui/2.0.0 package update
  kyverno-policy-reporter-ui.yaml
Labels: bincapz/pass

#39058 remove unnecessary .pem files under examples folder
  erlang-26.yaml
Labels: bincapz/pass

#39209 bump to 17.7.1
  gitlab-cng-17.7.yaml
Labels: bincapz/pass

#39141 New Package: flyway (open-source database migration tool)
  flyway.yaml
  flyway/pombump-deps.yaml
Labels: bincapz/pass, approved-to-run

#39220 Add root level /kubectl symlink, for parity with upstream image and helm chart
  gatekeeper-3.17.yaml
Labels: bincapz/pass

#39224 symlink 'manager' binary to root level, which is where the operator expects it
  k8sgpt-operator.yaml
Labels: bincapz/pass

#39225 add provides to compat package
  gatekeeper-3.17.yaml
Labels: bincapz/pass

#39226 jitsucom-jitsu: Make docker-start-console.sh executable
  jitsucom-jitsu.yaml
Labels: bincapz/pass

#38673 systemd: Add container package for container related tools and daemons
  systemd.yaml
Labels: bincapz/blocking, malcontent/reviewed

#39265 grafana-image-renderer: fix GHSA-rhx6-c78j-4q9w
  grafana-image-renderer.yaml
  grafana-image-renderer/GHSA-rhx6-c78j-4q9w.patch
Labels: bincapz/pass

#39245 websockify: multiversion support
  websockify.yaml
Labels: bincapz/pass

#39274 provide gitlab through gitlab-cng for versioning
  gitlab-cng-17.7.yaml
Labels: bincapz/pass

#39103 k8s-device-plugin: Restore non-problematic openssf-compiler-options
  k8s-device-plugin.yaml
Labels: bincapz/pass, openssf-compiler-options

#39277 kubernetes-csi-node-driver-registrar: bump epoch
  kubernetes-csi-node-driver-registrar-2.13.yaml
Labels: bincapz/pass

#39278 fix(cert-manager): Force rebuild of packages and images following image fix
  cert-manager-1.16.yaml
Labels: bincapz/pass

#39263 add nss-passwords
  nss-passwords.yaml
Labels: bincapz/pass

#39293 Corrects file structure within kong-entrypoint
  kong-entrypoint.yaml
Labels: bincapz/pass

#39299 Adds header files from kong repo
  kong.yaml
Labels: bincapz/pass

#39294 ruby-activerecord: new packages
  ruby3.2-activerecord.yaml
  ruby3.3-activerecord.yaml
  ruby3.4-activerecord.yaml
Labels: bincapz/pass

#39033 Test rebuild of packages for the poetry update
  py3-aiohappyeyeballs.yaml
  py3-archspec.yaml
  py3-backoff.yaml
  py3-cleo.yaml
  py3-click-aliases.yaml
  py3-codeowners.yaml
  py3-crashtest.yaml
  py3-gcloud-aio-auth.yaml
  py3-gcloud-aio-storage.yaml
  py3-grpc-interceptor.yaml
  py3-isort.yaml
  py3-pkgconfig.yaml
  py3-reactivex.yaml
  py3-rich.yaml
  py3-rsa.yaml
  py3-tinydb.yaml
  py3-tomlkit.yaml
  py3-zaproxy.yaml
Labels: bincapz/pass

#39295 Create a subpackage that places `systemd-boot` as-if installed.
  systemd.yaml
Labels: bincapz/blocking, malcontent/reviewed, ai/skip-comment

#39322 grafana-mimir add subpkgs metaconvert, mimirtool, query-tee
  grafana-mimir.yaml
Labels: bincapz/pass, approved-to-run

#39279 jitsucom-jitsu: fix GHSA-7m27-7ghc-44w9
  jitsucom-jitsu.yaml
  jitsucom-jitsu/GHSA-7m27-7ghc-44w9.patch
Labels: bincapz/pass

#38582 compiler-hardening-check: Clarify test for -fhardened
  pipelines/test/compiler-hardening-check.yaml
Labels: approved-to-run

#39164 malcontent/GHSA-w32m-9786-jp63 fix
  malcontent.yaml
Labels: bincapz/blocking, malcontent/reviewed

#37597 tensorflow-cpu: add new package
  tensorflow-cpu.yaml
Labels: bincapz/blocking, malcontent/reviewed, ai/skip-comment

#38558 dpkg improvements
  dpkg.yaml
Labels: bincapz/pass, approved-to-run

#39441 bump gobump to use multilines for deps
  gobump.yaml
Labels: bincapz/pass

#37339 New Package: pgadmin4(most popular and feature rich Open Source admin…
  pgadmin4-17.yaml
Labels: bincapz/blocking, malcontent/reviewed, approved-to-run, ai/skip-comment

#39408 ruby3.x-builder: new package
  ruby3.2-builder.yaml
  ruby3.3-builder.yaml
  ruby3.4-builder.yaml
Labels: bincapz/pass

#38717 systemd: add standalone binaries
  systemd.yaml
Labels: bincapz/blocking, malcontent/reviewed

#34427 linux-headers: upgrade to v6.12
  linux-headers.yaml
Labels: bincapz/pass

#39473 updatebot: Fix issue polling for updates, switch to use git: poller
  exiftool.yaml
Labels: bincapz/pass

#39472 Fix for update-bot failing to poll repo - also flips from fork to main source repo
  py3-escapism.yaml
Labels: bincapz/pass

#39416 ruby-erubi: new packages
  ruby3.2-erubi.yaml
  ruby3.3-erubi.yaml
  ruby3.4-erubi.yaml
Labels: bincapz/pass

#39415 mysql-9.1: create default runtime directories during build
  mysql-9.1.yaml
Labels: bincapz/pass, approved-to-run

#38880 py3-cassandra-medusa: pin poetry version during build
  py3-cassandra-medusa.yaml
Labels: service:ftbfs, bincapz/pass, approved-to-run

#39534 tensorflow-cpu: match upstream release version
  tensorflow-cpu.yaml
Labels: bincapz/blocking

#39422 openjdk: Use JRE build for JRE subpackage
  java-common.yaml
  openjdk-11.yaml
  openjdk-17.yaml
  openjdk-21.yaml
  openjdk-22.yaml
  openjdk-23.yaml
Labels: bincapz/pass, ai/skip-comment

#39591 pull code from git and use git poller. update to latest version. Add …
  py3-python-crfsuite.yaml
Labels: bincapz/pass

#39592 Update Git checkout URL
  sqlite.yaml
Labels: bincapz/pass

#39584 use var-transforms to construct the right version and tag. Update git…
  kpt.yaml
Labels: bincapz/pass

#39582 Updatebot w3m package
  w3m.yaml
  withdrawn-packages.txt
Labels: bincapz/pass

#39604 docker-credential-ecr-login: fetch2checkout and build with hashes
  docker-credential-ecr-login.yaml
Labels: bincapz/pass

#39634 yara-x: install built artifacts into yara-x package
  yara-x.yaml
Labels: bincapz/pass

#39646 tileserver-gl: rebuilding with latest libpng-dev
  tileserver-gl.yaml
Labels: bincapz/pass, approved-to-run

#39656 kafka: add missing symlinks as upstream image has already
  kafka-3.9.yaml
Labels: bincapz/pass

#39645 mlflow: bump epoch
  mlflow.yaml
Labels: bincapz/pass

#39545 Add basic pre-commit config
  .github/workflows/lint.yaml
  .pre-commit-config.yaml
  asciidoc.yaml
  asciidoc/allow-specify-python.patch
Labels: staging-build, bincapz/pass

#39670 fix(opentelemetry-plugin-nginx): Pin nginx to 1.25.5
  opentelemetry-plugin-nginx.yaml
Labels: bincapz/pass, ai/skip-comment

#39696 Switch some packages from using the ldd-check with specific files to the package
  aws-c-auth.yaml
  aws-c-cal.yaml
  aws-c-common.yaml
  aws-c-compression.yaml
  aws-c-event-stream.yaml
  aws-c-http.yaml
  aws-c-mqtt.yaml
  aws-c-s3.yaml
  aws-c-sdkutils.yaml
  aws-checksums.yaml
  expat.yaml
  rtmpdump.yaml
  s2n-tls.yaml
Labels: bincapz/pass

#39689 fix: Stream OTel plugin with ingress nginx
  ingress-nginx-controller-1.12.yaml
  opentelemetry-plugin-nginx.yaml
Labels: bincapz/pass, ai/skip-comment

#39732 dbus: add systemd build depends
  dbus.yaml
Labels: bincapz/pass

#39413 chrony: fix invalid configs, provide cloud configs
  chrony.yaml
  chrony/50-chronyd.list
  chrony/chrony.conf
  chrony/chronyd.confd
  chrony/chronyd.initd
  chrony/conf.d/aws.conf
  chrony/conf.d/azure.conf
  chrony/max_resolve_interval.patch
  chrony/sources.d/aws.sources
  chrony/sources.d/azure.sources
  chrony/sources.d/gcp.sources
  chrony/sysusers.d/chrony.conf
  chrony/timepps.h
Labels: bincapz/pass

#39715 feat/ruby3 fluentd kubernetes daemonset 1.18 version stream
  ruby3.1-fluentd-kubernetes-daemonset-1.18.yaml
  ruby3.2-fluentd-kubernetes-daemonset-1.18.yaml
  ruby3.3-fluentd-kubernetes-daemonset-1.18.yaml
  ruby3.4-fluentd-kubernetes-daemonset-1.18.yaml
Labels: bincapz/pass

#39733 add runtime deps to aspnet-runtime
  dotnet-8.yaml
  dotnet-9.yaml
Labels: bincapz/pass

#39751 systemd - make systemd-init package provide /sbin/init rather than /init
  systemd.yaml
Labels: bincapz/blocking

#39752 fix(ingress-nginx-otel-plugin): Drop controller from runtime deps
  ingress-nginx-controller-1.12.yaml
Labels: bincapz/pass

#32446 glibc.yaml: Add openssf-options (and disable it)
  glibc.yaml
Labels: P1, bincapz/pass, openssf-compiler-options, approved-to-run, eng:containers

#39779 More ldd checks to packages
  apk-tools.yaml
  btrfs-progs.yaml
  cyrus-sasl.yaml
  gdbm.yaml
  glibc.yaml
  gmp.yaml
  inih.yaml
  isl.yaml
  jq.yaml
  libevent.yaml
  libffi.yaml
  libgpg-error.yaml
  linux-pam.yaml
  lua-luv.yaml
  luajit.yaml
  mpc.yaml
  mpdecimal.yaml
  mpfr.yaml
  msgpack-c.yaml
  ncurses.yaml
  oniguruma.yaml
  pkgconf.yaml
  popt.yaml
  readline.yaml
  shadow.yaml
  tree-sitter.yaml
  unibilium.yaml
  userspace-rcu.yaml
  xfsprogs.yaml
  xz.yaml
  zlib.yaml
Labels: bincapz/pass

#39788 Build containerboot wrapper for Tailscale
  tailscale.yaml
Labels: bincapz/pass

#39793 chrony: disable NTS, MAC, MS-NTP unused or requires bootstrap
  chrony.yaml
Labels: bincapz/pass

#39798 fix updates and download url. Expand test coverage
  netcat-openbsd.yaml
Labels: bincapz/pass

#39801 switch to use git: poller and pull source from gitlab
  at-spi2-core.yaml
Labels: bincapz/pass

#39781 remove errorneous removal of debug from go.mod
  kubernetes-1.32.yaml
  nri-mssql.yaml
Labels: approved-to-run

#39764 fix(yara-x): build+add primary yr cli tool to yara-x, drop compat package, use distro cargo-c
  yara-x.yaml
Labels: bincapz/pass

#39830 openjdk 24: split JRE and mark as beta
  openjdk-24.yaml
  withdrawn-packages.txt
Labels: bincapz/pass

#39870 ruby3.x-sin_lru_redux: introduce new packages
  ruby3.2-sin_lru_redux.yaml
  ruby3.3-sin_lru_redux.yaml
  ruby3.4-sin_lru_redux.yaml
Labels: bincapz/pass

#39877 fix auto-updates and re-enable. Add tests
  libmilter.yaml
Labels: bincapz/pass

#39876 ruby*-lru_redux: add testing
  ruby3.2-lru_redux.yaml
  ruby3.3-lru_redux.yaml
  ruby3.4-lru_redux.yaml
Labels: bincapz/pass

#39663 dynamically link kong to system openssl
  kong.yaml
  kong/openssl.patch
Labels: bincapz/pass

#39901 Add yara-x patch to reduce virtual memory usage
  yara-x.yaml
  yara-x/reservation.patch
Labels: bincapz/pass

#39899 batch 9: go epoch bump
  policy-controller.yaml
  pombump.yaml
  portieris.yaml
  postgres-operator.yaml
  prometheus-3.1.yaml
  prometheus-adapter.yaml
  prometheus-alertmanager.yaml
  prometheus-beat-exporter.yaml
  prometheus-bind-exporter.yaml
  prometheus-blackbox-exporter.yaml
  prometheus-elasticsearch-exporter.yaml
  prometheus-mongodb-exporter.yaml
  prometheus-mysqld-exporter.yaml
  prometheus-nats-exporter.yaml
  prometheus-node-exporter.yaml
  prometheus-operator.yaml
  prometheus-podman-exporter.yaml
  prometheus-postgres-exporter.yaml
  prometheus-pushgateway.yaml
  prometheus-redis-exporter.yaml
  prometheus-stackdriver-exporter.yaml
  prometheus-statsd-exporter.yaml
  promxy.yaml
  protoc-gen-go-grpc.yaml
  protoc-gen-go.yaml
  pulumi-kubernetes-operator.yaml
  pulumi-language-dotnet.yaml
  pulumi-language-java.yaml
  pulumi-language-yaml.yaml
  pulumi.yaml
  q.yaml
  rabbitmq-cluster-operator.yaml
  rabbitmq-default-user-credential-updater.yaml
  rabbitmq-messaging-topology-operator.yaml
  rancher-agent-2.10.yaml
  rancher-fleet.yaml
  rancher-loglevel.yaml
  rancher-webhook-0.6.yaml
  rclone.yaml
  redka.yaml
  regclient.yaml
  rekor.yaml
  render-template.yaml
  restic.yaml
  rook.yaml
  rootlesskit.yaml
  rqlite.yaml
  runc.yaml
  s5cmd.yaml
Labels: bincapz/pass, ai/skip-comment

#39898 batch 8: go epoch bump
  nfs-subdir-external-provisioner.yaml
  nginx-prometheus-exporter.yaml
  node-feature-discovery-0.17.yaml
  node-problem-detector-0.8.yaml
  nodetaint.yaml
  nri-apache.yaml
  nri-cassandra.yaml
  nri-consul.yaml
  nri-couchbase.yaml
  nri-discovery-kubernetes.yaml
  nri-elasticsearch.yaml
  nri-f5.yaml
  nri-haproxy.yaml
  nri-jmx.yaml
  nri-kafka.yaml
  nri-kubernetes.yaml
  nri-memcached.yaml
  nri-mongodb.yaml
  nri-mssql.yaml
  nri-mysql.yaml
  nri-nagios.yaml
  nri-nginx.yaml
  nri-postgresql.yaml
  nri-prometheus.yaml
  nri-rabbitmq.yaml
  nri-redis.yaml
  nsc.yaml
  nuclei.yaml
  nvidia-container-toolkit.yaml
  oauth2-proxy.yaml
  octo-sts.yaml
  ollama.yaml
  opa.yaml
  openbao-k8s.yaml
  openbao.yaml
  openfga.yaml
  opentelemetry-collector-contrib.yaml
  opentelemetry-collector.yaml
  opentelemetry-operator.yaml
  opentofu-1.9.yaml
  oras.yaml
  osv-scanner.yaml
  overmind.yaml
  paranoia.yaml
  pdfcpu.yaml
  petname.yaml
  php-fpm_exporter.yaml
  pluto.yaml
Labels: bincapz/pass, ai/skip-comment

#39893 batch 3: go epoch bump
  dgraph.yaml
  direnv.yaml
  distribution.yaml
  dive.yaml
  docker-cli-buildx.yaml
  docker-cli.yaml
  docker-compose.yaml
  docker-credential-acr-env.yaml
  docker-credential-ecr-login.yaml
  docker-credential-gcr.yaml
  docker.yaml
  dockerize.yaml
  doppler-kubernetes-operator.yaml
  dynamic-localpv-provisioner.yaml
  eksctl.yaml
  elvish.yaml
  emissary.yaml
  envoy-gateway.yaml
  esbuild.yaml
  etcd-3.5.yaml
  external-dns.yaml
  external-secrets-operator.yaml
  extism.yaml
  falco-exporter.yaml
  falcoctl.yaml
  falcosidekick.yaml
  ferretdb.yaml
  filebrowser.yaml
  flannel-cni-plugin.yaml
  flannel.yaml
  fluent-bit-plugin-loki.yaml
  flux-2.4.yaml
  flux-helm-controller.yaml
  flux-image-automation-controller.yaml
  flux-image-reflector-controller.yaml
  flux-kustomize-controller.yaml
  flux-notification-controller.yaml
  flux-source-controller.yaml
  flux.yaml
  flyte.yaml
  fq.yaml
  frp.yaml
  fscrypt.yaml
  fulcio.yaml
  fuse-overlayfs-snapshotter.yaml
  fzf.yaml
  gatekeeper-3.18.yaml
  gcp-compute-persistent-disk-csi-driver-1.15.yaml
Labels: bincapz/blocking, ai/skip-comment

#39892 batch 2: go epoch bump
  cfssl.yaml
  chartmuseum.yaml
  checksec.yaml
  chezmoi.yaml
  cilium-1.16.yaml
  cilium-cli.yaml
  cilium-envoy-1.16.yaml
  cloud-provider-aws-1.31.yaml
  cloud-provider-aws-1.32.yaml
  cloud-provider-azure-1.32.yaml
  cloud-sql-proxy.yaml
  cloudflared.yaml
  cloudprober.yaml
  cluster-api-controller.yaml
  cluster-autoscaler-1.32.yaml
  cluster-proportional-autoscaler.yaml
  clusterctl.yaml
  cni-plugins.yaml
  configmap-reload.yaml
  confluent-common-docker.yaml
  conftest.yaml
  consul-k8s-1.6.yaml
  containerd-1.yaml
  containerd-2.yaml
  contour-1.30.yaml
  controller-gen.yaml
  coredns.yaml
  cortex.yaml
  cosign.yaml
  crane.yaml
  cri-tools.yaml
  croc.yaml
  crossplane-provider-aws.yaml
  crossplane-provider-azure.yaml
  crossplane-provider-gcp.yaml
  crossplane-provider-keycloak.yaml
  crossplane-provider-sql.yaml
  crossplane.yaml
  ctop.yaml
  cue.yaml
  dagdotdev.yaml
  dagger.yaml
  dask-gateway.yaml
  datadog-agent.yaml
  dataplaneapi.yaml
  dbmate.yaml
  delve.yaml
  descheduler.yaml
  dex.yaml
Labels: ai/skip-comment

#39895 batch 5: go epoch bump
  harbor-2.12.yaml
  harbor-cli.yaml
  harbor-registry.yaml
  harbor-scanner-trivy.yaml
  hcloud.yaml
  hello-world-golang.yaml
  helm-docs.yaml
  helm-push.yaml
  helm.yaml
  hey.yaml
  hivemind.yaml
  http-echo.yaml
  hubble-ui.yaml
  hubble.yaml
  hugo-extended.yaml
  hugo.yaml
  influx.yaml
  influxd.yaml
  ingress-nginx-controller-1.12.yaml
  ini-file.yaml
  ip-masq-agent.yaml
  ipfs.yaml
  istio-1.24.yaml
  jaeger-operator.yaml
  jitsucom-bulker.yaml
  k3d.yaml
  k3s.yaml
  k6.yaml
  k8s-device-plugin.yaml
  k8sgpt-operator.yaml
  k8sgpt.yaml
  k8ssandra-client.yaml
  k8ssandra-operator.yaml
  k9s.yaml
  kaf.yaml
  kafka-proxy.yaml
  kafka_exporter.yaml
  kaniko.yaml
  kapp-controller.yaml
  kapp.yaml
  kargo.yaml
  karpenter-1.0.yaml
  kbld.yaml
  keda-2.16.yaml
  kind.yaml
  kine.yaml
Labels: bincapz/pass, ai/skip-comment

#39891 batch 1: go epoch bump
  actions-runner-controller.yaml
  addon-resizer.yaml
  age.yaml
  amass.yaml
  amazon-cloudwatch-agent-operator.yaml
  amazon-cloudwatch-agent.yaml
  amazon-corretto-crypto-provider.yaml
  amazon-k8s-cni.yaml
  apko.yaml
  argo-cd-2.13.yaml
  argo-events.yaml
  argo-rollouts.yaml
  argocd-image-updater.yaml
  atlantis.yaml
  authservice.yaml
  aws-application-networking-k8s.yaml
  aws-eks-pod-identity-agent.yaml
  aws-flb-cloudwatch.yaml
  aws-flb-firehose.yaml
  aws-flb-kinesis.yaml
  aws-load-balancer-controller.yaml
  aws-network-policy-agent.yaml
  aws-privateca-issuer.yaml
  azcopy.yaml
  azuredisk-csi-1.31.yaml
  bank-vaults.yaml
  bazelisk.yaml
  bom.yaml
  boring-registry.yaml
  buf.yaml
  buildah.yaml
  buildkitd.yaml
  bun.yaml
  caddy.yaml
  cadvisor.yaml
  calico-3.29.yaml
  capslock.yaml
  cargobump.yaml
  cass-operator.yaml
  cert-exporter.yaml
  cert-manager-1.16.yaml
  cert-manager-cmctl.yaml
  cert-manager-istio-csr.yaml
  cert-manager-webhook-pdns.yaml
  certificate-transparency.yaml
Labels: bincapz/pass, ai/skip-comment

#39897 batch 7: go epoch bump
  kyverno-policy-reporter-ui.yaml
  kyverno-policy-reporter.yaml
  lazydocker.yaml
  lazygit.yaml
  libnvidia-container.yaml
  linkerd2-proxy-init.yaml
  linkerd2.yaml
  litefs.yaml
  litestream.yaml
  local-path-provisioner.yaml
  local-static-provisioner.yaml
  logstash-exporter.yaml
  loki-3.3.yaml
  mage.yaml
  mailpit.yaml
  malcontent.yaml
  mattermost-10.3.yaml
  mc.yaml
  melange.yaml
  melange/example.yaml
  memcached-exporter.yaml
  metacontroller.yaml
  metallb.yaml
  metrics-server.yaml
  minify.yaml
  minio.yaml
  mkcert.yaml
  mockery.yaml
  mockgen.yaml
  modelmesh-runtime-adapter.yaml
  mods.yaml
  mongo-tools.yaml
  mountpoint-s3-csi-driver.yaml
  multus-cni.yaml
  nats-server.yaml
  nats.yaml
  nerdctl.yaml
  neuvector-scanner.yaml
  neuvector-sigstore-interface.yaml
  newrelic-fluent-bit-output.yaml
  newrelic-infra-operator.yaml
  newrelic-infrastructure-agent.yaml
  newrelic-infrastructure-bundle.yaml
  newrelic-k8s-metadata-injection.yaml
  newrelic-nri-kube-events.yaml
  newrelic-prometheus-configurator.yaml
Labels: bincapz/blocking, malcontent/reviewed, ai/skip-comment

#39896 batch 6: go epoch bump
  ko.yaml
  kor.yaml
  kpt.yaml
  kserve-rest-proxy.yaml
  ksops.yaml
  kube-bench.yaml
  kube-fluentd-operator.yaml
  kube-logging-operator.yaml
  kube-metrics-adapter.yaml
  kube-rbac-proxy.yaml
  kube-state-metrics.yaml
  kube-vip.yaml
  kubeadm-bootstrap-controller.yaml
  kubeadm-controlplane-controller.yaml
  kubebuilder.yaml
  kubecolor.yaml
  kubeflow-katib.yaml
  kubeflow-pipelines.yaml
  kuberlr.yaml
  kubernetes-1.32.yaml
  kubernetes-csi-driver-hostpath.yaml
  kubernetes-csi-external-provisioner.yaml
  kubernetes-csi-external-resizer.yaml
  kubernetes-csi-external-snapshotter-8.1.yaml
  kubernetes-csi-livenessprobe.yaml
  kubernetes-csi-node-driver-registrar-2.13.yaml
  kubernetes-dashboard-auth.yaml
  kubernetes-dashboard-metrics-scraper.yaml
  kubernetes-dashboard-web.yaml
  kubernetes-dashboard.yaml
  kubernetes-dns-node-cache.yaml
  kubernetes-event-exporter.yaml
  kubernetes-ingress-defaultbackend.yaml
  kubernetes-release.yaml
  kubernetes-replicator.yaml
  kubescape.yaml
  kubevela.yaml
  kubewatch.yaml
  kuma-2.9.yaml
  kustomize.yaml
  kyverno-1.13.yaml
  kyverno-notation-aws.yaml
  kyverno-policy-reporter-kyverno-plugin.yaml
Labels: ai/skip-comment

#39889 Add flyway symlinks
  flyway.yaml
Labels: bincapz/pass, approved-to-run

#33754 new pkg: google-authenticator
  google-authenticator.yaml
Labels: approved-to-run

#39914 knative-serving package build
  knative-serving-1.16.yaml
Labels: bincapz/pass

#39912 Add liblmdb.so and liblmdb.so.0 symlinks
  lmdb.yaml
Labels: bincapz/pass

#39916 iproute2: disable capabilities until bots are updated so they can parse the new melange config
  iproute2.yaml
Labels: bincapz/pass

#39905 enable auto-updates, update to latest version, switch to git poller a…
  wasi-libc.yaml
Labels: bincapz/pass

#39639 kubeflow-pipelines-visualization-server: bump to use Python 3.11
  kubeflow-pipelines-visualization-server.yaml
  kubeflow-pipelines-visualization-server/0001-Bump-dependencies.patch
Labels: bincapz/pass

#39908 New package rustfilt
  rustfilt.yaml
  rustfilt/cargobump-deps.yaml
Labels: bincapz/pass, ai/skip-comment

#39911 rebuild airflow for apache-airflow-providers-celery 3.8.5 version
  airflow.yaml
Labels: bincapz/pass

#40015 protobuf-c: bump epoch to rebuild against new libprotobuf
  protobuf-c.yaml
Labels: bincapz/pass

#40049 fix: version bump for both logback jars to 1.5.13
  nextflow.yaml
  nextflow/logback-core-1.5.13.patch
Labels: bincapz/pass, approved-to-run

#40069 add new package: incert
  incert.yaml
Labels: bincapz/pass

#39981 apache2: update epoch to 6 and add curl dependency; download httpd-fo…
  apache2.yaml
Labels: bincapz/pass, approved-to-run
