Repository wolfi-dev/os, pull requests merged in 2025-10, with the labels that each got.

#67761 feat(code-server): bump dep to remediate GHSA-vj76-c3g6-qr5v
  code-server.yaml
Labels: bincapz/pass

#67857 openjdk-25: use self for bootstrap.
  openjdk-25.yaml
Labels: bincapz/pass

#67809 Add debianutils package
  debianutils.yaml
Labels: bincapz/pass, ai/skip-comment

#67788 jenkins-docker-agent: add missing runtime deps
  jenkins-2.yaml
Labels: bincapz/pass

#67873 Splits curl-static from -dev package
  curl.yaml
Labels: bincapz/pass

#67894 chore(jenkins-utils): Add curl
  jenkins-2.yaml
Labels: bincapz/pass

#67946 py3-setuptools-scm - add a -bin package.
  py3-setuptools-scm.yaml
Labels: bincapz/pass

#61219 add extra functionality to ip and friends
  iproute2.yaml
Labels: bincapz/pass

#67980 py3-pipenv: pip propagation rebuild: 2/3
  py3-pipenv.yaml
Labels: bincapz/pass

#68037 qemu - split edk2 files out to dependent subpackage
  qemu.yaml
Labels: bincapz/blocking, malcontent/reviewed

#68033 pdns-nosodium subpackages
  pdns-5.2.yaml
Labels: bincapz/pass

#67801 Pin the packages to clang-20 to prevent FTBFS with new llvm release
  dotnet-8.yaml
  dotnet-9.yaml
  libmamba.yaml
Labels: bincapz/pass, ai/skip-comment

#68030 improve kafka-proxy
  kafka-proxy.yaml
Labels: bincapz/pass

#67654 fix(fluentd): properly look up target version dir
  ruby3.2-fluentd-1.19.yaml
  ruby3.3-fluentd-1.17.yaml
  ruby3.4-fluentd-1.17.yaml
Labels: bincapz/pass, ai/skip-comment

#68099 Adds a number of core runtime dependencies required by jenkins-inbound-agent image
  jenkins-2.yaml
Labels: bincapz/pass

#66812 2609 jaeger stream
  jaeger-2.yaml
  jaeger-2/sampling_strategies.json
  jaeger/fix-build-react-icons-typescript-errors.patch
  withdrawn-packages.txt
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#68117 orthanc-{gdcm,python}: Pin boost-dev~1.88
  orthanc-gdcm.yaml
  orthanc-python.yaml
Labels: bincapz/pass

#68112 llvm-{20,21}: make libLLVM co-installable
  llvm-20.yaml
  llvm-21.yaml
Labels: bincapz/pass

#68186 chore(tw): bump epoch and rebuild for help-check
  tw.yaml
Labels: bincapz/pass

#68187 Switch 7zip and acl to using tw's help-check
  7zip.yaml
  acl.yaml
Labels: bincapz/pass

#68190 Add v18 for postgres dependent packages
  postgis-18
  postgis-18.yaml
  repmgr-18.yaml
Labels: bincapz/pass, ai/skip-comment

#68298 bumping fluent-operator version to resolve build failures
  fluent-operator.yaml
Labels: bincapz/pass

#68319 chore(bank-vaults): fix package updates
  bank-vaults.yaml
Labels: bincapz/pass

#68128 keycloak-26.4: introduce keycloak-operator subpackage
  keycloak-26.4.yaml
  keycloak-operator.yaml
Labels: bincapz/pass, ai/skip-comment

#68340 nasm: remove unused sed
  nasm.yaml
Labels: bincapz/pass

#68155 coredns: version stream
  coredns-1.13.yaml
  coredns-1.13/kuma-plugin.cfg
Labels: bincapz/pass

#68347 ncurses: housekeeping
  ncurses.yaml
  withdrawn-packages.txt
Labels: bincapz/pass

#68308 php-8.*: use external pcre
  php-8.1.yaml
  php-8.2.yaml
  php-8.3.yaml
  php-8.4.yaml
Labels: bincapz/pass

#68276 glibc: cherry-pick 855bfa256 for openjdk-17 fixes
  glibc.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment
