Repository wolfi-dev/os, pull requests merged in 2025-08, with the labels that each got.

#61356 feat(opentelemetry-collector): bump dep to remediate GHSA-x4rx-4gw3-53p4
  opentelemetry-collector.yaml
Labels: bincapz/pass

#61364 feat: add oauth2-proxy iamguarded compat subpkg
  oauth2-proxy.yaml
Labels: bincapz/pass, ai/skip-comment

#61082 feat: adds package kube-arangodb
  kube-arangodb.yaml
Labels: bincapz/pass

#61365 Harbor epoch
  harbor-2.13.yaml
Labels: bincapz/pass, approved-to-run

#61450 gcc(-14): fix shellcheck issue and a bug it found
  gcc-14.yaml
  gcc.yaml
Labels: bincapz/pass

#61434 spire-server: fix shellcheck issue and remove unused code
  spire-server.yaml
Labels: bincapz/pass

#61439 coreutils/uutils: Test the correct printf command
  coreutils.yaml
  uutils.yaml
Labels: bincapz/pass

#61208 apicurio-registry: switch to multi arch builds and switch to ecosystems maven
  apicurio-registry.yaml
Labels: bincapz/pass, ai/skip-comment

#61218 Bump tensorflow-core with Axion fixes
  tensorflow-core.yaml
Labels: ai/skip-comment

#61460 keycloak-config-cli: fix shellcheck errors
  keycloak-config-cli.yaml
Labels: ai/skip-comment

#61458 Build Dotnet with Axion fixes
  dotnet-6.yaml
  dotnet-7.yaml
  dotnet-8.yaml
  dotnet-9.yaml
Labels: bincapz/pass, ai/skip-comment

#61581 feat: adds package serve:14.2.4
  serve.yaml
Labels: bincapz/pass

#61633 python-3.13.yaml: fix shellcheck error
  python-3.13.yaml
Labels: bincapz/pass

#61575 datadog-operator package build
  datadog-operator.yaml
Labels: bincapz/pass

#61646 pgpool2-4.6.yaml: fix shellcheck errors
  pgpool2-4.6.yaml
Labels: bincapz/pass

#61652 No change rebuild of packages not built recently
  check.yaml
  libpfm.yaml
Labels: bincapz/pass

#61668 grafana-pyroscope-1.13: remediate cve
  grafana-pyroscope-1.13.yaml
  grafana-pyroscope-1.13/remove-oauth2-proxy.patch
Labels: bincapz/pass, ai/skip-comment

#61674 feat(cluster-api): add capd-manager
  cluster-api-1.10.yaml
Labels: bincapz/pass

#61570 add rspamd package
  rspamd.yaml
Labels: bincapz/pass

#61485 Add test/no-docs pipeline to batch 07 packages
  dash.yaml
  db.yaml
  dbus-glib.yaml
  dbus.yaml
  dhclient.yaml
  dhcping.yaml
  dieharder.yaml
  diffutils.yaml
  dmidecode.yaml
  dnsmasq.yaml
Labels: bincapz/pass

#61486 Add test/no-docs pipeline to batch 06 packages
  coreutils.yaml
  couchdb-3.3.yaml
  cpio.yaml
  cppunit.yaml
  cronie.yaml
  crun.yaml
  cryptsetup.yaml
  cups.yaml
  cyrus-sasl.yaml
Labels: bincapz/pass

#61754 Add test/no-docs pipeline to batch 13 packages
  iperf.yaml
  iproute2.yaml
  ipset.yaml
  iptables.yaml
  ipvsadm.yaml
  isa-l.yaml
  itstool.yaml
  ivykis.yaml
  jack.yaml
  jasper.yaml
Labels: bincapz/pass

#61757 Add test/no-docs pipeline to batch 16 packages
  libasyncns.yaml
  libatasmart.yaml
  libatomic_ops.yaml
  libb64-1.2.yaml
  libbsd.yaml
  libburn.yaml
  libcap-ng.yaml
  libcap.yaml
  libcmis.yaml
  libdaemon.yaml
Labels: bincapz/pass

#61773 feat: add cloud-provider-gcp-cloud-controller-manager package
  cloud-provider-gcp-cloud-controller-manager.yaml
Labels: bincapz/pass

#61825 Ignore checks for packages with known setuidgid usage
  apache2.yaml
  datadog-agent.yaml
  fuse2.yaml
  fuse3.yaml
  krb5.yaml
  libutempter.yaml
  nfs-utils.yaml
  opendoas.yaml
  openssh.yaml
  polkit.yaml
  postfix.yaml
  screen.yaml
  shadow.yaml
  util-linux.yaml
  xorg-server.yaml
Labels: bincapz/pass

#60998 postgresql plpython
  postgresql-17.yaml
Labels: bincapz/pass, approved-to-run

#61853 Revert "Repackages crossplane-provider-aws"
  crossplane-provider-aws.yaml
  withdrawn-packages.txt
Labels: bincapz/pass

#61579 correct release/ build for arm too
  font-stix-otf-arm.yaml
Labels: bincapz/pass, approved-to-run

#61751 fix(clickhouse-25.5): broken symlinks to build targets
  clickhouse-25.5.yaml
Labels: bincapz/pass, ai/skip-comment

#61845 add quiche package
  quiche.yaml
Labels: bincapz/pass

#61786 add xdp-tools
  xdp-tools.yaml
Labels: bincapz/pass

#61844 feat: adds package plugin-barman-cloud
  plugin-barman-cloud.yaml
Labels: bincapz/pass, malcontent/reviewed

#61925 xorg: provide lowercase xvfb and xnest
  xorg-server.yaml
Labels: bincapz/pass

#61776 add: headlamp package
  headlamp.yaml
Labels: bincapz/pass, approved-to-run

#62004 squid: disable -march=native
  squid.yaml
Labels: bincapz/pass

#61991 py3-trove-classifiers: move commands to -bin
  py3-trove-classifiers.yaml
Labels: bincapz/pass

#61885 add dnsdist
  dnsdist-2.0.yaml
  quiche.yaml
Labels: bincapz/pass, ai/skip-comment

#62065 nfs-utils: Fix build with glibc 2.42
  nfs-utils.yaml
  nfs-utils/fix-build-glibc-2.42.patch
Labels: bincapz/pass

#61969 Add test/no-docs pipeline to batch 20 packages
  ltrace.yaml
  lttng-ust.yaml
  lua5.3.yaml
  lua5.4.yaml
  luajit.yaml
  luit.yaml
  lvm2.yaml
  lynx.yaml
  lz4.yaml
  lzip.yaml
Labels: bincapz/pass

#62088 wget: build with gcc-14
  wget.yaml
Labels: bincapz/pass

#62518 add missing runtime dependency for headlamp-plugin-flux
  headlamp-plugin-flux.yaml
Labels: bincapz/pass, approved-to-run

#61933 cloud-provider-vsphere package build
  cloud-provider-vsphere.yaml
Labels: bincapz/pass

#60350 Package Update: ruby3.2-aws-partitions to version 1.1132.0
  ruby3.2-aws-partitions.yaml
Labels: automated pr, bincapz/pass, ltver

#60312 Package Update: ruby3.2-aws-eventstream to version 1.4.0
  ruby3.2-aws-eventstream.yaml
Labels: automated pr, bincapz/pass, ltver

#62081 Fix `test/compiler/asan` on GCC 14
  gcc-14.yaml
  pipelines/test/compiler/asan.yaml
Labels: bincapz/pass

#62856 aom: various fixes
  aom.yaml
  aom/ftbfs-include-cmath.patch
Labels: bincapz/pass, ai/skip-comment

#60352 Package Update: ruby3.2-aws-sdk-core to version 3.227.0
  ruby3.2-aws-sdk-core.yaml
Labels: automated pr, bincapz/pass, ltver

#62071 Fix GCC/LLVM builds with glibc 2.42
  gcc-14.yaml
  gcc-14/fix-build-glibc-2.42.patch
  llvm-16.yaml
  llvm-16/fix-build-glibc-2.42-01.patch
  llvm-16/fix-build-glibc-2.42-02.patch
  llvm-17.yaml
  llvm-17/fix-build-glibc-2.42-01.patch
  llvm-17/fix-build-glibc-2.42-02.patch
  llvm-18.yaml
  llvm-18/fix-build-glibc-2.42-01.patch
  llvm-18/fix-build-glibc-2.42-02.patch
  llvm-19.yaml
  llvm-19/fix-build-glibc-2.42-01.patch
  llvm-19/fix-build-glibc-2.42-02.patch
Labels: bincapz/pass

#62657 mesosphere-vsphere-csi driver and syncer package build
  mesosphere-vsphere-csi.yaml
Labels: bincapz/blocking, malcontent/reviewed

#60351 Package Update: ruby3.2-aws-sdk-cloudwatchlogs to version 1.122.0
  ruby3.2-aws-sdk-cloudwatchlogs.yaml
Labels: automated pr, bincapz/pass, ltver

#61829 kayenta 2.46 package build
  kayenta-2.46.yaml
  kayenta-2.46/upgrade-dependencies.patch
Labels: ai/skip-comment

#62829 Add test/no-docs pipeline to batch 28 packages
  perl-file-sharedir-install.yaml
  perl-file-sharedir.yaml
  perl-html-tagset.yaml
  perl-http-cookies.yaml
  perl-http-date.yaml
  perl-http-message.yaml
  perl-http-negotiate.yaml
  perl-importer.yaml
  perl-inc-latest.yaml
  perl-io-html.yaml
  perl-ipc-run3.yaml
  perl-json-maybexs.yaml
  perl-json.yaml
  perl-lwp-mediatypes.yaml
  perl-lwp-protocol-https.yaml
Labels: bincapz/pass

#62941 openjpeg: convert to git-checkout, cherry-pick CVE fix
  openjpeg.yaml
Labels: bincapz/pass

#63000 fix: removing grpc-health-probe as a runtime dep as it is not require…
  spicedb.yaml
Labels: bincapz/pass

#63017 Add libnetfilter_log package.
  libnetfilter_log.yaml
Labels: bincapz/pass

#63083 Fix OpenJDK FTBFS with glibc 2.42
  openjdk-11.yaml
  openjdk-11/fix-build-with-glibc-2.42.patch
  openjdk-12.yaml
  openjdk-12/fix-build-with-glibc-2.42.patch
  openjdk-13.yaml
  openjdk-13/fix-build-with-glibc-2.42.patch
  openjdk-14.yaml
  openjdk-14/fix-build-with-glibc-2.42.patch
  openjdk-15.yaml
  openjdk-15/fix-build-with-glibc-2.42.patch
  openjdk-17.yaml
  openjdk-21.yaml
Labels: bincapz/pass

#63101 Fix OpenJDK FTBFS with glibc 2.42 -- shard #2
  openjdk-16.yaml
  openjdk-16/fix-build-with-glibc-2.42.patch
  openjdk-18.yaml
  openjdk-18/fix-build-with-glibc-2.42.patch
  openjdk-19.yaml
  openjdk-19/fix-build-with-glibc-2.42.patch
  openjdk-20.yaml
  openjdk-20/fix-build-with-glibc-2.42.patch
  openjdk-22.yaml
  openjdk-22/fix-build-with-glibc-2.42.patch
  openjdk-23.yaml
  openjdk-23/fix-build-with-glibc-2.42.patch
  openjdk-24.yaml
  openjdk-24/fix-build-with-glibc-2.42.patch
Labels: bincapz/pass, approved-to-run

#63110 Tetragon package: bpf programs' directory fix
  tetragon.yaml
Labels: bincapz/pass, ai/skip-comment

#63209 openjdk: use build-dependency loop (part 1)
  openjdk-10.yaml
  openjdk-10/HelloWorld.java
  openjdk-10/JDK-8241296.patch
  openjdk-10/JDK-8245051.patch
  openjdk-10/aarch64.patch
  openjdk-10/extend-currency-check-to-100-years.patch
  openjdk-10/fix-bootjdk-check.patch
  openjdk-10/fix-build-with-glibc-2.42.patch
  openjdk-10/gcc10-compilation-fix.patch
  openjdk-10/gcc11.patch
  openjdk-10/make-4.3.patch
  openjdk-11.yaml
  openjdk-9.yaml
  openjdk-9/HelloWorld.java
  openjdk-9/JDK-8187578.patch
  openjdk-9/JDK-8224851.patch
  openjdk-9/JDK-8241296.patch
  openjdk-9/JDK-8245051.patch
  openjdk-9/extend-currency-check-to-100-years.patch
  openjdk-9/fix-build-with-glibc-2.42.patch
  openjdk-9/gcc10-compilation-fix.patch
  openjdk-9/gcc11.patch
  openjdk-9/int-conversion.patch
  openjdk-9/make-4.3.patch
Labels: bincapz/pass

#63241 openjdk: use build-dependency loop (part 2)
  openjdk-12.yaml
  openjdk-12/HelloWorld.java
  openjdk-12/JDK-8241296.patch
  openjdk-12/JDK-8245051.patch
  openjdk-12/JDK-8272472.patch
  openjdk-12/aarch64.patch
  openjdk-12/fix-build-with-glibc-2.42.patch
  openjdk-12/gcc10-compilation-fix.patch
  openjdk-12/make-4.3.patch
  openjdk-13.yaml
  openjdk-13/HelloWorld.java
  openjdk-13/JDK-8245051.patch
  openjdk-13/aarch64.patch
  openjdk-13/fix-build-with-glibc-2.42.patch
  openjdk-14.yaml
  openjdk-14/HelloWorld.java
  openjdk-14/JDK-8245051.patch
  openjdk-14/JDK-8272472.patch
  openjdk-14/aarch64.patch
  openjdk-14/fix-build-with-glibc-2.42.patch
  openjdk-14/gcc10-compilation-fix.patch
  openjdk-15.yaml
  openjdk-15/HelloWorld.java
  openjdk-15/aarch64.patch
  openjdk-15/fix-build-with-glibc-2.42.patch
  openjdk-16.yaml
  openjdk-16/FixNullPtrCast.patch
  openjdk-16/HelloWorld.java
  openjdk-16/fix-build-with-glibc-2.42.patch
  openjdk-17.yaml
Labels: bincapz/pass, approved-to-run

#63242 openjdk: use build-dependency loop (part 3)
  openjdk-18.yaml
  openjdk-18/FixNullPtrCast.patch
  openjdk-18/HelloWorld.java
  openjdk-18/detect-busybox-date-as-gnu-date.patch
  openjdk-18/fix-build-with-glibc-2.42.patch
  openjdk-19.yaml
  openjdk-19/FixNullPtrCast.patch
  openjdk-19/HelloWorld.java
  openjdk-19/JDK-8282306_disable-test.patch
  openjdk-19/fix-build-with-glibc-2.42.patch
  openjdk-20.yaml
  openjdk-20/FixNullPtrCast.patch
  openjdk-20/HelloWorld.java
  openjdk-20/JDK-8282306_disable-test.patch
  openjdk-20/JDK-8299245_disable-tests.patch
  openjdk-20/fix-build-with-glibc-2.42.patch
  openjdk-21.yaml
Labels: bincapz/pass

#63244 openjdk: use build-dependency loop (part 4)
  bazel-5
  bazel-5.yaml
  gcc-6.yaml
  gcc-6/0017-pr93402.patch
  gcc-6/fix-cxxflags-passing.patch
  gcc-6/fix-gcj-arm-thumb.patch
  gcc-6/fix-gcj-stdgnu14-link.patch
  gcc-6/isl-0.22.patch
  java-gcj-compat.yaml
  openjdk-7.yaml
  openjdk-7/autoconf-2.7x.patch
  openjdk-7/fix-xattr-include.patch
  openjdk-7/icedtea-patches/icedtea-hotspot-disable-agent.patch
  openjdk-7/icedtea-patches/icedtea-hotspot-fix-nullcheck.patch
  openjdk-7/icedtea-patches/icedtea-jdk-fix-build.patch
  openjdk-7/icedtea-patches/icedtea-jdk-fix-compile-optional.patch
  openjdk-7/icedtea-patches/icedtea-jdk-fix-gcc10.patch
  openjdk-7/icedtea-patches/icedtea-jdk-fix-ipv6-init.patch
  openjdk-7/icedtea-patches/icedtea-jdk-format-sec.patch
  openjdk-7/icedtea-patches/icedtea-jdk-glibc-2.32.patch
  openjdk-7/icedtea-patches/icedtea-jdk-no-soname.patch
  openjdk-7/icedtea-patches/icedtea-jdk-xattr.patch
  openjdk-8.yaml
Labels: bincapz/pass

#63543 go: use build-loop
  go-1.24.yaml
  go-1.25.yaml
Labels: bincapz/pass

#63611 Add systemd-dev build depends
  squid.yaml
Labels: bincapz/pass

#63651 ingress-nginx-controller-1.13: bump to version 1.13.1
  ingress-nginx-controller-1.13.yaml
Labels: bincapz/pass

#63660 kubernetes-1.33/cve remediation
  kubernetes-1.33.yaml
Labels: bincapz/pass, ai/skip-comment

#63461 refactor(linkerd2): merge 'policy-controller' into the 'controller' subpkg
  linkerd2.yaml
Labels: bincapz/pass

#63708 feat(open-webui): bump dep to remediate GHSA-7hfw-26vp-jp8m
  open-webui.yaml
Labels: bincapz/pass

#61357 keycloak: version stream keycloak
  keycloak-26.3.yaml
  keycloak-26.3/napi-static-assert.c
  keycloak-26.3/pombump-deps.yaml
  keycloak-26.3/pombump-properties.yaml
Labels: bincapz/pass, ai/skip-comment

#63683 add py3 versions to xfsprogs
  xfsprogs.yaml
Labels: bincapz/pass

#63666 Add no docs test batch 34
  perl-types-serialiser.yaml
  perl-www-robotrules.yaml
  perl-yaml-tiny.yaml
Labels: bincapz/pass

#63700 harbor-2.13: unpin swagger
  harbor-2.13.yaml
Labels: bincapz/pass

#63817 apk-tools: future proof CRC algorithms access
  apk-tools.yaml
  apk-tools/0001-Work-without-fips-sha1.patch
Labels: bincapz/pass

#63739 llvm-20: Cleanup collateral changes from enabling MLIR
  llvm-20.yaml
Labels: bincapz/pass, ai/skip-comment

#63818 feat(thingsboard): bump dep to remediate GHSA-r936-gwx5-v52f
  thingsboard.yaml
  thingsboard/pombump-deps.yaml
  thingsboard/proto-pombump-deps.yaml
Labels: bincapz/pass

#63909 feat(langfuse): upgrade pkg and bump dep to remediate GHSA-8gwm-58g9-j8pw and GHSA-7rqq-prvp-x9jh
  langfuse.yaml
Labels: bincapz/pass

#63998 feat(apache-nifi): bump dep to remediate GHSA-mmxm-8w33-wc4h
  apache-nifi.yaml
  apache-nifi/pombump-nifi-email-nar.yaml
  apache-nifi/pombump-properties.yaml
Labels: bincapz/pass

#64030 ed: bump to version 1.22.2
  ed.yaml
Labels: bincapz/pass

#64040 Add systemd-ukify
  py3-pefile.yaml
  systemd.yaml
Labels: bincapz/pass

#64057 kube-arangodb/cve remediation
  kube-arangodb.yaml
Labels: bincapz/pass

#64147 feat(solr): bump dep to remediate GHSA-mmxm-8w33-wc4h
  solr.yaml
Labels: bincapz/pass

#63659 glibc 2.42 upgrade
  glibc.yaml
Labels: bincapz/pass

#64175 feat(argo-events): bump dep to remediate GHSA-2464-8j7c-4cjm
  argo-events.yaml
Labels: bincapz/pass

#64204 More golang FTBFS fixes
  dapr-1.15.yaml
  ferretdb.yaml
  go-licenses.yaml
  ipfs-cluster.yaml
  swagger.yaml
  verticadb-operator.yaml
Labels: bincapz/pass

#64219 Fix FTBFSes due to missing `AM_ICONV`
  dosfstools.yaml
  fluxbox.yaml
  freetds.yaml
  fuse2.yaml
Labels: bincapz/pass

#64238 feat(kyverno-notation-aws): bump dep to remediate GHSA-2464-8j7c-4cjm
  kyverno-notation-aws.yaml
Labels: bincapz/pass

#64234 feat(boring-registry): bump dep to remediate GHSA-2464-8j7c-4cjm
  boring-registry.yaml
Labels: bincapz/pass

#64289 rancher-charts-2.12: add new version stream manually
  rancher-charts-2.12.yaml
Labels: bincapz/pass

#63875 busybox/cve remediation
  busybox.yaml
  busybox/CVE-2024-58251-2.patch
  busybox/CVE-2024-58251.patch
  busybox/CVE-2025-46394.patch
Labels: bincapz/pass

#64344 chore: add symlink for docker dind
  docker.yaml
Labels: bincapz/pass

#63855 libspatialindex: No-change rebuild for 2.28 toolchain
  libspatialindex.yaml
Labels: bincapz/pass, approved-to-run

#64407 fix: add symlink to cilium image to match upstream
  cilium-1.18.yaml
Labels: bincapz/pass

#64449 harbor-registry: fix ldflags, enable auto-updates, improve tests
  harbor-registry.yaml
Labels: bincapz/pass

#64502 Make cpio and gnutar co-installable.
  cpio.yaml
  gnutar.yaml
Labels: bincapz/pass

#64510 Unpin `gcc-14-default` from packages that build with GCC 15 -- part 2
  libgdiplus.yaml
  libical.yaml
  libtirpc.yaml
  malcontent.yaml
  mariadb-12.0.yaml
  mariadb-connector-c.yaml
  mysql-connector-cpp.yaml
  nginx-mainline.yaml
  ninja-build.yaml
  ollama.yaml
  pstack.yaml
  py3-sentencepiece.yaml
  py3-tensorflow-data-validation.yaml
  python-3.10.yaml
Labels: bincapz/pass, ai/skip-comment

#64499 add metrics-exporter binary
  clickhouse-operator.yaml
Labels: bincapz/pass

#64529 zookeeper-3.9: add missing runtime deps
  zookeeper-3.9.yaml
Labels: bincapz/pass

#64549 fix(python-3.11): remediate CVE-2025-8194
  python-3.11.yaml
Labels: bincapz/pass

#64553 Bump kubernetes to remediate CVE-2025-5187|GHSA-4x4m-3c2p-qppc
  yunikorn-k8shim.yaml
Labels: bincapz/pass, approved-to-run

#64581 feat(open-webui): bump dep to remediate GHSA-847f-9342-265h
  open-webui.yaml
Labels: bincapz/pass

#63245 chore(crossplane-provider-aws): Build individual resource packages instead of monolith provider
  crossplane-provider-aws.yaml
Labels: ai/skip-comment

#64667 sudo: encode upstream patch level into our versioning
  sudo.yaml
Labels: bincapz/pass
