Repository wolfi-dev/os, pull requests merged in 2025-02, with the labels that each got.

#40317 add kn package
  knative-client.yaml
Labels: bincapz/pass

#41070 systemd: split off userdb
  systemd.yaml
Labels: bincapz/pass

#41117 add json-server package
  json-server.yaml
Labels: bincapz/pass

#41121 use go/build pipeline for building nats-server
  nats-server.yaml
Labels: bincapz/pass

#41001 Add the ldd-check test pipeline to some more packages
  collectd.yaml
  confluent-docker-utils.yaml
  google-cloud-sdk.yaml
  libmamba.yaml
  logstash-8.yaml
  zed.yaml
Labels: bincapz/pass

#41162 add json-mock package
  json-mock.yaml
Labels: bincapz/pass

#41200 Compile ruby-puma with ssl support
  ruby3.4-puma.yaml
Labels: bincapz/pass

#41047 openssf-compiler-options: Allow -fno-omit-frame-pointer override
  openssf-compiler-options.yaml
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/11/openssf.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/12/openssf.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/13/openssf.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/14/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/11/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/12/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/13/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/14/openssf.spec
Labels: bincapz/pass

#41232 rekor bump to fix CVE-2024-45341 and CVE-2024-45336
  rekor.yaml
Labels: bincapz/pass

#40551 custom-error-pages package build
  ingress-nginx-controller-1.12.yaml
Labels: bincapz/pass, ai/skip-comment

#41193 python-3.13: add CVE-2025-0938 fixes
  python-3.13.yaml
Labels: bincapz/pass

#41228 Adds aws-s3-controller v1.0.21
  aws-s3-controller.yaml
Labels: bincapz/pass

#41225 apache-tika: unbump jetty version
  apache-tika-3.0.yaml
  apache-tika-3.0/patches.yaml
Labels: bincapz/pass, approved-to-run

#41207 python-3.12: add CVE-2025-0938 fix
  python-3.12.yaml
Labels: bincapz/pass, approved-to-run

#41322 sudo-rs: Include /etc/sudoers.d by default
  sudo-rs.yaml
Labels: bincapz/pass

#41328 py3-json*: misc deps
  py3-jsonpatch.yaml
  py3-jsonpointer.yaml
Labels: bincapz/pass

#41347 add compat package to nats-server package
  nats-server.yaml
Labels: bincapz/pass

#41348 feat: Validate vars correctness in GitLab CNG package
  gitlab-cng-17.8.yaml
Labels: bincapz/pass

#41327 Add tailscale-compat subpackage
  tailscale.yaml
Labels: bincapz/pass

#41429 Fix keyutils-dev
  keyutils.yaml
Labels: bincapz/pass, ai/skip-comment

#41493 net-tools: usrmerge
  net-tools.yaml
Labels: bincapz/pass

#41492 secrets-store-csi-driver-provider-azure: go/build pipeline, add compat and expand tests
  secrets-store-csi-driver-provider-azure.yaml
Labels: bincapz/pass

#41511 fix(collectd.yaml): Revert adding runtime dependencies to satisfy ldd-check
  collectd.yaml
Labels: bincapz/pass

#41506 tig: install manpages into -doc package, add test/docs test
  tig.yaml
Labels: bincapz/pass

#41539 fix(py3-cassandra-medusa): add missing poetry binary
  py3-cassandra-medusa.yaml
Labels: bincapz/pass

#41548 sqlpad: add py3-setuptools to build environment to fix FTBFS
  sqlpad.yaml
Labels: bincapz/pass

#41555 python:3.12: remove unnecessary cherry picks as its part of the release
  python-3.12.yaml
Labels: bincapz/pass

#41563 shaderc: fix update config, bump to latest version
  shaderc.yaml
Labels: bincapz/pass

#41553 opensearch-2: build with older version of gradle to fix FTBFS
  opensearch-2.yaml
Labels: bincapz/pass

#41547 spdx-tools-java: add missing build deps, fixing FTBFS
  spdx-tools-java.yaml
Labels: bincapz/pass

#41543 percona-server-9.0: fetch boost from archive.boost.io, fixing FTBFS
  percona-server-9.0.yaml
Labels: bincapz/pass

#41544 py3-cairo: add python3 to build environment, fixing FTBFS
  py3-cairo.yaml
Labels: bincapz/pass

#41542 kong: use Bazel 7 for builds, fixing FTBFS
  kong.yaml
Labels: bincapz/pass

#41540 graphene: add python3 to build dependencies, fixing FTBFS
  graphene.yaml
Labels: bincapz/pass

#41586 chore(tevent): bump epoch to rebuild
  tevent.yaml
Labels: bincapz/pass

#41587 chore(samba): bump epoch and add tests for samba-client
  samba.yaml
Labels: bincapz/pass, ai/skip-comment

#41541 opencost package build
  opencost.yaml
Labels: bincapz/pass

#41427 add package for bitnami/jmx-exporter
  jmx-exporter-bitnami.yaml
Labels: bincapz/pass, ai/skip-comment

#41615 Refactor superset package to include entrypoint scripts
  superset.yaml
Labels: bincapz/blocking

#41572 Add a new package for fetching sources from Chainguard sboms
  chainguard-source.yaml
Labels: bincapz/pass, ai/skip-comment

#41631 minio: update to version 0.20250203.210304
  minio.yaml
Labels: bincapz/pass

#41925 speex: fix test/doc for -doc subpkg
  speex.yaml
Labels: bincapz/pass, approved-to-run

#41922 tiff: fix test/doc in subpkg -doc
  tiff.yaml
Labels: bincapz/pass, approved-to-run

#42154 add cpio package
  cpio.yaml
Labels: bincapz/pass

#42201 build opentelemetry-cpp with GRPC on
  opentelemetry-cpp.yaml
Labels: bincapz/pass

#41625 Allow test/ldd-check to resolve shared objects in the same python module, run newly passing tests
  checkov.yaml
  kserve.yaml
  kubeflow-katib.yaml
  mlflow.yaml
  pipelines/test/ldd-check.yaml
Labels: approved-to-run

#42185 ingress-nginx-controller: build from specific commit of opentelemetry-cpp-contrib
  ingress-nginx-controller-1.12.yaml
Labels: bincapz/pass, ai/skip-comment

#42244 Adds compat package for rabbitmq-default-user-credential-updater
  rabbitmq-default-user-credential-updater.yaml
Labels: bincapz/pass

#42271 Out of date base allows missing bump, rebump
  containerd-2.yaml
Labels: bincapz/pass

#42278 Unwedge debezium
  debezium-3.0.yaml
  debezium-connect-entrypoint-3.0.yaml
  debezium-connector-db2-3.0.yaml
  debezium-connector-ibmi-3.0.yaml
  debezium-connector-informix-3.0.yaml
  debezium-connector-spanner-3.0.yaml
  debezium-connector-vitess-3.0.yaml
Labels: bincapz/pass

#42291 java-cacerts: update to 20241121 bundle
  java-cacerts.yaml
Labels: bincapz/pass

#42360 Add missing make dependency
  Makefile
Labels: papercut

#42371 mosquitto: Fix tests to exit 1 when failing
  mosquitto.yaml
Labels: papercut

#42361 add tests for yamllint
  yamllint.yaml
Labels: papercut

#42377 Add tests to wait-for-it
  wait-for-it.yaml
Labels: papercut

#42373 ruby3.[23]-timers: add tests
  ruby3.2-timers.yaml
  ruby3.3-timers.yaml
Labels: bincapz/pass

#42405 wolfictl bump for apk fetch BAD archive
  libmd.yaml
Labels: bincapz/pass

#42416 wolfictl bump for apk fetch BAD archive
  neuvector-db.yaml
Labels: bincapz/pass, ai/skip-comment

#42418 wolfictl bump for apk fetch BAD archive
  npm-lodash.yaml
Labels: bincapz/pass

#42410 wolfictl bump for apk fetch BAD archive
  libpciaccess.yaml
Labels: bincapz/pass

#42408 wolfictl bump for apk fetch BAD archive
  libnetfilter_cthelper.yaml
Labels: bincapz/pass

#42406 wolfictl bump for apk fetch BAD archive
  libmnl.yaml
Labels: bincapz/pass

#42419 wolfictl bump for apk fetch BAD archive
  pigz.yaml
Labels: bincapz/pass

#42412 wolfictl bump for apk fetch BAD archive
  libretls.yaml
Labels: bincapz/pass

#42409 wolfictl bump for apk fetch BAD archive
  libnetfilter_cttimeout.yaml
Labels: bincapz/pass

#42413 wolfictl bump for apk fetch BAD archive
  libtree.yaml
Labels: bincapz/pass

#42428 wolfictl bump for apk fetch BAD archive
  zstd.yaml
Labels: bincapz/pass, papercut

#42407 wolfictl bump for apk fetch BAD archive
  libnet.yaml
Labels: bincapz/pass

#42425 wolfictl bump for apk fetch BAD archive
  wolfi-base.yaml
Labels: bincapz/pass, papercut

#42423 wolfictl bump for apk fetch BAD archive
  tinyxml2.yaml
Labels: bincapz/pass, papercut

#42422 wolfictl bump for apk fetch BAD archive
  ssh-import-id.yaml
Labels: bincapz/pass, papercut

#42421 wolfictl bump for apk fetch BAD archive
  run-one.yaml
Labels: bincapz/pass, papercut

#42431 dhcping: split manpages into -docs package, add tests
  dhcping.yaml
Labels: bincapz/pass, approved-to-run

#42404 wolfictl bump for apk fetch BAD archive
  libedit.yaml
Labels: bincapz/pass, papercut

#42403 wolfictl bump for apk fetch BAD archive
  libdbi.yaml
Labels: bincapz/pass, papercut

#42402 wolfictl bump for apk fetch BAD archive
  krb5-conf.yaml
Labels: bincapz/pass, papercut

#42401 wolfictl bump for apk fetch BAD archive
  jansson.yaml
Labels: bincapz/pass, papercut

#42400 wolfictl bump for apk fetch BAD archive
  hiredis.yaml
Labels: bincapz/pass, papercut

#41945 trurl: fix doc subpkg
  curl.yaml
  trurl.yaml
Labels: bincapz/pass, approved-to-run

#42399 wolfictl bump for apk fetch BAD archive
  fontsproto.yaml
Labels: bincapz/pass, papercut

#42398 wolfictl bump for apk fetch BAD archive
  font-ubuntu.yaml
Labels: bincapz/pass, papercut

#42393 wolfictl bump for apk fetch BAD archive
  R-units.yaml
Labels: bincapz/pass, papercut

#42397 wolfictl bump for apk fetch BAD archive
  dumb-init.yaml
Labels: bincapz/pass, papercut

#42388 wolfictl bump for apk fetch BAD archive
  R-DBI.yaml
Labels: bincapz/pass, papercut

#42389 wolfictl bump for apk fetch BAD archive
  R-proxy.yaml
Labels: bincapz/pass, papercut

#42391 wolfictl bump for apk fetch BAD archive
  R-showtextdb.yaml
Labels: bincapz/pass, papercut

#42392 wolfictl bump for apk fetch BAD archive
  R-sysfonts.yaml
Labels: bincapz/pass, papercut

#42394 wolfictl bump for apk fetch BAD archive
  asciidoctor.yaml
Labels: bincapz/pass, papercut

#42395 wolfictl bump for apk fetch BAD archive
  configurable-http-proxy.yaml
Labels: bincapz/pass, papercut

#42396 wolfictl bump for apk fetch BAD archive
  container-entrypoint.yaml
Labels: bincapz/pass, papercut

#42334 Fix doc subpkg smartypants + openblas
  openblas.yaml
  smartypants.yaml
Labels: bincapz/pass, approved-to-run

#42429 Add tests to wolfi-base
  wolfi-base.yaml
Labels: papercut

#42385 keycloak: skip ProtoStream Schema Compat check (fixing an FTBFS)
  keycloak.yaml
Labels: bincapz/pass, approved-to-run, papercut

#42446 bump the cue epoch for cve remediation
  cue.yaml
Labels: bincapz/pass

#42414 wolfictl bump for apk fetch BAD archive
  libxcomposite.yaml
Labels: bincapz/pass, papercut

#42459 new package: go-tools, including goimports
  crossplane-provider-keycloak.yaml
  go-tools.yaml
Labels: bincapz/pass

#42440 go-1.24: add new go major release
  go-1.24.yaml
  go-1.24/change-default-telemetry-from-local-to-off.patch
  go-1.24/cmd-go-always-emit-ldflags-version-information.patch
  hello-world-golang.yaml
  hey.yaml
Labels: bincapz/pass

#42526 py3-supported-gdal: Add missing 3.13 dep
  gdal.yaml
Labels: bincapz/pass

#41381 fix(python): Support binding to ports less than 1024
  python-3.12.yaml
  python-3.13.yaml
Labels: bincapz/pass

#42235 add rpm2cpio package
  rpm2cpio.yaml
Labels: bincapz/pass

#42197 add trufflehog package
  trufflehog.yaml
Labels: bincapz/pass

#42122 add xeol package
  xeol.yaml
Labels: bincapz/pass

#42569 spark-3.5-scala-2.13 invalid dependency bump removal and CVE Fix
  spark-3.5-scala-2.13.yaml
  spark-3.5-scala-2.13/GHSA-4g8c-wm8x-jfhw-fix.patch
  spark-3.5-scala-2.13/pombump-deps.yaml
  spark-3.5-scala-2.13/pombump-properties.yaml
Labels: bincapz/pass, ai/skip-comment

#42628 test: fix file capabilities tests
  coredns.yaml
  spire-server.yaml
Labels: bincapz/pass

#39152 Implement Package Metadata ELF notes by including melange generated gcc specs for C, C++, Rust, Go.
  gops.yaml
  pax-utils.yaml
  rust-audit-info.yaml
Labels: blocked, bincapz/pass, approved-to-run

#42664 node-problem-detector: update provides and use var-transfroms
  node-problem-detector-0.8.yaml
Labels: bincapz/pass

#42657 add curl as runtime dependency to cassandra
  cassandra-5.0.yaml
Labels: bincapz/pass

#42665 add compat package to kubernetes-dashboard-api
  kubernetes-dashboard-api.yaml
Labels: bincapz/pass

#42677 compat packages for kubernetes-dashboard-{auth,metrics-scraper}
  kubernetes-dashboard-auth.yaml
  kubernetes-dashboard-metrics-scraper.yaml
Labels: bincapz/pass

#42698 rebuild kubernetes-dashboard-web with static assets embedded
  kubernetes-dashboard-web.yaml
Labels: bincapz/pass

#42478 opencost-ui package build
  opencost-ui.yaml
Labels: bincapz/pass, ai/skip-comment

#42752 fluent-plugin-label-router: relax ruby3.2-fluentd version constraint
  fluent-plugin-label-router.yaml
  fluent-plugin-label-router/relax-fluent-constraint.patch
Labels: bincapz/pass

#42758 fix mime.types issue
  opencost-ui.yaml
Labels: bincapz/pass

#42802 add py3-findpython
  py3-findpython.yaml
Labels: bincapz/pass

#42813 add py3-pbs_installer
  py3-pbs_installer.yaml
Labels: bincapz/pass

#41031 added wildfly.yaml
  wildfly.yaml
Labels: bincapz/pass, approved-to-run

#41000 Add oath-toolkit package definition and build pipeline
  oath-toolkit.yaml
Labels: bincapz/pass, approved-to-run

#41255 feat(new-package): add op-geth package
  op-geth.yaml
Labels: bincapz/blocking, malcontent/reviewed, approved-to-run, ai/skip-comment

#42978 add missing scripts in the entrypoint folder
  docker-nginx.yaml
Labels: bincapz/pass

#42988 add docker-nginx to opencost-ui's runtime deps
  opencost-ui.yaml
Labels: bincapz/pass

#42873 feat(jupyter-base-notebook): add required packages
  jupyter-base-notebook.yaml
Labels: bincapz/pass, malcontent/reviewed

#42995 ruby*-rack: convert to git update backend, bump version
  ruby3.2-rack.yaml
  ruby3.3-rack.yaml
  ruby3.4-rack.yaml
Labels: bincapz/pass, ai/skip-comment

#42997 ruby*-rails-8.0: use APK to provide net-imap
  ruby3.2-rails-8.0.yaml
  ruby3.3-rails-8.0.yaml
  ruby3.4-rails-8.0.yaml
Labels: bincapz/pass

#42996 zookeeper-3.9/GHSA-4g8c-wm8x-jfhw netty version update
  zookeeper-3.9.yaml
Labels: bincapz/pass

#42250 py3-* misc deps
  py3-netifaces.yaml
  py3-pyserial.yaml
Labels: bincapz/pass

#43051 fix(dumb-init): Support binding to ports less than 1024
  dumb-init.yaml
Labels: bincapz/pass

#41290 refactor: Consolidate git-checkout pipelines and enforce version consistency with upstream
  gitlab-runner-17.8.yaml
Labels: bincapz/pass

#41510 Add hydra to pkgs
  hydra.yaml
Labels: bincapz/pass

#43072 Fix: add dumb-init-privileged-netbindservice as runtime dep
  ingress-nginx-controller-1.12.yaml
Labels: bincapz/pass, ai/skip-comment

#39643 Add Spark 3.5 enhancements including dependency updates and script fixes
  spark-3.5-scala-2.12/mvn.patch
  spark-3.5-scala-2.12/pombump-deps.yaml
  spark-3.5-scala-2.13.yaml
  spark-3.5.yaml
  spark-3.5/GHSA-4g8c-wm8x-jfhw-fix.patch
  spark-3.5/GHSA-8qv5-68g4-248j-fix.patch
  spark-3.5/dataframe-import.patch
  spark-3.5/internal-access.patch
  spark-3.5/load-spark-env.sh.diff
  spark-3.5/make-2.13-distribution.patch
  spark-3.5/make-distribution.patch
  spark-3.5/mvn.patch
  spark-3.5/pombump-deps.yaml
  spark-3.5/pombump-properties-2.13.yaml
  spark-3.5/pombump-properties.yaml
  spark-3.5/scala-test
  spark-3.5/spark-daemon.sh.diff
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#43077 remove and withdraw wildfly
  wildfly.yaml
  withdrawn-packages.txt
Labels: approved-to-run

#43103 add package wildfly
  wildfly.yaml
Labels: approved-to-run

#43104 docker-selenium/GHSA-4g8c-wm8x-jfhw fix
  docker-selenium.yaml
Labels: bincapz/pass

#43115 remove and withdraw wildfly -r9 versions
  withdrawn-packages.txt
Labels: approved-to-run

#43091 Fix: Remove /nginx/owasp-modsecurity-crs/tests to replicate upstream
  ingress-nginx-controller-1.12.yaml
Labels: bincapz/pass

#38921 add font-noto package
  font-noto.yaml
  font-noto/45-noto-math.conf
  font-noto/45-noto.xml.erb
  font-noto/58-noto-math.conf
  font-noto/58-noto.xml.erb
  font-noto/noto-meta
  font-noto/noto-meta.json
Labels: bincapz/pass, ai/skip-comment

#43118 Fix(mlflow): pip install .[auth] for missing dependencies
  mlflow.yaml
Labels: bincapz/pass

#43138 Add py3-roman-numerals-py, a missing dep of py3-sphinx
  py3-roman-numerals-py.yaml
  py3-sphinx.yaml
Labels: bincapz/pass

#43153 add font-noto-math, font-noto-common and font-noto-symbols to font-noto's runtime deps
  font-noto.yaml
Labels: bincapz/pass

#43163 Complete 3.13 transition
  py3-dbus-python.yaml
  py3-frozendict.yaml
  py3-notify2.yaml
Labels: bincapz/pass

#43176 gcp-compute-persistent-disk-csi-driver-1.15/CVE-2025-22866 fix
  gcp-compute-persistent-disk-csi-driver-1.15.yaml
Labels: bincapz/pass

#43203 postgresql-*: bump to latest versions
  postgresql-16.yaml
  postgresql-17.yaml
Labels: bincapz/pass

#43188 fix(calico-3.29.yaml): Disable the calico-apiserver 3.29.2 when Validating Admission Policy checks until upstream tigrea operator adds the required rules
  calico-3.29.yaml
  calico-3.29/calico-apiserver-disable-validating-admission-policy.patch
Labels: bincapz/pass

#43156 feat: Add Prometheus C++ libraries
  prometheus-cpp.yaml
Labels: bincapz/pass, ai/skip-comment

#43222 Remove the Swedish manpage from groff
  groff.yaml
Labels: bincapz/pass

#43256 build(wolfictl): bump to v0.29.3
  wolfictl.yaml
Labels: bincapz/pass

#43274 feat: Add selinux packages to wolfi
  libselinux.yaml
  libsemanage.yaml
  libsepol.yaml
Labels: bincapz/pass

#43278 feat: compile linux-pam with selinux support
  linux-pam.yaml
Labels: bincapz/pass, ai/skip-comment

#43277 kafka-3.9/GHSA-4g8c-wm8x-jfhw-fix
  kafka-3.9.yaml
  kafka-3.9/GHSA-4g8c-wm8x-jfhw-fix.patch
Labels: bincapz/pass

#43245 akhq/cve-remediation GHSA-4g8c-wm8x-jfhw
  akhq.yaml
  akhq/cves-20250220.patch
Labels: bincapz/pass
