Repository wolfi-dev/os, pull requests merged in 2025-09, with the labels that each got.

#64835 Newer pcre version for njs
  njs.yaml
Labels: bincapz/pass

#64836 opensearch-dashboards-3: fix CVE-2025-9287 and CVE-2025-9288
  opensearch-dashboards-3.yaml
Labels: bincapz/pass

#64796 Revert "wget: Unpin gcc-14-default"
  wget.yaml
Labels: bincapz/pass

#64893 fix: revert kubernetes-1.33: make kubelet-1.33 subpackage provide kubelet
  kubernetes-1.33.yaml
Labels: bincapz/pass

#64955 introduce additional virtualpackage tests
  kuma-2.11.yaml
Labels: bincapz/pass

#64946 introduce additional virtualpackage tests
  istio-1.27.yaml
Labels: bincapz/pass

#64945 introduce additional virtualpackage tests
  istio-1.26.yaml
Labels: bincapz/pass

#64944 introduce additional virtualpackage tests
  imagemagick-7.yaml
Labels: bincapz/pass

#64943 introduce additional virtualpackage tests
  harbor-2.13.yaml
Labels: bincapz/pass

#64942 introduce additional virtualpackage tests
  haproxy-3.2.yaml
Labels: bincapz/pass

#64940 introduce additional virtualpackage tests
  grafana-12.1.yaml
Labels: bincapz/pass

#64939 introduce additional virtualpackage tests
  grafana-12.0.yaml
Labels: bincapz/pass

#64935 introduce additional virtualpackage tests
  gitlab-runner-18.2.yaml
Labels: bincapz/pass

#64934 introduce additional virtualpackage tests
  gitaly-18.3.yaml
Labels: bincapz/pass

#64930 introduce additional virtualpackage tests
  fluent-bit-4.0.yaml
Labels: bincapz/pass

#64920 introduce additional virtualpackage tests
  dotnet-9.yaml
Labels: bincapz/pass

#64916 introduce additional virtualpackage tests
  docker-selenium.yaml
Labels: bincapz/pass

#64915 introduce additional virtualpackage tests
  debezium-3.0.yaml
Labels: bincapz/pass

#64919 introduce additional virtualpackage tests
  dotnet-8.yaml
Labels: bincapz/pass

#64914 introduce additional virtualpackage tests
  datawire-envoy-1.31.yaml
Labels: bincapz/pass

#64908 introduce additional virtualpackage tests
  cloud-sql-proxy-2.16.yaml
Labels: bincapz/pass

#64905 introduce additional virtualpackage tests
  cilium-1.18.yaml
Labels: bincapz/pass

#64904 introduce additional virtualpackage tests
  cert-manager-1.18.yaml
Labels: bincapz/pass

#64897 introduce additional virtualpackage tests
  argo-cd-3.0.yaml
Labels: bincapz/pass

#64899 introduce additional virtualpackage tests
  azuredisk-csi-1.33.yaml
Labels: bincapz/pass

#64927 introduce additional virtualpackage tests
  ffmpeg-7.1.yaml
Labels: bincapz/pass

#64925 introduce additional virtualpackage tests
  erlang-28.yaml
Labels: bincapz/pass

#64922 introduce additional virtualpackage tests
  erlang-25.yaml
Labels: bincapz/pass

#64902 introduce additional virtualpackage tests
  calico-3.30.yaml
Labels: bincapz/pass

#64929 introduce additional virtualpackage tests
  flink-2.1.yaml
Labels: bincapz/pass

#64990 py3-ml-dtypes: adjust dependency on numpy
  py3-ml-dtypes.yaml
Labels: bincapz/pass

#65031 chore: velero-plugin-for-microsoft-azure runtime deps
  velero-plugin-for-microsoft-azure.yaml
Labels: bincapz/pass

#65032 opensearch-dashboards-3/GHSA-95m3-7q98-8xr5 fix
  opensearch-dashboards-3.yaml
  opensearch-dashboards-3/CVE-2025-9287-fix.patch
Labels: bincapz/pass

#65037 langfuse/GHSA-g5qg-72qw-gw5v fix
  langfuse.yaml
Labels: bincapz/pass

#65045 busybox/cve remediation
  busybox.yaml
  busybox/CVE-2025-46394.patch
Labels: bincapz/pass

#65080 cassandra-reaper: cherry-pick JWT secret length extension feature
  cassandra-reaper.yaml
  cassandra-reaper/0001-Ensure-JWT-secret-is-at-least-32-bytes.patch
Labels: bincapz/pass, ai/skip-comment

#65093 introduce additional virtualpackage tests
  openjdk-24.yaml
Labels: bincapz/pass

#65098 introduce additional virtualpackage tests
  php-8.1.yaml
Labels: bincapz/pass

#65100 introduce additional virtualpackage tests
  php-8.3.yaml
Labels: bincapz/pass

#65111 introduce additional virtualpackage tests
  ruby3.2-openid_connect-1.1.8.yaml
Labels: bincapz/pass

#65109 introduce additional virtualpackage tests
  redpanda-25.2.yaml
Labels: bincapz/pass

#65108 introduce additional virtualpackage tests
  python-3.13.yaml
Labels: bincapz/pass

#65096 introduce additional virtualpackage tests
  pax-utils-bootstrap.yaml
Labels: bincapz/pass

#65076 introduce additional virtualpackage tests
  mariadb-12.0.yaml
Labels: bincapz/pass

#65075 introduce additional virtualpackage tests
  management-api-for-apache-cassandra-5.0.yaml
Labels: bincapz/pass

#65078 introduce additional virtualpackage tests
  msgpack-cxx.yaml
Labels: bincapz/pass

#65077 introduce additional virtualpackage tests
  maven-stage0.yaml
Labels: bincapz/pass

#65081 introduce additional virtualpackage tests
  mysql-9.4.yaml
Labels: bincapz/pass

#65085 introduce additional virtualpackage tests
  node-problem-detector-0.8.yaml
Labels: bincapz/pass

#65089 introduce additional virtualpackage tests
  openjdk-17.yaml
Labels: bincapz/pass

#65084 introduce additional virtualpackage tests
  nginx-stable.yaml
Labels: bincapz/pass

#65086 introduce additional virtualpackage tests
  openbao.yaml
Labels: bincapz/pass

#65090 introduce additional virtualpackage tests
  openjdk-21.yaml
Labels: bincapz/pass

#65115 introduce additional virtualpackage tests
  ztunnel-1.26.yaml
Labels: bincapz/pass

#65088 introduce additional virtualpackage tests
  openjdk-11.yaml
Labels: bincapz/pass

#65102 introduce additional virtualpackage tests
  postgresql-16.yaml
Labels: bincapz/pass

#64921 introduce additional virtualpackage tests
  envoy-1.34.yaml
Labels: bincapz/pass

#65229 fix(rancher-2.12): Bump jwt from v3 to v4 to remediate GHSA-mh63-6h87-95cp
  rancher-2.12.yaml
Labels: bincapz/pass

#65281 lint.sh - do stuff faster with multiple processes
  lint.sh
Labels: approved-to-run

#65338 spark-4.0/hadoop-3.4.2 upgrade, fixes multiple CVEs
  spark-4.0.yaml
  spark-4.0/hadoop.patch
  spark-4.0/pombump-deps.yaml
  spark-4.0/pombump-properties.yaml
Labels: bincapz/pass

#65347 istio-1.26/istio-1.27: fix Go module versioning
  istio-1.26.yaml
  istio-1.27.yaml
Labels: bincapz/pass

#65351 orthanc: rebuild with newer boost version
  orthanc.yaml
Labels: bincapz/pass

#65380 py3-pyyaml: re-instate py3-yaml provides
  py3-pyyaml.yaml
Labels: bincapz/pass

#65405 Expand test coverage for external-secrets package. Remove older package version
  external-secrets-operator-0.18.yaml
  external-secrets-operator-0.19.yaml
  external-secrets-operator-0.19/clustersecretstore.yaml
  external-secrets-operator-0.19/externalsecret.yaml
Labels: bincapz/pass

#65418 Fix GHSA-3p8m-j85q-pgmj netty vulnerability - Cassandra family in os
  cassandra-5.0.yaml
  cassandra-5.0/pombump-deps.yaml
  cassandra-reaper.yaml
  cassandra-reaper/src/server/pombump-deps.yaml
  management-api-for-apache-cassandra-5.0.yaml
  management-api-for-apache-cassandra-5.0/2025-08-15-consolidated-cve-patches.patch
Labels: bincapz/pass, ai/skip-comment

#65421 apache-activemq-artemis/GHSA-3p8m-j85q-pgmj netty vulnerability fix
  apache-activemq-artemis.yaml
  apache-activemq-artemis/pombump-deps.yaml
  apache-activemq-artemis/pombump-properties.yaml
Labels: bincapz/pass

#65551 Enable auto-update checks for a number of packages
  inotify-tools.yaml
  jack.yaml
  jvmkill.yaml
Labels: bincapz/pass

#65690 Fix GHSA-3p8m-j85q-pgmj netty vulnerability - zipkin, solr
  solr.yaml
  zipkin.yaml
  zipkin/pombump-deps.yaml
  zipkin/pombump-properties.yaml
Labels: bincapz/blocking, malcontent/reviewed

#65754 erlang-26: improve backwards compatibility
  erlang-26.yaml
Labels: bincapz/pass

#65767 Add a temporary-package temporary test package
  temporary-package.yaml
Labels: bincapz/pass

#66083 grafana-image-renderer: remediate cve
  grafana-image-renderer.yaml
Labels: bincapz/pass

#66166 langfuse: remediate CVE
  langfuse.yaml
Labels: bincapz/pass

#66172 feat(kubeflow-centraldashboard): bump dep to remediate GHSA-4hjh-wcwx-xvwj
  kubeflow-centraldashboard.yaml
Labels: bincapz/pass

#66183 fix: remediate CVE-2025-58754
  prism.yaml
  prism/CVE-2025-1302.patch
Labels: bincapz/pass

#66182 feat(kubeflow-pipelines): bump dep to remediate GHSA-4hjh-wcwx-xvwj
  kubeflow-pipelines.yaml
  kubeflow-pipelines/GHSA-4hjh-wcwx-xvwj.patch
Labels: bincapz/pass, ai/skip-comment

#66225 fix(restored-packages.txt/withdrawn-packages.txt): restore py3-numpy-1.26.5-r0.apk to unblock elastic-builds
  restored-packages.txt
Labels: tbr

#66189 systemd - Fix paths in package systemd-boot-installed
  systemd.yaml
Labels: bincapz/pass

#66320 [shard-23] No-change rebuild old packages
  xcb-proto.yaml
  xkbcomp.yaml
  zip.yaml
Labels: bincapz/pass, no-change-rebuild-2025-09

#66309 [shard-12] No-change rebuild old packages
  ruby3.2-fiber-annotation.yaml
  ruby3.2-fiber-local.yaml
  ruby3.2-filesize.yaml
  ruby3.2-fluent-config-regexp-type.yaml
  ruby3.2-gems.yaml
  ruby3.2-hashie.yaml
  ruby3.2-http-accept.yaml
  ruby3.2-http-cookie.yaml
  ruby3.2-http-form_data.yaml
  ruby3.2-http_parser.rb.yaml
Labels: bincapz/pass, no-change-rebuild-2025-09

#66297 [shard-0] No-change rebuild old packages
  R-e1071.yaml
  R-wk.yaml
  acme.sh.yaml
  bash-completion.yaml
  bubblewrap.yaml
  build-base.yaml
  dnssec-root.yaml
  ell.yaml
  fftw.yaml
  flac.yaml
Labels: bincapz/pass, no-change-rebuild-2025-09

#66306 [shard-9] No-change rebuild old packages
  py3-html5lib.yaml
  py3-pyjwt.yaml
  py3-python-pypi-mirror.yaml
  py3-scikit-build.yaml
  py3-threadloop.yaml
  py3-webencodings.yaml
  qpress.yaml
  rabbitmq-c.yaml
  ragel.yaml
  resolv_wrapper.yaml
Labels: bincapz/pass, no-change-rebuild-2025-09

#66304 [shard-7] No-change rebuild old packages
  php-8.2-memcached.yaml
  php-8.2-msgpack.yaml
  php-8.2-pecl-pdosqlsrv.yaml
  php-8.2-pecl-sqlsrv.yaml
  php-8.2-ssh2.yaml
  php-8.3-amqp.yaml
  php-8.3-decimal.yaml
  php-8.3-igbinary.yaml
  php-8.3-memcached.yaml
  php-8.3-msgpack.yaml
Labels: bincapz/pass, no-change-rebuild-2025-09

#66319 [shard-22] No-change rebuild old packages
  spirv-headers.yaml
  sshpass.yaml
  sysfsutils.yaml
  tcptraceroute.yaml
  ts-patch.yaml
  uglifyjs.yaml
  util-macros.yaml
  w3m.yaml
  wl-clipboard.yaml
  xbitmaps.yaml
Labels: bincapz/pass, ai/skip-comment, no-change-rebuild-2025-09

#66317 [shard-20] No-change rebuild old packages
  ruby3.4-fiber-annotation.yaml
  ruby3.4-fiber-local.yaml
  ruby3.4-http-cookie.yaml
  ruby3.4-jmespath.yaml
  ruby3.4-jrjackson.yaml
  ruby3.4-jsonpath.yaml
  ruby3.4-net-http.yaml
  ruby3.4-netrc.yaml
  ruby3.4-pry.yaml
  ruby3.4-rack-2.2.yaml
Labels: bincapz/pass, no-change-rebuild-2025-09

#66314 [shard-17] No-change rebuild old packages
  ruby3.3-fiber-local.yaml
  ruby3.3-filesize.yaml
  ruby3.3-fluent-config-regexp-type.yaml
  ruby3.3-gems.yaml
  ruby3.3-hashie.yaml
  ruby3.3-http-accept.yaml
  ruby3.3-http-cookie.yaml
  ruby3.3-http-form_data.yaml
  ruby3.3-jmespath.yaml
  ruby3.3-jrjackson.yaml
Labels: bincapz/pass, no-change-rebuild-2025-09

#66315 [shard-18] No-change rebuild old packages
  ruby3.3-jsonpath.yaml
  ruby3.3-kubeclient.yaml
  ruby3.3-net-http.yaml
  ruby3.3-netrc.yaml
  ruby3.3-pry.yaml
  ruby3.3-rack-2.2.yaml
  ruby3.3-recursive-open-struct.yaml
  ruby3.3-rest-client.yaml
  ruby3.3-securerandom.yaml
  ruby3.3-webrick.yaml
Labels: bincapz/pass, no-change-rebuild-2025-09

#66311 [shard-14] No-change rebuild old packages
  ruby3.2-pry.yaml
  ruby3.2-rack-2.2.yaml
  ruby3.2-recursive-open-struct.yaml
  ruby3.2-rest-client.yaml
  ruby3.2-securerandom.yaml
  ruby3.2-strptime.yaml
  ruby3.2-webrick.yaml
  ruby3.3-addressable.yaml
  ruby3.3-aes_key_wrap.yaml
  ruby3.3-async-io.yaml
Labels: bincapz/pass, no-change-rebuild-2025-09

#66307 [shard-10] No-change rebuild old packages
  ripgrep.yaml
  ruby3.0-bundler.yaml
  ruby3.2-addressable.yaml
  ruby3.2-aes_key_wrap.yaml
  ruby3.2-async-io.yaml
  ruby3.2-async.yaml
  ruby3.2-attr_required.yaml
  ruby3.2-aws-sdk-kms.yaml
  ruby3.2-aws-sdk-s3.yaml
  ruby3.2-aws-sdk-sqs.yaml
Labels: bincapz/pass, no-change-rebuild-2025-09

#66302 [shard-5] No-change rebuild old packages
  libxt.yaml
  lksctp-tools.yaml
  logstash-output-opensearch.yaml
  lua-json4.yaml
  mitmproxy.yaml
  mkfontscale.yaml
  mtdev.yaml
  numactl.yaml
  owfs.yaml
  php-8.1-amqp.yaml
Labels: bincapz/pass, no-change-rebuild-2025-09

#66333 chore(crossplane): fix ldflag
  crossplane.yaml
Labels: bincapz/pass

#66421 py3-lxml: depend on libxml<2.15, to fix incompatibility
  py3-lxml.yaml
Labels: bincapz/pass

#66450 test(varnish-modules): ensure compat with available varnish
  varnish-modules.yaml
Labels: bincapz/pass

#66453 feat(py3-numpy-1.26.yaml): As part of continuing to support packages in OS that depend on py3-numpy-1*
  py3-numpy-1.26.yaml
Labels: bincapz/pass

#66454 Remove py3-lxml dependency on pinned libxml2
  py3-lxml.yaml
Labels: bincapz/pass

#66574 openjdk-25: drop debuginfo, enable tests
  openjdk-25.yaml
Labels: bincapz/pass

#66547 Switch --version tests to ver-check
  whereabouts.yaml
  wireguard-go.yaml
  wireguard-tools.yaml
  wit-bindgen.yaml
  wizer.yaml
  wl-clipboard.yaml
  wuzz.yaml
  wv.yaml
Labels: bincapz/pass

#66664 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-safetensors.yaml
Labels: bincapz/pass

#66663 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-sacrebleu.yaml
Labels: bincapz/pass

#66662 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-pythran.yaml
Labels: bincapz/pass

#66661 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-pandas.yaml
Labels: bincapz/pass

#66659 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-opt-einsum.yaml
Labels: bincapz/pass

#66649 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-contourpy.yaml
Labels: bincapz/pass

#66645 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  gdal.yaml
Labels: bincapz/pass

#66644 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  apache-arrow.yaml
Labels: bincapz/pass

#66655 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-itables.yaml
Labels: bincapz/pass

#66646 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-apache-beam.yaml
Labels: bincapz/pass

#66667 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-scipy.yaml
Labels: bincapz/pass, ai/skip-comment

#66648 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-cmaes.yaml
Labels: bincapz/pass

#66654 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-hyperopt.yaml
Labels: bincapz/pass

#66665 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-scikit-learn.yaml
Labels: bincapz/pass, ai/skip-comment

#66650 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-dask.yaml
Labels: bincapz/pass

#66666 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-scikit-optimize.yaml
Labels: bincapz/pass, ai/skip-comment

#66658 fix(py3-numpy<2.0): Pin explicitly to py3-numpy-1.26 packages instead of py3-numpy<2.0
  py3-nltk.yaml
Labels: bincapz/pass

#66681 feat(jenkins-2): bump dep to remediate GHSA-jmp9-x22r-554x and GHSA-8v5q-rhf3-jphm
  jenkins-2.yaml
  jenkins-2/pombump-deps-bom.yaml
Labels: bincapz/pass

#66567 WIP
  zipkin.yaml
  zipkin/fix-build-zipkin-server-pom-xml.patch
  zipkin/pombump-deps.yaml
  zipkin/pombump-properties.yaml
Labels: bincapz/blocking, approved-to-run, ai/skip-comment

#66871 feat(gst-plugins-bad): enable openh264enc plugin for gst-plugins-bad package
  gst-plugins-bad.yaml
Labels: bincapz/pass

#66888 Reformat openssf GCC spec files
  openssf-compiler-options.yaml
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/11/openssf.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/12/openssf.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/13/openssf.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/14/openssf.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/15/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/11/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/12/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/13/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/14/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/15/openssf.spec
Labels: bincapz/pass

#67020 fix(rancher-charts): Retain latest git commit
  rancher-2.12.yaml
  rancher-charts-2.12.yaml
  rancher-helm3-charts.yaml
  rancher-partner-charts.yaml
  rancher-rke2-charts.yaml
  rancher-system-charts-2.10.yaml
Labels: bincapz/pass

#67030 fix(mattermost-10.12): Remediate GHSA-jc7w-c686-c4v9 and GHSA-fv92-fjc5-jj9h
  mattermost-10.12.yaml
Labels: bincapz/pass

#67085 numpy-2.2: update dependant packages to use it
  py3-sacrebleu.yaml
Labels: bincapz/pass, inc59

#67076 numpy-2.2: update dependant packages to use it
  py3-gguf.yaml
Labels: bincapz/pass, inc59

#67072 numpy-2.2: update dependant packages to use it
  py3-contourpy.yaml
Labels: bincapz/pass, inc59

#67080 numpy-2.2: update dependant packages to use it
  py3-itables.yaml
Labels: bincapz/pass, inc59

#67074 numpy-2.2: update dependant packages to use it
  py3-faiss-cpu.yaml
Labels: bincapz/pass, inc59

#67067 numpy-2.2: update dependant packages to use it
  apache-arrow.yaml
Labels: bincapz/pass, inc59

#67091 numpy-2.2: update dependant packages to use it
  py3-transformers.yaml
Labels: bincapz/pass, inc59

#67008 systemd: cherry-pick upstream patch exposing system UIDs/GIDs in pkgconf
  systemd.yaml
  systemd/pkgconf-expose-variables-for-system-alloc-uid-gid-min.patch
Labels: bincapz/pass

#67089 numpy-2.2: update dependant packages to use it
  py3-scipy.yaml
Labels: bincapz/pass, inc59

#67090 numpy-2.2: update dependant packages to use it
  py3-seaborn.yaml
Labels: bincapz/pass, inc59

#67073 numpy-2.2: update dependant packages to use it
  py3-dask.yaml
Labels: bincapz/pass, inc59

#67069 py3-apache-beam: numpy-2.2: update dependant packages to use it
  py3-apache-beam.yaml
Labels: bincapz/pass, inc59

#67083 py3-optuna: numpy-2.2: update dependant packages to use it
  py3-optuna.yaml
Labels: bincapz/pass, inc59

#67082 py3-nltk: numpy-2.2: update dependant packages to use it
  py3-nltk.yaml
Labels: bincapz/pass, inc59

#67122 shadow: add minimum system user id to login.defs
  shadow.yaml
Labels: bincapz/pass

#67165 feat(open-webui): bump dep to remediate GHSA-9ggr-2464-2j32
  open-webui.yaml
Labels: bincapz/pass

#67309 CVE-2025-58056/neo4j-2025.08 remediation
  neo4j-2025.08.yaml
  neo4j-2025.08/pombump-deps.yaml
Labels: bincapz/pass

#67348 rootlesskit: remediate CVE
  rootlesskit.yaml
Labels: bincapz/pass

#67405 bats: actually include and test bats libraries
  bats.yaml
Labels: bincapz/pass

#67430 tw - bump to v0.0.28
  pipelines/test/tw/verify-service.yaml
  tw.yaml
Labels: bincapz/pass

#67454 py3-scikit-optimize: numpy-2.2: update dependant packages to use it
  py3-scikit-optimize.yaml
Labels: bincapz/pass, inc59

#67079 py3-hyperopt: numpy-2.2: update dependant packages to use it
  py3-hyperopt.yaml
Labels: bincapz/pass, inc59

#67078 py3-graph-tool: numpy-2.2: update dependant packages to use it
  py3-graph-tool.yaml
Labels: bincapz/pass, inc59

#67482 py3-nltk: py3.10: drop support
  py3-nltk.yaml
Labels: bincapz/pass

#67506 tw - bump to v0.0.30
  pipelines/py/tw/bump-constraints.yaml
  pipelines/test/tw/verify-service.yaml
  tw.yaml
Labels: bincapz/pass

#67565 fix(rancher-dashboard-2.12): Embed Harvester UI extension
  rancher-dashboard-2.12.yaml
Labels: bincapz/pass

#67603 fix(grafana-image-renderer): Bump tar-fs to remediate GHSA-vj76-c3g6-qr5v
  grafana-image-renderer.yaml
  grafana-image-renderer/bump-tar-fs-GHSA-vj76-c3g6-qr5v.patch
Labels: bincapz/pass

#67619 libunistring: update package for 1.4 release
  libunistring.yaml
Labels: bincapz/pass

#67611 liblangtag: refresh package for new upstream version 0.6.8
  liblangtag.yaml
Labels: bincapz/pass

#67624 feat(strimzi-kafka-operator): bump dep to remediate GHSA-2hmj-97jw-28jh
  strimzi-kafka-operator.yaml
  strimzi-kafka-operator/move-access-operator-dependency-to-systemtest.patch
  strimzi-kafka-operator/pombump-deps-cc.yaml
Labels: bincapz/pass, ai/skip-comment

#67660 fio: disable native builds
  fio.yaml
Labels: bincapz/pass
