Repository wolfi-dev/os, pull requests merged in 2025-06, with the labels that each got.

#55038 datadog-agent: remediate cve
  datadog-agent.yaml
Labels: bincapz/pass

#55033 feat(packages): add aio packages - aioboto3, aiodataloader, aiostream
  py3-aioboto3.yaml
  py3-aiodataloader.yaml
  py3-aiostream.yaml
Labels: bincapz/pass, approved-to-run

#54845 [Shard 1] Add output redirection to tests
  apache-nifi.yaml
  apache2.yaml
  chartmuseum.yaml
  clamav-1.4.yaml
  cloud-sql-proxy-2.16.yaml
  coredns.yaml
  cpp-httplib.yaml
  dapr-1.15.yaml
  distribution.yaml
  envoy-1.34.yaml
Labels: bincapz/pass

#54977 [Shard 2] Add output redirection to tests
  envoy-gateway.yaml
  envoy-ratelimit.yaml
  etcd-3.6.yaml
  external-secrets-operator-0.17.yaml
  frp.yaml
  fulcio.yaml
  gatus.yaml
  gitlab-cng-18.0.yaml
  grafana-oncall.yaml
  harbor-registry.yaml
Labels: bincapz/blocking, malcontent/reviewed

#54986 [Shard 7] Add output redirection to tests
  npm.yaml
  nri-kubernetes.yaml
  nsc.yaml
  oauth2-proxy.yaml
  ollama.yaml
  opentelemetry-operator.yaml
  pgpool2-4.6.yaml
  pgpool2_exporter.yaml
  prism.yaml
  procps.yaml
Labels: bincapz/pass

#55002 [Shard 11] Add output redirection to tests
  wildfly.yaml
  xcover.yaml
  zookeeper-3.9.yaml
Labels: bincapz/pass

#55106 gcc: Update `--with-glibc-version` parameter
  gcc.yaml
Labels: bincapz/pass

#55052 py3-numpy: convert to git update backend, bump to 1.26.5
  py3-numpy.yaml
Labels: bincapz/pass

#55138 Renames ffmpeg for version streaming
  ffmpeg-7.yaml
Labels: bincapz/pass

#55146 bump epoch for graph-tool
  py3-graph-tool.yaml
Labels: bincapz/pass

#55144 chore: bump otel-cpp to build against new protobuf
  opentelemetry-cpp.yaml
Labels: bincapz/pass

#55171 curl: fix multi-transfer handling
  curl-rustls.yaml
  curl.yaml
Labels: bincapz/pass

#55000 [Shard 9] Add output redirection to tests
  ruby3.4-prometheus-client.yaml
  ruby3.4-rack.yaml
  ruby3.4-sinatra.yaml
  samba.yaml
  skaffold.yaml
  sndio.yaml
  tailscale.yaml
  teleport.yaml
  tempo.yaml
Labels: bincapz/pass, ai/skip-comment

#55164 chromium: drop clang-19 compat patch
  chromium.yaml
  chromium/clang-19-compat.patch
Labels: bincapz/pass

#55104 update libxml2 to version 2.14.3
  asciidoc.yaml
  at-spi2-core.yaml
  docbook-xml.yaml
  emacs.yaml
  gettext.yaml
  glib-gir.yaml
  glib.yaml
  graphicsmagick.yaml
  gstreamer.yaml
  itstool.yaml
  jenkins-2.yaml
  libcmis.yaml
  libgphoto2.yaml
  libgsf.yaml
  libical.yaml
  liblangtag.yaml
  libselinux.yaml
  libsemanage.yaml
  libxcrypt.yaml
  libxml2.yaml
  libxslt.yaml
  llvm-18.yaml
  llvm15.yaml
  llvm16.yaml
  llvm17.yaml
  memtier-benchmark.yaml
  modsecurity.yaml
  nfs-utils.yaml
  nginx-mainline.yaml
  nginx-stable.yaml
  njs.yaml
  openmp-16.yaml
  openmp-17.yaml
  openmp-18.yaml
  openresty.yaml
  pixz.yaml
  rrdtool.yaml
  s3fs-fuse.yaml
  shared-mime-info.yaml
  wayland.yaml
  wv.yaml
  xdg-utils.yaml
  xmlsec.yaml
Labels: bincapz/pass, ai/skip-comment

#55199 No change rebuild for the libxml2 transition
  ffmpeg-7.yaml
  hwloc.yaml
  libglvnd.yaml
  lighttpd.yaml
  rstudio.yaml
Labels: bincapz/pass, ai/skip-comment

#55218 Rebuild packages for the libxml2 transition
  libxkbcommon.yaml
  llvm-19.yaml
  llvm-20.yaml
  openscap.yaml
Labels: bincapz/pass, ai/skip-comment

#55232 Rebuild postgresql packages for the libxml2 transition
  postgresql-16.yaml
  postgresql-17.yaml
Labels: bincapz/pass

#55231 Rebuild packages for the libxml2 transition
  apache2.yaml
  clamav-1.4.yaml
  collectd.yaml
  fontforge.yaml
  gdal.yaml
  gst-plugins-bad.yaml
Labels: bincapz/pass, ai/skip-comment

#55243 Rebuild postgis-17 with the new version of libxml2
  postgis-17.yaml
Labels: bincapz/pass

#55230 Rebuilds for the libxml2 transition
  oath-toolkit.yaml
  php-8.1.yaml
  php-8.2.yaml
  php-8.3.yaml
  php-8.4.yaml
Labels: bincapz/pass, ai/skip-comment

#54827 add opentel-java-instrumentation
  opentelemetry-java-instrumentation.yaml
Labels: bincapz/pass, ai/skip-comment

#55293 py3-lxml: cherry-pick upstream fix for ftbfs w/ new libxml2
  py3-lxml.yaml
Labels: bincapz/pass

#55269 libxml2: no change rebuilds for transition.
  librsvg.yaml
  openbox.yaml
Labels: bincapz/pass

#55302 py3-xmlsec: no change rebuild for libxml2 transition.
  py3-xmlsec.yaml
Labels: bincapz/pass

#55318 systemd: cherry-pick dbebba11c3b80549ef80bd9005abe0c78a0dfdfe
  systemd.yaml
  systemd/35712.patch
Labels: bincapz/pass

#55324 No change rebuild of prrte for libxml2
  prrte.yaml
Labels: bincapz/pass

#55329 No change rebuild for libxml2
  rust-1.83.yaml
Labels: bincapz/pass

#55330 No change rebuild for libxml2
  rust-1.84.yaml
Labels: bincapz/pass

#55332 No change rebuild for libxml2
  rust-1.86.yaml
Labels: bincapz/pass

#55331 No change rebuild for libxml2
  rust-1.85.yaml
Labels: bincapz/pass

#55334 Rebuild repmgr-17 with libxml2
  repmgr-17.yaml
Labels: bincapz/pass

#55346 Rebuild R for the libxml2 transition
  R.yaml
Labels: bincapz/pass

#55347 Rebuild ingress-nginx-controller-1.12 for the libxml2 transition
  ingress-nginx-controller-1.12.yaml
Labels: bincapz/pass

#55349 Rebuild poppler for the libxml2 transition
  poppler.yaml
Labels: bincapz/pass

#55374 Fix(update): Use Gitlab repo sourcecode and our toolchain to build
  cryptsetup.yaml
Labels: bincapz/pass

#55414 pombump: package update
  pombump.yaml
Labels: bincapz/pass

#55358 "-doc" package fix
  glib.yaml
  grep.yaml
Labels: bincapz/pass, approved-to-run

#55342 empty package fix 3
  i2c-tools.yaml
  kakoune.yaml
  rtmpdump.yaml
Labels: bincapz/pass, approved-to-run

#55362 "-doc" package fix
  m4.yaml
  make.yaml
  nano.yaml
  ndctl.yaml
  netcat-openbsd.yaml
Labels: bincapz/pass, approved-to-run

#55354 "-doc" package fix
  bison.yaml
  exim.yaml
Labels: bincapz/pass, approved-to-run

#55365 "-doc" package fix
  vim.yaml
  wireguard-tools.yaml
  xdpyinfo.yaml
  xterm.yaml
Labels: bincapz/pass, approved-to-run

#55444 util-linux: fix chainguard-2.28 ftbfs
  util-linux.yaml
Labels: bincapz/pass

#55364 "-doc" package fix
  rsyslog.yaml
  rust-1.70.yaml
  scap-security-guide.yaml
  slirp4netns.yaml
  texinfo.yaml
  varnish.yaml
Labels: bincapz/pass, approved-to-run

#55363 "-doc" package fix
  nodejs-20.yaml
  nodejs-22.yaml
  ocamlbuild.yaml
  patch.yaml
  pkcs11-helper.yaml
  rdfind.yaml
Labels: bincapz/pass, approved-to-run

#55462 fix(CVE): [confluent-kafka] Update commons-beanutils transitive dependency to 1.11.0 to address GHSA-wxr5-93ph-8wr9
  confluent-kafka.yaml
  confluent-kafka/fix-GHSA-wxr5-93ph-8wr9-force-update-common-beanutils.patch
Labels: bincapz/pass

#55051 Allow tshark to run as nonroot
  tshark-4.4.yaml
Labels: bincapz/pass

#55491 Bump epoch of packages to pickup latest iamguarded-tools
  cert-manager-1.17.yaml
  contour-1.32.yaml
  envoy-1.34.yaml
  etcd-3.6.yaml
  kubernetes-1.33.yaml
  memcached-exporter.yaml
  memcached.yaml
  mysql-9.3.yaml
  postgresql-17-iamguarded-compat.yaml
  rabbitmq-cluster-operator.yaml
  rabbitmq-messaging-topology-operator.yaml
  rabbitmq-server-4.1.yaml
  valkey.yaml
Labels: approved-to-run

#55494 falco-no-driver: pin build deps to llvm 19
  falco-no-driver.yaml
Labels: bincapz/pass

#54402 stow: Add GNU Stow package
  stow.yaml
Labels: bincapz/pass, ai/skip-comment

#55465 kubernetes-1.33: make kubelet-1.33 subpackage provide kubelet
  kubernetes-1.33.yaml
Labels: bincapz/pass, approved-to-run

#51794 open-webui: new package
  open-webui.yaml
Labels: bincapz/blocking, malcontent/reviewed, ai/skip-comment

#55522 sqlpad: bump tar-fs to 2.1.3 to fix GHSA-8cj5-5rvv-wf4v
  sqlpad.yaml
Labels: bincapz/pass

#55521 bash: Use -std=c17 to fix ftbfs with GCC 15
  bash.yaml
Labels: bincapz/pass

#55450 Add py3-xet-core, a runtime dependency of py3-huggingface-hub
  py3-huggingface-hub.yaml
  py3-xet-core.yaml
Labels: bincapz/pass

#55523 fix - open-webui
  open-webui.yaml
Labels: bincapz/blocking

#55524 xh: bump onig version to fix build error with gcc 15
  xh.yaml
  xh/cargobump-deps.yaml
Labels: bincapz/pass, approved-to-run

#55510 timestamp-authority: Improve tests
  timestamp-authority.yaml
Labels: bincapz/pass

#55583 nginx-s3-gateway: add compression libraries
  nginx-s3-gateway.yaml
Labels: bincapz/pass

#55275 feat(new_package): libass portable subtitle renderer for the ASS/SSA subtitle format.
  libass.yaml
Labels: bincapz/pass, approved-to-run

#55107 gcc-14: Update to 14.3 (and enable auto-updates)
  gcc-14.yaml
  gcc-14/pr117739.patch
Labels: bincapz/pass

#55637 curl: rebuild without overlinking
  curl.yaml
Labels: bincapz/pass

#55356 "-doc" package fix
  fuse-overlayfs.yaml
  gawk.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#55691 azuredisk-csi: withdraw old package versions
  withdrawn-packages.txt
Labels: approved-to-run

#55715 ruby3.x-rails-8.0 GHSA-47m2-26rw-j2jw fix
  ruby3.2-rails-8.0.yaml
  ruby3.3-rails-8.0.yaml
  ruby3.4-rails-8.0.yaml
Labels: bincapz/pass

#55722 alertmanager: add iamguarded compat
  prometheus-alertmanager.yaml
Labels: bincapz/pass

#55470 chore[airflow]: fix airflow-3 and remove older airflow
  airflow-3.yaml
  airflow.yaml
  airflow/cryptography.patch
  airflow/patch.py
  airflow/requests.patch
  airflow/urllib3.patch
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#55359 "-doc" package fix
  htop.yaml
  httpie.yaml
  ipvsadm.yaml
  ldns.yaml
Labels: bincapz/pass, approved-to-run

#55779 distribution: copy config to /etc/distrubution
  distribution.yaml
Labels: bincapz/pass, ai/skip-comment

#55781 Add the missing files to the package and improve the test
  aws-network-policy-agent.yaml
Labels: bincapz/pass

#55801 Add a runtime dep on xz
  ruby3.2-systemd-journal.yaml
Labels: bincapz/pass

#55818 py3-astunparse: Add test/tw/pip-check
  py3-astunparse.yaml
  py3-wheel.yaml
Labels: bincapz/pass

#55605 py3-onnx: cleanup
  py3-onnx.yaml
Labels: bincapz/pass

#55916 chore: make teleport version streamed
  teleport-17.yaml
  teleport-17/bulk-memory.patch
Labels: approved-to-run, ai/skip-comment

#55636 no change rebuild to regenerate SBOM's
  aom.yaml
  binutils.yaml
  bzip2.yaml
  giflib.yaml
  keyutils.yaml
  libcap.yaml
  npth.yaml
Labels: bincapz/pass

#55908 zola: fix build error with gcc 15
  zola.yaml
  zola/cargobump-deps.yaml
Labels: bincapz/pass, approved-to-run

#55957 jenkins-docker-agent: new pkg script
  jenkins-2.yaml
Labels: bincapz/pass

#55992 Elixir Improvements
  elixir-1.17.yaml
  elixir-1.18.yaml
  elixir-1.18/zzz/lib/zzz.ex
  elixir-1.18/zzz/lib/zzz/application.ex
  elixir-1.18/zzz/mix.exs
  elixir-1.18/zzz/test/test_helper.exs
  rebar3.yaml
Labels: bincapz/pass

#55975 k6: Package quality updates
  k6.yaml
Labels: bincapz/pass, approved-to-run

#55976 prometheus: add iamguarded packages
  prometheus-3.4.yaml
Labels: bincapz/pass

#56033 feat(zookeeper-3.9): add iamguarded compat package
  zookeeper-3.9.yaml
Labels: bincapz/pass

#55951 jupyter-base-notebook/GHSA-9hjg-9r4m-mvj7: Rebuild to remediate
  jupyter-base-notebook.yaml
Labels: bincapz/pass

#56070 fix: make unshare optional when not needed
  datadog-agent.yaml
Labels: bincapz/pass, approved-to-run

#56081 Update melange to 0.26.10
  melange.yaml
Labels: bincapz/pass

#54713 Add ldd-check tests to several packages
  postfix.yaml
  rsyslog.yaml
  rustls-ffi.yaml
  subversion.yaml
Labels: bincapz/pass

#56107 chainguard-security-guide: update to stig 3.2.3
  chainguard-security-guide.yaml
Labels: bincapz/pass

#56111 fix: rebuild postfix to pick up permissions fixes
  postfix.yaml
Labels: bincapz/pass

#56011 epoch bump/dynamic-py3-pip fix
  asciidoc.yaml
  dask-kubernetes.yaml
  ggshield.yaml
  in-toto.yaml
  k8s-sidecar.yaml
  kubeflow-katib.yaml
  py3-tensorflow-serving-api.yaml
  spark-3.5.yaml
  tensorflow-cpu-jupyter.yaml
Labels: bincapz/pass, ai/skip-comment

#56093 add keycloak-iamguarded
  keycloak.yaml
Labels: bincapz/pass

#56121 sonar-scanner-cli: use cg libraries
  sonar-scanner-cli.yaml
Labels: bincapz/pass, cg-libraries

#56120 dependency-track: use cg libraries
  dependency-track.yaml
Labels: bincapz/pass, cg-libraries

#56131 Corepack Package update and build from source
  corepack.yaml
  yarn-berry.yaml
Labels: bincapz/pass

#56181 tarball-upload: no change rebuild to test archive generation.
  bzip2.yaml
Labels: staging-build, bincapz/pass

#56012 Fix GHSA-9hjg-9r4m-mvj7: upgrade requests to 2.32.4 in 13 packages
  dask-kubernetes.yaml
  kserve.yaml
  kubeflow-jupyter-web-app.yaml
  kubeflow-katib.yaml
  kubeflow-pipelines.yaml
  kubeflow-volumes-web-app.yaml
  mlflow.yaml
  py3-cassandra-medusa.yaml
  semgrep.yaml
  superset.yaml
  tensorflow-cpu-jupyter.yaml
Labels: bincapz/pass, ai/skip-comment

#56191 No change rebuild of libxslt for chainguard-2.28
  libxslt.yaml
Labels: bincapz/pass

#56182 opensearch-3/GHSA-vgq5-3255-v292 bump kafka-client version in security plugin
  opensearch-3.yaml
  opensearch-3/security-plugin-GHSA-vgq5-3255-v292.patch
Labels: bincapz/pass

#54002 feat: add additonal tests for kong
  kong.yaml
Labels: bincapz/pass, malcontent/reviewed, ai/skip-comment

#56211 Remove libtbb and update opentbb for its removal
  libtbb.yaml
  onetbb.yaml
Labels: bincapz/pass

#56223 tileserver-gl/cve remediation
  tileserver-gl.yaml
Labels: bincapz/pass

#56476 New package for aws-otel-collector
  aws-otel-collector.yaml
Labels: bincapz/pass

#56408 flux: add iam subpackages
  flux-helm-controller.yaml
  flux-image-automation-controller.yaml
  flux-image-reflector-controller.yaml
  flux-kustomize-controller.yaml
  flux-notification-controller.yaml
  flux-source-controller.yaml
Labels: bincapz/pass

#56383 metrics-server: add iamg subpackage
  metrics-server.yaml
Labels: bincapz/pass

#56731 fix: ease hardening of tmpfs on QEMU runner
  microvm-init.yaml
  microvm-init/init
Labels: bincapz/pass, approved-to-run

#56746 fix: QEMU: correctly propagate mounts in chroot
  microvm-init.yaml
  microvm-init/init
Labels: bincapz/pass, approved-to-run

#56755 tarball-upload: no change rebuilds to test robustness improvements.
  binutils.yaml
  busybox.yaml
Labels: staging-build, bincapz/pass

#56788 gcc-14: Add libatomic-14 subpackage
  gcc-14.yaml
Labels: bincapz/pass

#54200 adding redpanda package to wolfi
  redpanda-25.1.yaml
  redpanda-25.1/0001-build-update-krb5-configuration-to-include-system-er.patch
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#56794 kubeflow-centraldashboard: fix GHSA-v6h2-p8h4-qcjw in vendored protobufjs deps
  kubeflow-centraldashboard.yaml
Labels: bincapz/pass

#56795 code-server/GHSA-v6h2-p8h4-qcjw fix
  code-server.yaml
  code-server/fix-GHSA-v6h2-p8h4-qcjw.patch
Labels: bincapz/pass

#56801 rancher-api-ui: fix GHSA-v6h2-p8h4-qcjw brace-expansion vulnerability
  rancher-api-ui.yaml
  rancher-api-ui/fix-GHSA-v6h2-p8h4-qcjw.patch
Labels: bincapz/pass

#56742 electric: add necessary runtime dependencies
  electric.yaml
Labels: bincapz/pass

#56748 spark-3.5: add iamguarded compat
  spark-3.5.yaml
Labels: bincapz/pass, ai/skip-comment

#56556 aws-sigv4-proxy package build
  aws-sigv4-proxy.yaml
Labels: bincapz/pass

#56799 Add redirection to remaining packages
  grafana-oncall.yaml
  kubernetes-csi-livenessprobe.yaml
  mlflow.yaml
  pgpool2_exporter.yaml
  sops.yaml
Labels: bincapz/pass

#56868 add iam subpackage for pushgateway
  prometheus-pushgateway.yaml
Labels: bincapz/pass, ai/skip-comment

#56094 fuse3: don't install init scripts
  fuse3.yaml
Labels: bincapz/pass, ai/skip-comment

#55333 empty package fix 1
  bat.yaml
  benchmark.yaml
  fatrace.yaml
Labels: bincapz/pass, approved-to-run

#56902 Fix subpackage runtime deps, which were meant at the test level
  aws-otel-collector.yaml
Labels: bincapz/pass

#56909 fix(sqlpad): recreate client yarn env for 7.5.4
  sqlpad.yaml
Labels: bincapz/pass

#56912 prometheus-pushgateway: add tzdata and update symlink
  prometheus-pushgateway.yaml
Labels: bincapz/pass, ai/skip-comment

#56835 fix: renamed package and added installed container entrypoint scripts
  kubo.yaml
Labels: bincapz/pass

#56926 feat(logstash-8): add iamguarded compat
  logstash-8.yaml
  logstash-8/logstash.iamguarded.yml
Labels: bincapz/pass

#56747 kubernetes-reflector: init at 9.1.12
  kubernetes-reflector.yaml
  kubernetes-reflector/configmap.yaml
Labels: bincapz/pass

#56960 Fix/systemd unit tests
  systemd.yaml
Labels: bincapz/pass, approved-to-run

#56756 Sonarqube community build package in wolfi
  sonarqube.yaml
  sonarqube/GHSA-hq9p-pm7w-8p54-remediation.patch
  sonarqube/entrypoint.sh
  sonarqube/sonar-eclipse-GHSA-vrpq-qp53-qv56.patch
Labels: bincapz/pass

#55782 quality: extend test it-tools package
  it-tools.yaml
Labels: bincapz/pass, approved-to-run

#56989 bug: Fix openrc test to work in qemu runner
  openrc.yaml
Labels: bincapz/pass

#56997 Add iamguarded-compat package to external-dns
  external-dns.yaml
Labels: bincapz/pass

#56936 metrics-server: build iam compat again
  metrics-server.yaml
Labels: bincapz/pass

#56806 add just-newuidmap-newgidmap
  shadow.yaml
Labels: bincapz/pass

#57015 gcc-14: enable gfortran
  gcc-14.yaml
Labels: bincapz/pass, ai/skip-comment

#57047 tez: use auth/maven pipeline
  tez.yaml
Labels: bincapz/pass

#57056 sonarqube and otel-java-inst: use auth/gradle pipeline
  opentelemetry-java-instrumentation.yaml
  sonarqube-10.yaml
Labels: bincapz/pass

#57071 postfix: use gcc 15 with -std=gnu17 to fix build error
  postfix.yaml
Labels: approved-to-run

#57024 prometheus-operator: add iam subpackage
  prometheus-operator.yaml
Labels: bincapz/pass

#57122 openssf-compiler-options: clang 14
  openssf-compiler-options.yaml
Labels: bincapz/pass

#56763 add clickhouse-iamguarded
  clickhouse-25.2.yaml
Labels: bincapz/pass

#57173 add clickhouse keeper
  clickhouse-25.2.yaml
Labels: bincapz/pass, ai/skip-comment

#57284 openssl: build without jitterentropy on 2.28
  openssl.yaml
Labels: bincapz/pass

#57288 Add epoch field to redpanda-25.1 package definition
  redpanda-25.1.yaml
Labels: bincapz/pass, approved-to-run

#48225 usrmerge - /lib - wolfi-baselayout
  wolfi-baselayout.yaml
Labels: bincapz/pass

#57301 lz4 package: lz4-static fix
  lz4.yaml
Labels: bincapz/pass

#48222 glibc - usrmerge /lib
  glibc.yaml
Labels: bincapz/pass, ai/skip-comment

#48224 usrmerge /lib 2
  gnupg.yaml
  libfido2.yaml
  libselinux.yaml
  libsepol.yaml
  lvm2.yaml
  man-db.yaml
Labels: bincapz/pass, ai/skip-comment

#57319 samba: fix usrmerge lib miss
  samba.yaml
Labels: bincapz/pass

#57313 gdk-pixbuf: fix fetch URL, update to latest version
  gdk-pixbuf.yaml
Labels: bincapz/pass, ai/skip-comment

#57331 rename dotty -> scala-3
  scala-3.7.yaml
Labels: bincapz/pass

#57338 db: Build with GCC 14 to workaround FTBFS
  db.yaml
Labels: bincapz/pass

#57336 ncurses: Fix version-transform
  ncurses.yaml
Labels: bincapz/pass

#54700 drupal: init package
  drupal-11.yaml
Labels: bincapz/blocking, malcontent/reviewed, ai/skip-comment
