Repository wolfi-dev/os, pull requests merged in 2025-04, with the labels that each got.

#48715 fix(spark-operator): Add missing ldflags
  spark-operator.yaml
Labels: bincapz/pass

#48615 fix CVE-2024-12905 for tileserver-gl
  tileserver-gl.yaml
  tileserver-gl/CVE-2024-12905.patch
Labels: bincapz/pass

#41032 gst-libav: new package
  gst-libav.yaml
Labels: bincapz/pass

#48736 avahi - fix installation to /usr/bin rather than /bin
  avahi.yaml
Labels: bincapz/pass

#48686 tests: add service file test pipeline and use it in in a few packages
  chrony.yaml
  openssh.yaml
  pipelines/test/verify-service.yaml
  systemd.yaml
Labels: bincapz/pass

#48511 openssf-compiler-options: Provide linker flags via `link` spec
  openssf-compiler-options.yaml
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/11/openssf.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/12/openssf.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/13/openssf.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/14/openssf-nomelange.spec
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/14/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/11/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/12/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/13/openssf.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/14/openssf-nomelange.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/14/openssf.spec
Labels: bincapz/pass, ai/skip-comment

#48692 py3-jupyterlab-server: update
  py3-jupyterlab-server.yaml
Labels: bincapz/pass

#48751 py3-requests-unixsocket: fix fetch URL, bump to latest version
  py3-requests-unixsocket.yaml
Labels: bincapz/pass

#48776 ruby3.2-llhttp: bump to latest version, re-enable automatic updates
  ruby3.2-llhttp.yaml
Labels: bincapz/pass

#48781 ruby3.4-llhttp: bump to latest version, re-enable automatic updates
  ruby3.4-llhttp.yaml
Labels: bincapz/pass

#48778 ruby3.3-llhttp: bump to latest version, re-enable automatic updates
  ruby3.3-llhttp.yaml
Labels: bincapz/pass

#48768 libtheora: fix update config, bump to version 1.2.0
  ffmpeg.yaml
  gst-plugins-base.yaml
  libtheora.yaml
  libtheora/automake.patch
  libtheora/enc.patch
  libtheora/fix-mmx.patch
  libtheora/fix-timeb.patch
  libtheora/libtheora-flags.patch
Labels: bincapz/pass

#48788 hack
  py3-pip.yaml
  py3-supported-python.yaml
Labels: bincapz/pass

#48695 Adjust sed to match new `link` GCC spec
  datadog-agent.yaml
  k8s-device-plugin.yaml
Labels: bincapz/pass

#48739 Lddchecks batch16
  libdeflate.yaml
  libepoxy.yaml
  libestr.yaml
  libev.yaml
  libevdev.yaml
  libevent.yaml
  libexif.yaml
  libfastjson.yaml
  libfido2.yaml
  libfontenc.yaml
  libgcrypt.yaml
Labels: bincapz/pass

#48796 Lddchecks batch24
  alsa-lib.yaml
  argon2.yaml
  armadillo.yaml
  arpack.yaml
  avahi.yaml
  boost.yaml
Labels: bincapz/pass

#48740 Lddchecks batch17
  libapr.yaml
  libarchive.yaml
  libart-lgpl.yaml
  libasyncns.yaml
  libatasmart.yaml
  libatomic_ops.yaml
  libburn.yaml
  libcap-ng.yaml
  libcmis.yaml
  libdaemon.yaml
  libdc1394.yaml
  llvm.yaml
Labels: bincapz/pass

#48750 Lddchecks batch18
  jemalloc.yaml
  jq.yaml
  json-c.yaml
  jsoncpp.yaml
  lame.yaml
  ldns.yaml
  lerc.yaml
  libacvp.yaml
  libaio.yaml
Labels: bincapz/pass

#48752 Lddchecks batch19
  guile.yaml
  highway.yaml
  http-parser.yaml
  hunspell.yaml
  imath.yaml
  imlib2.yaml
  inotify-tools.yaml
  ipset.yaml
  isl.yaml
  ivykis.yaml
  jack.yaml
  jasper.yaml
  jbig2dec.yaml
  jellyfin.yaml
Labels: bincapz/pass

#48774 Lddchecks batch22
  crc32c.yaml
  dbus-glib.yaml
  dieharder.yaml
  elfutils.yaml
  ell.yaml
  eudev.yaml
  eventlog.yaml
  exim.yaml
  fftw.yaml
  flac.yaml
  freetype.yaml
  fribidi.yaml
Labels: bincapz/pass, ai/skip-comment

#48787 Lddchecks batch23
  benchmark.yaml
  blosc.yaml
  brotli.yaml
  cairo.yaml
  cdparanoia.yaml
  check.yaml
  cjson.yaml
  clang-16.yaml
  clang-17.yaml
  clang-18.yaml
  clblast.yaml
  cmocka.yaml
  cppunit.yaml
Labels: bincapz/pass

#48798 thingsboard: bump spring-security.version
  thingsboard.yaml
  thingsboard/pombump-deps.yaml
  thingsboard/pombump-properties.yaml
Labels: bincapz/pass

#48757 Lddchecks batch20
  glu.yaml
  gnu-libiconv.yaml
  gnucobol.yaml
  graphicsmagick.yaml
  graphite2.yaml
  grpc-1.68.yaml
  gsl.yaml
  gsm.yaml
  gtk-2.0.yaml
  gtk-3.yaml
  gtk-4.yaml
  guacamole-server.yaml
Labels: bincapz/pass

#48817 Fix CVE-2024-12905 on sqlpad
  sqlpad.yaml
Labels: bincapz/pass

#48797 feat: new package for clickhouse-operator
  clickhouse-operator.yaml
Labels: bincapz/pass

#48825 Bump vitess-21 epoch to remediate CVE-2025-31125
  vitess-21.0.yaml
Labels: bincapz/pass

#48809 py3-pybind11 correct name of cmake function
  py3-pybind11.yaml
  py3-pybind11/Correct-name-of-cmake-function.patch
Labels: bincapz/pass

#48862 py3-aiobotocore: new package
  py3-aiobotocore.yaml
Labels: bincapz/pass

#48624 add rancher-machine
  rancher-machine.yaml
Labels: bincapz/pass, ai/skip-comment

#48770 Lddchecks batch21
  fstrm.yaml
  fuse3.yaml
  gc.yaml
  gd.yaml
  gdal.yaml
  gdk-pixbuf.yaml
  geoip.yaml
  gflags.yaml
  giflib.yaml
  glog.yaml
  glpk.yaml
  glslang.yaml
Labels: bincapz/pass

#48892 py3-jupyter-lsp: update package for all python versions
  py3-jupyter-lsp.yaml
Labels: bincapz/pass

#48893 py3-jupyterlab: add missing runtime dependencies
  py3-jupyterlab.yaml
Labels: bincapz/pass

#48894 buck2: update to latest version, remove need for manual updates
  buck2.yaml
Labels: bincapz/pass

#48916 Flannel
  flannel.yaml
Labels: bincapz/pass

#48967 Disable DNSSEC by default in systemd-resolved
  systemd.yaml
Labels: bincapz/pass

#48956 py3-arrow: new package
  py3-arrow.yaml
Labels: bincapz/pass

#48966 py3-pdm-backend: new package
  py3-pdm-backend.yaml
Labels: bincapz/pass

#48957 druid/GHSA-2c59-37c4-qrx5/GHSA-55g7-9cwv-5qfv/GHSA-fjpj-2g6w-x25r/GHSA-pqr6-cmr2-h8hf/GHSA-qcwq-55hx-v3vh/fixes
  druid.yaml
  druid/GHSA-2c59-37c4-qrx5-fix.patch
  druid/pombump-deps.yaml
Labels: bincapz/pass

#48928 add missing scripts to whereabouts package
  whereabouts.yaml
Labels: bincapz/pass

#43573 5183 ceph package diverge
  ceph.yaml
  ceph/fix-osd-class-dir.patch
  ceph/fix-submodule.patch
  rook.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#48984 py3-webcolors: new package
  py3-webcolors.yaml
Labels: bincapz/pass

#48991 py3-fqdn: new package
  py3-fqdn.yaml
Labels: bincapz/pass

#48992 xmlsec: fix update config, bump to 1.3.7
  xmlsec.yaml
Labels: bincapz/pass

#41405 Introduce libcurl-abi virtual package
  CODEOWNERS
  curl-rustls.yaml
  curl.yaml
  withdrawn-packages.txt
Labels: bincapz/pass

#49011 py3-jsonpointer: split binary from library - add functional testing
  py3-jsonpointer.yaml
Labels: bincapz/pass

#49014 wildfly-35.0.1/cve remediation
  wildfly.yaml
Labels: bincapz/pass

#48907 use SOURCE_DATE_EPOCH when invoking `date` for build dates
  amazon-cloudwatch-agent.yaml
  apko.yaml
  argo-rollouts.yaml
  argocd-image-updater.yaml
  aws-efs-csi-driver.yaml
  aws-s3-controller.yaml
  azuredisk-csi-1.31.yaml
  boring-registry.yaml
  chezmoi.yaml
  cloud-provider-azure-1.32.yaml
  cluster-api-1.9.yaml
  cosign.yaml
  descheduler.yaml
  fluent-bit-plugin-loki.yaml
  glow.yaml
  hydra.yaml
  k9s.yaml
  knative-client.yaml
  kube-state-metrics.yaml
  kubebuilder.yaml
  kuberlr.yaml
  kustomize.yaml
  lazydocker.yaml
  lazygit.yaml
  logstash-exporter.yaml
  mods.yaml
  mountpoint-s3-csi-driver.yaml
  nats-top.yaml
  openbao.yaml
  otel-cli.yaml
  sftpgo-plugin-auth.yaml
  sftpgo-plugin-eventsearch.yaml
  sftpgo-plugin-eventstore.yaml
  sftpgo-plugin-geoipfilter.yaml
  sftpgo-plugin-kms.yaml
  sftpgo-plugin-pubsub.yaml
  sftpgo.yaml
  skaffold.yaml
  spark-operator.yaml
  step-ca.yaml
  traefik-3.3.yaml
  wolfictl.yaml
  x509-certificate-exporter.yaml
  xeol.yaml
Labels: bincapz/pass, ai/skip-comment

#48880 openjdk-24: move to ga version
  openjdk-24.yaml
Labels: bincapz/pass, ai/skip-comment

#48109 prometheus-operator: add bitnami-compat subpackage
  prometheus-operator.yaml
Labels: bincapz/pass

#48920 NSC Package tests addition
  nsc.yaml
Labels: bincapz/pass

#45713 Nats box adder
  nats-box.yaml
Labels: bincapz/pass, ai/skip-comment

#49036 Revert "curl,curl-rusttls: Establish libcurl-abi virtual package"
  curl-rustls.yaml
  curl.yaml
Labels: bincapz/pass

#49024 fix more instances of `date` with `SOURCE_DATE_EPOCH`
  aws-load-balancer-controller.yaml
  cloudprober.yaml
  dive.yaml
  gitlab-cng-17.10.yaml
  gitlab-kas-17.10.yaml
  jitsucom-bulker.yaml
  k8ssandra-operator.yaml
  kserve-modelmesh.yaml
  kuberay-operator.yaml
  metacontroller.yaml
  nats-server-config-reloader.yaml
  secrets-store-csi-driver-provider-azure.yaml
  stern.yaml
  timestamp-authority.yaml
  vault-benchmark.yaml
  vitess-21.0.yaml
Labels: bincapz/pass, ai/skip-comment

#49002 Add build deps and extra-library-paths so ldd-checks pass
  openjdk-12.yaml
  openjdk-13.yaml
  openjdk-14.yaml
  openjdk-15.yaml
  openjdk-16.yaml
  openjdk-17.yaml
  openjdk-18.yaml
  openjdk-19.yaml
  openjdk-20.yaml
Labels: bincapz/pass

#48993 py3-amazon-q-developer-jupyterlab-ext: new package
  py3-amazon-q-developer-jupyterlab-ext.yaml
Labels: bincapz/pass

#49067 add pgvector-17 package
  pgvector-17.yaml
Labels: bincapz/pass

#49017 pipelines/test/verify-service: test sockets, allow skipping files
  pipelines/test/verify-service.yaml
  systemd.yaml
Labels: bincapz/pass

#49018 lvm2: ship service files, depend on lvm2 in device mapper
  lvm2.yaml
Labels: bincapz/pass

#49082 add docker-machine-driver-harvester and docker-machine-driver-linode
  docker-machine-driver-harvester.yaml
  docker-machine-driver-linode.yaml
Labels: bincapz/pass

#49097 openjdk24 bump for rebuild
  openjdk-24.yaml
Labels: bincapz/pass

#49215 make 5 more packages reproducible
  eksctl.yaml
  newrelic-prometheus-configurator.yaml
  nri-kubernetes.yaml
  secrets-store-csi-driver.yaml
  thanos.yaml
Labels: bincapz/pass

#49163 nethack: make the build reproducible
  nethack.yaml
Labels: bincapz/pass

#49254 Patch GHSA-3wgm-2gw2-vh5m in our k8s package by disabling git repo pl…
  kubernetes-1.32.yaml
Labels: bincapz/pass

#49268 rustup: bump openssl to 0.10.72 to fix GHSA-4fcv-w3qc-ppgg
  rustup.yaml
  rustup/cargobump-deps.yaml
Labels: bincapz/pass

#49208 add rancher-helm-3
  rancher-helm-3.yaml
Labels: bincapz/pass

#49129 add rancher-telemetry and cdrkit
  cdrkit.yaml
  cdrkit/gcc10.patch
  cdrkit/implicit.patch
  cdrkit/series
  cdrkit/werrorformat.patch
  rancher-telemetry.yaml
Labels: bincapz/pass, ai/skip-comment

#49022 Add gem check batch2
  ruby3.2-addressable.yaml
  ruby3.2-aes_key_wrap.yaml
  ruby3.2-async-http.yaml
  ruby3.2-async-io.yaml
  ruby3.2-async-pool.yaml
  ruby3.2-async.yaml
  ruby3.2-attr_required.yaml
  ruby3.2-base64.yaml
  ruby3.2-benchmark.yaml
  ruby3.2-bindata.yaml
  ruby3.2-builder.yaml
  ruby3.2-bundler.yaml
Labels: bincapz/pass

#49066 Add gem check batch4
  ruby3.2-elasticsearch-api.yaml
  ruby3.2-elasticsearch.yaml
  ruby3.2-erubi.yaml
  ruby3.2-excon.yaml
  ruby3.2-faraday-excon.yaml
  ruby3.2-faraday-follow_redirects.yaml
  ruby3.2-faraday.yaml
  ruby3.2-ffi.yaml
  ruby3.2-fiber-annotation.yaml
  ruby3.2-fiber-local.yaml
  ruby3.2-fiber-storage.yaml
  ruby3.2-filesize.yaml
Labels: bincapz/pass

#49068 Add gem check batch5
  ruby3.2-gems.yaml
  ruby3.2-hashie.yaml
  ruby3.2-http-accept.yaml
  ruby3.2-http-cookie.yaml
  ruby3.2-http-form_data.yaml
  ruby3.2-http.yaml
  ruby3.2-http_parser.rb.yaml
  ruby3.2-i18n.yaml
  ruby3.2-io-console.yaml
  ruby3.2-io-endpoint.yaml
  ruby3.2-io-event.yaml
  ruby3.2-io-stream.yaml
Labels: bincapz/pass

#49065 Add gem check batch3
  ruby3.2-charlock_holmes.yaml
  ruby3.2-clamp.yaml
  ruby3.2-coderay.yaml
  ruby3.2-connection_pool.yaml
  ruby3.2-console.yaml
  ruby3.2-cool.io.yaml
  ruby3.2-csv.yaml
  ruby3.2-date.yaml
  ruby3.2-deep_merge.yaml
  ruby3.2-domain_name.yaml
  ruby3.2-drb.yaml
  ruby3.2-elastic-transport.yaml
Labels: bincapz/pass

#49214 Package ELF notes transition cleanup
  git.yaml
  gops.yaml
  openssf-compiler-options.yaml
  openssf-compiler-options/usr/lib/gcc/aarch64-unknown-linux-gnu/14/openssf-nomelange.spec
  openssf-compiler-options/usr/lib/gcc/x86_64-pc-linux-gnu/14/openssf-nomelange.spec
  openssl.yaml
  pax-utils.yaml
  rust-audit-info.yaml
Labels: kind/cleanup, bincapz/pass

#49308 docker: add package to configure daemon to use GCR mirror
  docker.yaml
Labels: bincapz/pass, ai/skip-comment

#49037 Yamale package addition
  py3-yamale.yaml
Labels: bincapz/pass, ai/skip-comment

#49271 linkerd-extension-init: bump openssl to fix GHSA-4fcv-w3qc-ppgg
  linkerd-extension-init.yaml
  linkerd-extension-init/cargobump-deps.yaml
Labels: bincapz/pass

#49307 add grpc_health_probe symlink with grpc-health-probe package
  grpc-health-probe.yaml
Labels: bincapz/pass, ai/skip-comment

#49088 py3-jupyterlab / py3-amazon-q-developer-jupyterlab-ext dependency cleanup
  py3-aiobotocore.yaml
  py3-aiohttp.yaml
  py3-amazon-q-developer-jupyterlab-ext.yaml
  py3-jupyter-lsp.yaml
  py3-jupyterlab-server.yaml
  py3-jupyterlab.yaml
Labels: bincapz/pass

#49263 jitsucom-jitsu: bump nextjs to 15.2.4 to fix CVE-2025-30218
  jitsucom-jitsu.yaml
Labels: bincapz/pass

#49321 py3-langsmith: new package
  py3-langsmith.yaml
Labels: bincapz/pass

#49340 perl-module-runtime: fix fetch URL, new version
  perl-module-runtime.yaml
Labels: bincapz/pass

#49270 Chart-testing package addition
  chart-testing.yaml
Labels: bincapz/pass

#49273 Flannel
  flannel.yaml
Labels: bincapz/pass

#49343 linkerd-extension-init: use test/daemon-check-output pipeline
  linkerd-extension-init.yaml
Labels: bincapz/pass

#49375 Chart-testing package - Added bash as runtime dependency
  chart-testing.yaml
Labels: bincapz/pass

#49359 linkerd2: bump openssl and tokio
  linkerd2.yaml
  linkerd2/cargobump-deps.yaml
Labels: bincapz/pass

#49432 py3-jsonpatch: split jsonpatch binaries from jsonpatch lib / adding additional testing
  py3-jsonpatch.yaml
Labels: bincapz/pass

#49326 py3-langchain-core: new package
  py3-langchain-core.yaml
Labels: bincapz/pass

#48985 chore: add runtime dependencies
  vault-env.yaml
  vault-secrets-webhook.yaml
Labels: bincapz/pass

#49327 py3-langchain-text-splitters: new package
  py3-langchain-text-splitters.yaml
Labels: bincapz/pass

#49470 py3-pybind11: Update patch to allow using Python3_add_library()
  py3-pybind11.yaml
  py3-pybind11/Correct-name-of-cmake-function.patch
  py3-pybind11/cmake-Use-any-available-Python_add_library-command.patch
Labels: bincapz/pass, ai/skip-comment

#49274 grafana-pyroscope-1.13 package build
  grafana-pyroscope-1.13.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#49480 qdrant/GHSA-rr8g-9fpq-6wmg fix
  qdrant.yaml
  qdrant/cargobump-deps.yaml
Labels: bincapz/pass

#49395 New packages for py3-repoze.lru and py3-routes
  py3-repoze.lru.yaml
  py3-routes.yaml
Labels: bincapz/pass

#49526 py3-kubernetes: support multiple Pythons
  py3-kubernetes.yaml
Labels: bincapz/pass

#49561 fix(update): Bump yunikorn-k8shim to 1.6.2 and ignore pre-release tags and use tag to get the version
  yunikorn-k8shim.yaml
Labels: bincapz/pass

#49445 fix(rabbitmq-server): set correct version via PROJECT_VERSION and improve test coverage
  rabbitmq-server-4.0.yaml
Labels: bincapz/pass, approved-to-run

#49564 py3-locket: new package
  py3-locket.yaml
Labels: bincapz/pass

#49569 py3-toolz: new package
  py3-toolz.yaml
Labels: bincapz/pass

#49577 libnotify: fix gcc argument ordering in test, fixing build failure
  libnotify.yaml
Labels: bincapz/pass

#49570 neuvector-sigstore-interface: snapshot latest upstream commit
  neuvector-sigstore-interface.yaml
Labels: bincapz/pass

#49562 scripts/auto-approve-pr.sh: Only look for open, unreviewed PRs
  scripts/auto-approve-pr.sh
Labels: auto-approver-bot/approve

#49583 Update the gcsfuse package to the latest version
  gcsfuse.yaml
Labels: bincapz/pass

#49578 smarter-device-manager: remove unneeded go/bump
  smarter-device-manager.yaml
Labels: bincapz/pass

#49670 downgrade npm to 11.2.0
  npm.yaml
Labels: bincapz/pass

#49477 py3-langchain: new package
  py3-langchain.yaml
Labels: bincapz/pass

#49555 added subpackages readinessprobe and version-upgrade-hook to mongodb-kubernetes-operator
  mongodb-kubernetes-operator.yaml
Labels: bincapz/pass

#49704 feat: add amazon-cloudwatch-agent-all subpackage, to install everything
  amazon-cloudwatch-agent.yaml
Labels: bincapz/pass

#49709 npm: add test for issue that should block updates, re-enable updates
  npm.yaml
Labels: bincapz/pass

#49765 Fix the python shbang for oscap-docker which has /usr/sbin/python3
  openscap.yaml
Labels: bincapz/pass

#49674 in-toto: new package
  in-toto.yaml
Labels: bincapz/pass

#49728 py3-tblib: new package
  py3-tblib.yaml
Labels: bincapz/pass

#49775 py3-lz4: new package
  py3-lz4.yaml
Labels: bincapz/pass

#49741 py3-zict: new package
  py3-zict.yaml
Labels: bincapz/pass

#49751 dask-gateway/2025.4.0 package update
  dask-gateway.yaml
Labels: bincapz/pass, approved-to-run

#49664 package update: Bump to stable v3.0.0 and enable automated updates
  distribution.yaml
Labels: bincapz/pass

#49777 iptables - split iptables-apply out to a subpackage.
  iptables.yaml
Labels: bincapz/pass

#49716 feat: add systemd-repart for ext4
  systemd.yaml
  systemd/50-root-ext4.conf
  systemd/50-root-xfs.conf
Labels: bincapz/pass

#49838 bug: fix systemd-logind-service subpackage
  systemd.yaml
Labels: bincapz/pass

#49880 add missing provides for subpkgs of knative-operator
  knative-operator-1.17.yaml
Labels: bincapz/pass

#47422 add rancher-ui-2.10
  rancher-ui-2.10.yaml
Labels: bincapz/pass, ai/skip-comment

#49935 nfs-ganesha: enable ceph support
  nfs-ganesha.yaml
Labels: bincapz/pass

#49784 py3-dask: new package
  py3-dask.yaml
  py3-distributed.yaml
Labels: bincapz/pass

#49958 py3-deepmerge: new package
  py3-deepmerge.yaml
  py3-deepmerge/test.py
Labels: bincapz/pass

#49946 fix(kubernetes-1.32): add ip6tables to kube-proxy runtime dependencies
  kubernetes-1.32.yaml
Labels: approved-to-run

#49980 py3-distributed: re-enable runtime dependency / package tests
  py3-distributed.yaml
Labels: bincapz/pass

#49913 new: gptfdisk
  gptfdisk.yaml
  gptfdisk/fix-cgdisk-linking.patch
  gptfdisk/fix-wrong-include.patch
Labels: bincapz/pass

#49941 py3-pyyaml: depend on all cypthons
  py3-pyyaml.yaml
Labels: bincapz/pass

#49786 Fix subversion builds in QEMU
  subversion.yaml
Labels: bincapz/pass

#49718 add kube-vip-cloud-provider pkg
  kube-vip-cloud-provider-0.0.11.yaml
Labels: bincapz/pass

#49661 new: smartmontools
  smartmontools.yaml
Labels: bincapz/pass

#49269 add wiremock package
  wiremock-oci-entrypoint.yaml
  wiremock.yaml
Labels: bincapz/pass

#49249 add fastfetch package
  fastfetch.yaml
Labels: bincapz/pass

#49219 github-mcp-server: new package
  github-mcp-server.yaml
Labels: bincapz/pass

#48359 add(new): pvc-autoresizer package non-fips
  pvc-autoresizer.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#50008 ceph: add more missing dependencies
  ceph.yaml
Labels: bincapz/pass

#50044 pgbouncer: enable automatic updates, bump to latest version
  pgbouncer.yaml
Labels: bincapz/pass

#47404 add rancher-2.10
  rancher-2.10.yaml
Labels: bincapz/pass, ai/skip-comment

#50207 add rancher-ui-driver-linode
  docker-machine-driver-linode.yaml
  rancher-ui-driver-linode.yaml
Labels: bincapz/pass, ai/skip-comment

#50239 refactor oras to use go/build pipeline
  oras.yaml
Labels: bincapz/pass

#50240 add more tests to openfga package
  openfga.yaml
Labels: bincapz/pass

#50243 wiremock: create more required dirs
  wiremock.yaml
Labels: bincapz/pass

#50241 grpcurl: remove build-time deps and add tests
  grpcurl.yaml
Labels: bincapz/pass

#50251 rebuild rancher and retry for export-images
  rancher-2.10.yaml
Labels: bincapz/pass, ai/skip-comment

#50202 kserve/update: refactor poetry install; omit cuda related deps
  kserve.yaml
Labels: bincapz/pass

#50126 fish 4.x.x rust build
  fish.yaml
Labels: bincapz/pass

#50304 shardowsocks-rust-1.23.0-r2/cve remediation
  shadowsocks-rust.yaml
  shadowsocks-rust/cargobump-deps.yaml
Labels: bincapz/pass

#50290 cassandra-5.0: bump to version 5.0.4
  cassandra-5.0.yaml
  cassandra-5.0/fix-doc-build.patch
Labels: bincapz/pass, ai/skip-comment

#50327 release numpy-2.x packages
  py3-numpy.yaml
Labels: bincapz/pass

#50417 xfsprogs: fix missing python3 dep for xfs_protofile, misc tests
  xfsprogs.yaml
Labels: bincapz/pass

#50419 httpie: use python/build-wheel pipeline to build httpie
  httpie.yaml
Labels: bincapz/pass

#50413 build gdal with numpy bindings
  gdal.yaml
Labels: bincapz/pass
