Repository wolfi-dev/os, pull requests merged in 2025-03, with the labels that each got.

#44204 Add the ldd-check test to apr-util
  apr-util.yaml
Labels: bincapz/pass

#44203 Add the ldd-check test to gpsd
  gpsd.yaml
Labels: bincapz/pass

#44202 Add the ldd-check test to gpgme
  gpgme.yaml
Labels: bincapz/pass

#44201 Add the ldd-check test to gstreamer
  gstreamer.yaml
Labels: bincapz/pass

#44200 Add the ldd-check test to gtest
  gtest.yaml
Labels: bincapz/pass

#44198 Add the ldd-check test to hwloc
  hwloc.yaml
Labels: bincapz/pass

#44197 Add the ldd-check test to heimdal
  heimdal.yaml
Labels: bincapz/pass

#44196 Add the ldd-check test to hiredis
  hiredis.yaml
Labels: bincapz/pass

#44195 Add the ldd-check test to hdf5
  hdf5.yaml
Labels: bincapz/pass

#44184 Add the ldd-check test to dbus
  dbus.yaml
Labels: bincapz/pass

#44183 Add the ldd-check test to acl
  acl.yaml
Labels: bincapz/pass

#44165 Add the ldd-check test to dhclient
  dhclient.yaml
Labels: bincapz/pass

#44220 font-ubuntu: switch to the SPDX identifier
  font-ubuntu.yaml
Labels: bincapz/pass, oss-licensing

#44117 fix postunpack.sh to generate postgresql.conf file
  postgresql-17-bitnami-compat.yaml
Labels: bincapz/pass

#44112 ksm: use go/build, add bitnami-compat and expand tests
  kube-state-metrics.yaml
Labels: bincapz/pass, ai/skip-comment

#43073 License fun: add the licensee tool and all it's dependencies
  ruby3.4-dotenv.yaml
  ruby3.4-licensee.yaml
  ruby3.4-licensee/test-data/LICENSE.md
  ruby3.4-nokogiri.yaml
  ruby3.4-octokit.yaml
  ruby3.4-reverse_markdown.yaml
  ruby3.4-rugged.yaml
  ruby3.4-rugged/fix-libgit2-paths.patch
  ruby3.4-rugged/fix-system-libgit2-1.9.0.patch
  ruby3.4-sawyer.yaml
  ruby3.4-thor.yaml
Labels: bincapz/pass

#44133 feat(mysql-9.1): add bitnami-compat package
  mysql-9.1.yaml
  mysql-9.1/bitnami-my.cnf
Labels: bincapz/pass

#44061 remove yq from kubectl-bitnami-compat
  kubernetes-1.32.yaml
Labels: bincapz/pass

#44293 wait-for-port: use go/build pipeline and add test
  wait-for-port.yaml
Labels: bincapz/pass

#44272 Add the ldd-check test to bluez
  bluez.yaml
Labels: bincapz/pass

#44271 Add the ldd-check test to aws-c-sdkutils
  aws-c-sdkutils.yaml
Labels: bincapz/pass

#44270 Add the ldd-check test to aws-c-s3
  aws-c-s3.yaml
Labels: bincapz/pass

#44269 Add the ldd-check test to aws-c-mqtt
  aws-c-mqtt.yaml
Labels: bincapz/pass

#44268 Add the ldd-check test to aws-c-io
  aws-c-io.yaml
Labels: bincapz/pass

#44267 Add the ldd-check test to aws-c-http
  aws-c-http.yaml
Labels: bincapz/pass

#44266 Add the ldd-check test to aws-checksums
  aws-checksums.yaml
Labels: bincapz/pass

#44265 Add the ldd-check test to aws-c-event-stream
  aws-c-event-stream.yaml
Labels: bincapz/pass

#44262 Add the ldd-check test to attr
  attr.yaml
Labels: bincapz/pass

#44261 Add the ldd-check test to ati-sp2-core
  at-spi2-core.yaml
Labels: bincapz/pass

#44259 Add the ldd-check test to aom
  aom.yaml
Labels: bincapz/pass

#44263 Add the ldd-check test to aws-c-common
  aws-c-common.yaml
Labels: bincapz/pass

#44258 Add the ldd-check test to rustls-ffi
  rustls-ffi.yaml
Labels: bincapz/pass

#44257 Add the ldd-check test to s-lang
  s-lang.yaml
Labels: bincapz/pass

#44253 Add the ldd-check test to aws-c-cal
  aws-c-cal.yaml
Labels: bincapz/pass

#44255 Add the ldd-check test to simdjson
  simdjson.yaml
Labels: bincapz/pass

#44256 Add the ldd-check test to sn2-tls
  s2n-tls.yaml
Labels: bincapz/pass

#44303 render-template: use go/build and add tests
  render-template.yaml
Labels: bincapz/pass

#44175 py3-pydantic: pin pydantic-core at version expected by upstream
  py3-pydantic.yaml
Labels: bincapz/pass

#44339 ntfs3g - usrmerge sbin, bin, usr/sbin to usr/bin/
  ntfs-3g.yaml
Labels: bincapz/pass

#44221 git: enable ELF package notes canary
  git.yaml
Labels: bincapz/pass

#44379 Add the ldd-check test to graphicsmagick
  graphicsmagick.yaml
Labels: bincapz/pass

#44331 Add the ldd-check test to botan
  botan.yaml
Labels: bincapz/pass

#44332 Add the ldd-check test to btrfs-progs
  btrfs-progs.yaml
Labels: bincapz/pass

#44333 Add the ldd-check test to bzip2
  bzip2.yaml
Labels: bincapz/pass

#44378 Add the ldd-check test to graphene
  graphene.yaml
Labels: bincapz/pass

#44345 Add the ldd-check test to cyrus-sasl
  cyrus-sasl.yaml
Labels: bincapz/pass

#44350 Add the ldd-check test to dav1d
  dav1d.yaml
Labels: bincapz/pass

#44356 Add the ldd-check test to enchant2
  enchant2.yaml
Labels: bincapz/pass

#44357 Add the ldd-check test to expat
  expat.yaml
Labels: bincapz/pass

#44358 Add the ldd-check test to falco
  falco.yaml
Labels: bincapz/pass

#44364 Add the ldd-check test to fmt
  fmt.yaml
Labels: bincapz/pass

#44365 Add the ldd-check test to fontconfig
  fontconfig.yaml
Labels: bincapz/pass

#44366 Add the ldd-check test to freetds
  freetds.yaml
Labels: bincapz/pass

#44370 Add the ldd-check test to gdbm
  gdbm.yaml
Labels: bincapz/pass

#44371 Add the ldd-check test to gmp
  gmp.yaml
Labels: bincapz/pass

#44376 Add the ldd-check test to gnutls
  gnutls.yaml
Labels: bincapz/pass

#44377 Add the ldd-check test to gobject-instrospection
  gobject-introspection.yaml
Labels: bincapz/pass

#44343 Add the ldd-check test to c-ares
  c-ares.yaml
Labels: bincapz/pass

#44236 add missing /etc/ssh/ssh_known_hosts file
  argo-cd-2.14.yaml
Labels: bincapz/pass, ai/skip-comment

#44367 Add the ldd-check test to frr-10.2
  frr-10.2.yaml
Labels: bincapz/pass

#44334 Add the ldd-check test to bzip3
  bzip3.yaml
Labels: bincapz/pass

#44342 Add the ldd-check test to cairo
  cairo.yaml
Labels: bincapz/pass

#44102 aws-cli-2: Enable test/ldd-check
  aws-cli-2.yaml
Labels: bincapz/pass

#44216 add bitnami compats to cert-manager
  cert-manager-1.17.yaml
Labels: bincapz/pass, ai/skip-comment

#44395 glibc: use merged path in the trigger
  glibc.yaml
Labels: bincapz/pass

#44398 Fix druid pombump and improve test
  druid.yaml
  druid/pombump-deps.yaml
  druid/pombump-properties.yaml
Labels: bincapz/pass

#44119 redis-operator-0.18.1 : new package
  redis-operator.yaml
Labels: bincapz/pass, approved-to-run

#44305 fix: remove `kustomize-sops.yaml` and add kustomize symlink
  ksops.yaml
  kustomize-sops.yaml
  withdrawn-packages.txt
Labels: bincapz/pass

#43542 gobject-introspection - separate binaries to -bin package.
  gobject-introspection.yaml
Labels: bincapz/pass

#44194 remove incorrect dependencies from spark
  spark-3.5.yaml
  spark-3.5/pombump-deps.yaml
Labels: bincapz/pass

#44469 bump the epoch for the changes made previously
  gobject-introspection.yaml
Labels: bincapz/pass

#44394 Add the ldd-check test to imagemagick-7
  imagemagick-7.yaml
Labels: bincapz/pass

#44393 Add the ldd-check test to icu
  icu.yaml
Labels: bincapz/pass

#44359 Add the ldd-check test to ffmpeg
  ffmpeg.yaml
Labels: bincapz/pass

#44476 fix(docker-selenium): add gettext as runtime which fails to start script
  docker-selenium.yaml
Labels: bincapz/pass, approved-to-run

#44479 ruby3.4-rails-8.0: bump epoch to pull in new gem versions
  ruby3.4-rails-8.0.yaml
Labels: bincapz/pass

#44477 ruby3.2-rails-8.0: bump epoch to pull in new gem versions
  ruby3.2-rails-8.0.yaml
Labels: bincapz/pass

#44478 ruby3.3-rails-8.0: bump epoch to pull in new gem versions
  ruby3.3-rails-8.0.yaml
Labels: bincapz/pass

#44473 ruby-3.2: bump uri and cgi gems to address vulnerabilities
  ruby-3.2.yaml
Labels: bincapz/pass

#44159 Build prism with ttypescript again
  prism.yaml
  prism/json_schema.patch
  prism/tsconfig.json.diff
Labels: bincapz/pass, approved-to-run

#44158 couchdb-3.3: Enable test/ldd-check
  couchdb-3.3.yaml
Labels: bincapz/pass

#44090 openmp-16: Enable test/ldd-check
  openmp-16.yaml
Labels: bincapz/pass

#44081 openmp-17: Enable test/ldd-check
  openmp-17.yaml
Labels: bincapz/pass

#44507 Add the ldd-check test to libdwarf
  libdwarf.yaml
Labels: bincapz/pass

#44523 remove patch since it breaks the app
  apache-tika-3.1.yaml
Labels: bincapz/pass

#42534 feat: build openssh with pam support
  openssh.yaml
  openssh/sshd.pam
Labels: bincapz/pass, ai/skip-comment

#44547 apache-tika improve test
  apache-tika-3.0.yaml
  apache-tika-3.1.yaml
Labels: bincapz/pass

#44546 Add the ldd-check test to libmnl
  libmnl.yaml
Labels: bincapz/pass

#44545 Add the ldd-check test to libmemcached
  libmemcached.yaml
Labels: bincapz/pass

#44544 Add the ldd-check test to libmd
  libmd.yaml
Labels: bincapz/pass

#44542 Add the ldd-check test to file
  file.yaml
Labels: bincapz/pass

#44541 Add the ldd-check test to libjpeg-turbo
  libjpeg-turbo.yaml
Labels: bincapz/pass

#44539 Add the ldd-check test to libinput
  libinput.yaml
Labels: bincapz/pass

#44537 Add the ldd-check test to libice
  libice.yaml
Labels: bincapz/pass

#44543 Add the ldd-check test to libmaxminddb
  libmaxminddb.yaml
Labels: bincapz/pass

#44485 Add the ldd-check test to isa-l
  isa-l.yaml
Labels: bincapz/pass

#44512 Add the ldd-check test to libgeotiff
  libgeotiff.yaml
Labels: bincapz/pass

#44483 Add the ldd-check test to inih
  inih.yaml
Labels: bincapz/pass

#44484 Add the ldd-check test to iniparser
  iniparser.yaml
Labels: bincapz/pass

#44489 Add the ldd-check test to jansson
  jansson.yaml
Labels: bincapz/pass

#44494 fix prism GHSA-hw8r-x6gr-5gjp
  prism.yaml
  prism/CVE-2025-1302.patch
Labels: bincapz/pass, approved-to-run

#44344 add py3-prettytable package with multi-version support and testing
  py3-prettytable.yaml
Labels: bincapz/pass, approved-to-run

#44633 envoy-ratelimit: ensure full history is checked out.
  envoy-ratelimit.yaml
Labels: bincapz/pass

#44511 Fix: usrmerge /bin busybox, coreutils, dash, util-linux
  busybox.yaml
  busybox/busyboxconfig
  busybox/busyboxconfig-full
  coreutils.yaml
  dash.yaml
  util-linux.yaml
  wolfi-baselayout.yaml
Labels: bincapz/pass, ai/skip-comment

#44501 add support for eth interfances named end*
  systemd.yaml
  systemd/22-end.network
Labels: bincapz/pass

#44577 usrmerge/bin: gzip
  gzip.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#43076 usrmerge /bin to /usr/bin
  container-entrypoint.yaml
  execline.yaml
  graphicsmagick.yaml
  kube-fluentd-operator.yaml
  management-api-for-apache-cassandra-5.0.yaml
  newrelic-nri-statsd.yaml
  php-8.1.yaml
  php-8.2.yaml
  php-8.3.yaml
  php-8.4.yaml
  py3-cassandra-medusa.yaml
  ruby3.2-fluentd-1.18.yaml
  ruby3.3-fluentd-1.17.yaml
  ruby3.4-fluentd-1.17.yaml
  s6.yaml
  vault-benchmark.yaml
  velero-plugin-for-aws.yaml
  velero-plugin-for-csi.yaml
  velero-plugin-for-microsoft-azure.yaml
  weaviate.yaml
  zsh.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#44590 Usrmerge jenkins-docker
  jenkins-docker.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#44657 merged-bin linkerd2
  linkerd2.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#43105 usrmerge /bin - Remove -compat packages
  argo-rollouts.yaml
  aws-s3-controller.yaml
  cloud-provider-aws-1.31.yaml
  cloud-provider-aws-1.32.yaml
  contour-1.30.yaml
  descheduler.yaml
  distribution.yaml
  envoy-ratelimit.yaml
  gitlab-cng-17.8.yaml
  gitlab-cng-17.9.yaml
  gitlab-pages-17.9.yaml
  grafana-alloy.yaml
  grafana-rollout-operator.yaml
  grpc-health-probe.yaml
  kafka_exporter.yaml
  mountpoint-s3-csi-driver.yaml
  prometheus-operator.yaml
  promxy.yaml
  secrets-store-csi-driver-provider-aws.yaml
  secrets-store-csi-driver-provider-azure.yaml
  sql_exporter.yaml
Labels: bincapz/pass, approved-to-run, ai/skip-comment

#44593 Build gcc w/ iconv support to fix 93 glibc test case failures
  gcc.yaml
Labels: bincapz/pass

#44005 add nginx-bitnami
  nginx-mainline.yaml
Labels: bincapz/pass

#44677 gn: bump to latest git snapshot
  gn.yaml
Labels: bincapz/pass

#44642 kubernetes-csi-node-driver-registrar-2.13: bump epoch to build with newer Go
  kubernetes-csi-node-driver-registrar-2.13.yaml
Labels: bincapz/pass

#44589 spark-3.5/GHSA-4g8c-wm8x-jfhw custom image subpackage name fix and other dependency updates
  spark-3.5.yaml
  spark-3.5/pombump-deps.yaml
  spark-3.5/pombump-properties.yaml
Labels: bincapz/pass

#44679 ruby3.4-rack: add basic functional test
  ruby3.4-rack.yaml
Labels: bincapz/pass

#44715 fix rrdtool FTBFS after /sbin usrmerge
  rrdtool.yaml
Labels: bincapz/pass

#44770 bump renovate to 39.188.2
  renovate.yaml
Labels: bincapz/pass

#44653 fix(mysql): update entrypoint to log from stdin correctly
  mysql-9.1.yaml
  mysql-9.1/docker-entrypoint.sh
Labels: bincapz/pass

#44638 feat: add kots-compat subpackage to kots
  kots.yaml
Labels: bincapz/pass

#44795 add additional tests for syft
  syft.yaml
Labels: bincapz/pass

#44644 python: Use more generic march for rosetta compatibiity
  python-3.10.yaml
  python-3.11.yaml
  python-3.12.yaml
  python-3.13.yaml
Labels: bincapz/pass, ai/skip-comment

#44794 Use merged-bin location for any shell
  glibc.yaml
Labels: bincapz/pass

#44862 go-discover: remediate CVE-2025-22868, CVE-2025-22869
  go-discover.yaml
Labels: bincapz/pass

#44885 kserve: bump jinja2 to 3.1.6
  kserve.yaml
Labels: bincapz/pass

#44884 kubeflow-pipelines-visualization-server: bump jinja2 to 3.1.6
  kubeflow-pipelines-visualization-server.yaml
  kubeflow-pipelines-visualization-server/0001-Bump-dependencies.patch
Labels: bincapz/pass

#44877 kubeflow-volumes-web-app: bump jinja2 to 3.1.6
  kubeflow-volumes-web-app.yaml
  kubeflow-volumes-web-app/upgrade-jinja2.patch
Labels: bincapz/pass

#44874 emissary: bump jinja2 to 3.1.6
  emissary.yaml
Labels: bincapz/pass

#44872 airflow: rebuild to pull in new jinja2 version
  airflow.yaml
Labels: bincapz/pass

#44889 feat: openssh with pam support
  openssh.yaml
Labels: bincapz/pass

#44894 mlflow: rebuild to include jinja2 3.1.6
  mlflow.yaml
Labels: bincapz/pass

#44904 adding some more top level font tests, bump epoch to run tests and re…
  font-noto.yaml
  font-util.yaml
Labels: bincapz/pass

#44888 kubeflow-jupyter-web-app: rebuild for jinja2 vuln fix, clean up some dependency munging
  kubeflow-jupyter-web-app.yaml
Labels: bincapz/pass

#44905 Fix: openssh pam config subpackage name.
  openssh.yaml
  withdrawn-packages.txt
Labels: bincapz/pass

#44783 pypy3: remove pypy-bootstrap and build pypy3 standalone.
  pypy-3.10.yaml
  pypy-3.11.yaml
  pypy-bootstrap.yaml
  withdrawn-packages.txt
Labels: bincapz/pass

#44950 Revert "python: Use more generic march for rosetta compatibiity (#44644)"
  python-3.10.yaml
  python-3.11.yaml
  python-3.12.yaml
  python-3.13.yaml
Labels: bincapz/pass

#44972 Revert "add nginx-bitnami"
  nginx-mainline.yaml
Labels: bincapz/pass

#44703 Add the ldd-check test to libxau
  libxau.yaml
Labels: bincapz/pass

#44933 use the test/docs pipeline for hello-wolfi
  hello-wolfi.yaml
Labels: bincapz/pass

#44746 Add the ldd-check test to luajit
  luajit.yaml
Labels: bincapz/pass

#44744 Add the ldd-check test to lsof
  lsof.yaml
Labels: bincapz/pass

#44742 Add the ldd-check test to lmdb
  lmdb.yaml
Labels: bincapz/pass

#44735 Add the ldd-check test to linux-pam
  linux-pam.yaml
Labels: bincapz/pass

#44734 Add the ldd-check test to libyang
  libyang.yaml
Labels: bincapz/pass

#44731 Add the ldd-check test to libxshmfence
  libxshmfence.yaml
Labels: bincapz/pass

#44698 Add the ldd-check test to libvorbis
  libvorbis.yaml
Labels: bincapz/pass

#44700 Add the ldd-check test to libwebp
  libwebp.yaml
Labels: bincapz/pass

#44733 Add the ldd-check test to libxxf86vm
  libxxf86vm.yaml
Labels: bincapz/pass

#44726 Add the ldd-check test to libxdamage
  libxdamage.yaml
Labels: bincapz/pass

#44719 Add the ldd-check test to libxcvt
  libxcvt.yaml
Labels: bincapz/pass
